### ISSUE TITLE
Add complete SMuFL guitar range

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#100]
MusicXML could complete its support for the SMuFL guitar range U+E830–U+E84F for better interoperability between applications. The range is documented at http://w3c.github.io/smufl/gitbook/tables/guitar.html.

MusicXML 3.0 already supports the string symbols in this range. Completing the range would involve adding:
- The vibrato bar scoop and dip glyphs U+E830 and U+E831, likely working together with the MusicXML with-bar element 
- The wah/volume pedal glyphs U+E83D-U+E83F
- The left-hand and right-hand tapping glyphs U+E840 and U+E841, working together with the MusicXML tap element
- The golpe glyph U+E842
- The fade in / fade out / swell glyphs U+E843-U+E845
- The strum direction glyphs U+E846 and U+E847
- The barré glyphs U+E848 and U+E849

This issue arose while analyzing MusicXML 3.0 for SMuFL support in preparation for the 2015 MusicXML community meeting at Musikmesse. Requests for some of these symbols have also been made by MusicXML developers in private emails.

**Comment by asieralkortaformazioa** [comment]
Regarding the tapping glyphs, it's cool to have those new symbols, but it could be even more useful if the symbols added information about which finger is used in the tapping. 

For example, instead of the "T" of tapping, "I" could be used to represent that the tapping should be done using the index finger, "M" for middle, "R" for ring, "L" for little finger and "T" for the thumb.

Another coding system could be used to display this information, but I think including it could be useful.

**Comment by mdgood** [comment]
My current thoughts are to

- Use with-bar element content of "scoop" and "dip" for the guitarVibratoBarScoop and guitarVibratoBarDip glyphs.
- Add a new "hand" attribute with values of "left" and "right" to the tap element for the guitarLeftHandTapping and guitarRightHandTapping glyphs. The proposal to encode tapping fingers is interesting but seems perhaps beyond the scope of this issue and MusicXML 3.1.
- Add a new "golpe" element for the guitarGolpe glyph. We have had requests for the golpe symbol for many years.

Some of the other glyphs have already been handled by smufl attributes on other elements - for instance, guitarStrumUp and guitarStrumDown have been handled by issue #79 when we added the smufl attribute to the `<arrow>` element. The remaining glyphs could be handled by using the `<other-technical>` element with the appropriate smufl attribute.

However, I am not very knowledgeable about guitar notation. It would be great if some of our more guitar-knowledgeable group members could review this and suggest improvements if needed. @adrianholovaty, what do you think about this proposal?

Thanks for any assistance on this issue!

**Comment by adrianholovaty** [comment]
@mdgood These proposals all sound reasonable to me. :-)

**Comment by mdgood** [comment]
Thanks @adrianholovaty! Pull request #201 addresses this issue. Might you have a chance to review the pull request?

**Comment by adrianholovaty** [comment]
@mdgood Done! Looks good to me.

**Comment by mdgood** [comment]
Thanks for the review Adrian!

**Comment by snakebyte69** [comment]
The "with-bar" element also needs "warble" to be added to it.

Warble is a technique where you quickly strike the whammy bar to make it vibrate quickly, this produces a very distinct type of vibrato. It's a very common technique in Heavy Metal used by players like Jason Becker, Steve Vai, John Petrucci and many others.

**Comment by GualtieroChiapello** [comment]
On the final page of the score "Pictures at an Exhibition" (Mussorgsky - Mar.1981) of the arrangement by the classical guitar master Kazuhito Yamashita there are elements of notation with their meaning: strangely they have not yet been considered.

Example:
![yamashita](https://user-images.githubusercontent.com/60393694/73272000-ef82df80-41e1-11ea-8b31-5fee687284a5.png)
