### ISSUE TITLE
Add complete SMuFL lyrics range

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#101]
MusicXML could add support for the SMuFL lyrics range U+E550–U+E55F for better interoperability between applications. The range is documented at http://w3c.github.io/smufl/gitbook/tables/lyrics.html.

In SMuFL 1.19, this range contains 5 varieties of elision symbols. MusicXML 3.0's elision element allows one to specify Unicode text content for an elision symbol, but does not cover all the SMuFL variations, such as the narrow, normal, and wide variations of the undertie elision symbol. On the other hand, SMuFL doesn't include all possible MusicXML elision symbols, such as a non-breaking space.

One potential way to add SMuFL elision support for the lyrics range would be to have a SMuFL attribute that could contain one of the SMuFL lyrics range unique glyph names (e.g. lyricsElisionWide, not U+E552). MusicXML would need to define which value should take priority if both the attribute and text content are present in a single element.

This issue arose while analyzing MusicXML 3.0 for SMuFL support in preparation for the 2015 MusicXML community meeting at Musikmesse. The idea of allowing specification of SMuFL unique names at different points within the MusicXML format was suggested by Martin Marris and Peter Trubinov at the 2014 MusicXML community meeting.

**Comment by joeberkovitz** [comment]
I do not think we should attack text formatting or inclusion of special symbols in text without a broader discussion of text treatment in MusicXML.

**Comment by artexanis** [comment]
I agree. For example: 'The font-size can be one of the CSS font sizes or a numeric point size.'
As far as I know it's the only vertical metric not being expressed in tenths.
In my experience it's sometimes inpossible to determine the exact font-size in relation to the staff.

**Comment by joeberkovitz** [comment]
@mdgood Now that I understand that this would only be applied in an `<elision>` element as a way of customizing the flavor of elision that it would use, I think this is reasonable to do.

**Comment by mdgood** [comment]
The proposed solution would be to rename the text-font-color complex type in the XSD schema as the elision type, and add a "smufl" attribute group to the definition of the elision type. The interaction between the smufl attribute and the text content of the elision element would be documented something like this:

> If the elision element is empty, the smufl attribute is used to determine which elision glyph to use. The glyph name in the smufl attribute should come from the SMuFL lyrics range. The SMuFL attribute is ignored if the elision glyph is already specified by text content in the elision element. If neither text content nor a smufl attribute are present, the elision glyph is application-specific.

Corresponding changes would be made in the note.mod and to30.xsl files.

Comments and suggestions welcome!

**Comment by mdgood** [comment]
As in issue #84, we can tighten up the definition of the smufl attribute by creating a new simple type that uses a pattern to enforce the restriction to the SMuFL lyrics range:
```
	<xs:simpleType name="smufl-lyrics-glyph-name">
		<xs:annotation>
			<xs:documentation>The smufl-lyrics-glyph-name type is used to reference a specific Standard Music Font Layout (SMuFL) lyrics elision character. The value is a SMuFL canonical glyph name that starts with lyrics.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="smufl-glyph-name">
			<xs:pattern value="lyrics\c+"/>
		</xs:restriction>
	</xs:simpleType>
```

**Comment by mdgood** [comment]
Pull request #182 addresses this issue.
