### ISSUE TITLE
Add more comprehensive piano pedal indications

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#102]
MusicXML 3.0's pedal element could be enhanced to cover all the pedal indications displayed in Elaine Gould's book _Behind Bars_ in table 2 on page 333. This would involve adding text indications to the sign and line indications already supported in MusicXML 3.0.

It would also be useful to include at least the two main alternative symbols for the damper and sostenuto pedal covered in SMuFL's [keyboard techniques range](http://w3c.github.io/smufl/gitbook/tables/keyboard-techniques.html). These are glyphs U+E650 and U+E651 for the damper pedal, and glyphs U+E659 and U+E65A for the sostenuto pedal.

MusicXML 3.0 lets you get the graphical appearance of these text and line pedal marks by using a combination of the words and bracket element. However, this loses the semantics behind the pedal element.

See the discussion started by James Sutton (@jsutdolph) on the MusicXML forum: http://forums.makemusic.com/viewtopic.php?f=12&t=2902.

**Comment by mdgood** [comment]
Here is an initial idea for how we could do this in MusicXML 3.1.
- Change the start-stop-change-continue simple type to a pedal-type simple type, and add a "sostenuto" enumeration values. This refers to starting a sostenuto pedal. The "change" and "stop" values continue to be used for both damper and sostenuto pedals. Clarify the documentation to indicate that the "start" type value refers to the damper pedal.
- Add an "abbreviated" attribute which is only used if the sign attribute is set to "yes" and the type is "start" or "sostenuto". This will have a yes-no type. A value of "yes" refers to SMuFL glyphs U+E651 or U+E65A; a value of "no" refers to SMuFL glyphs U+E650 or U+E659.

I originally had a proposal to add text content to the pedal element for the full coverage of page 333 table 2 directly in semantic representation. However, that is different than how MusicXML represents text / line content anywhere else. That type of issue seems best reserved for MNX, especially given the piano pedal playback features of the sound element in MusicXML 3.0.

Do you think this more constrained approach would be useful, @jsutdolph? Is there a different implementation that you would prefer that still stays within the MusicXML 3.0 framework?

**Comment by jsutdolph** [comment]
Thanks for this Michael.
Could you define the new pedal-type here to make it more explicit?
No mention of una corda / tre corde notation for soft pedal?
I am happy if we keep it as a simple enumeration as you suggest since this makes it simpler to render
James @jsutdolph Sutton

**Comment by mdgood** [comment]
The new pedal-type simple type would look something like this. The documentation includes an explanation of why there is no una corda / tre corde notation here. Does this look OK?

```
	<xs:simpleType name="pedal-type">
		<xs:annotation>
			<xs:documentation>The pedal-type simple type is used to distinguish types of pedal directions. The "start" value indicates the start of a damper pedal, while the "sostenuto" value indicates the start of a sostenuto pedal. The change, continue, and stop elements can be used with either the damper or sostenuto pedal. The soft pedal is not included here because there is no special symbol or graphics used for it beyond what can be specified with words and bracket elements.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="start"/>
			<xs:enumeration value="stop"/>
			<xs:enumeration value="sostenuto"/>
			<xs:enumeration value="change"/>
			<xs:enumeration value="continue"/>
		</xs:restriction>
	</xs:simpleType>
```

**Comment by jsutdolph** [comment]
This looks good, but perhaps you now need to add a "number" attribute to "pedal" since you could have 2 simultaneous pedals. Not being a pianist I don't know if this can occur!

**Comment by mdgood** [comment]
Good catch! Thanks James. Overlapping pedals can occur, as in the example on page 333 of _Behind Bars_. That uses words which we could handle with bracket elements. But it makes sense that sostenuto and damper pedals could overlap, so I think the number attribute is a good idea. 

The updated pedal complex type would then look something like this:
```
	<xs:complexType name="pedal">
		<xs:annotation>
			<xs:documentation>The pedal type represents piano pedal marks. In MusicXML 3.1 this includes sostenuto as well as damper pedal marks. The line attribute is yes if pedal lines are used. The sign attribute is yes if Ped, Sost, and * signs are used. For MusicXML 2.0 compatibility, the sign attribute is yes by default if the line attribute is no, and is no by default if the line attribute is yes. If the sign attribute is set to yes and the type is start or sostenuto, the abbreviated attribute is yes if the short P and S signs are used, and no if the full Ped and Sost signs are used. It is no by default. Otherwise the abbreviated attribute is ignored.

The change and continue types are used when the line attribute is yes. The change type indicates a pedal lift and retake indicated with an inverted V marking. The continue type allows more precise formatting across system breaks and for more complex pedaling lines. The alignment attributes are ignored if the line attribute is yes.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="type" type="pedal-type" use="required"/>
		<xs:attribute name="number" type="number-level"/>
		<xs:attribute name="line" type="yes-no"/>
		<xs:attribute name="sign" type="yes-no"/>
		<xs:attribute name="abbreviated" type="yes-no"/>
		<xs:attributeGroup ref="print-style-align"/>
	</xs:complexType>
```
How does this look?

**Comment by jsutdolph** [comment]
This looks good

**Comment by mdgood** [comment]
Pull request #171 addresses this issue.
