### ISSUE TITLE
Remove reference to parentheses attribute from interchangeable complex type

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#12]
Evan Brooks (@ebrooks01) found an error in the XSD documentation on the interchangeable complex type. The last sentence references a non-existent parentheses attribute and should be removed. 

This is at line 2428 in the musicxml.xsd file in MusicXML 3.0. The DTD documentation does not have this error.

See the MusicXML forum discussion at http://forums.makemusic.com/viewtopic.php?f=12&t=2710.

**Comment by mdgood** [comment]
The fix for this is in the description - the last sentence of the interchangeable complex type documentation should be removed. This is now on line 2431 of the current musicxml.xsd draft.

**Comment by lasconic** [comment]
You mean here https://github.com/w3c/musicxml/blob/5d84a04a19d9603729b882be2a96dfa353ceea53/schema/musicxml.xsd#L2431

See http://andrew.yurisich.com/work/2014/07/16/dont-link-that-line-number/

**Comment by mdgood** [comment]
Thanks for the tip! I'll add links for the other documentation issues.

**Comment by mdgood** [comment]
Pull request #117 addresses this issue.
