### ISSUE TITLE
Correct "cancel" documentation

### ISSUE THREAD

**Issue by ebrooks01** [w3c/musicxml#125]
The XSD and web documentation (and perhaps others) for the "cancel" element read in part:

"The optional location attribute indicates whether the cancellation appears relative to the new key signature"

It should read:

"The optional location attribute indicates where the cancellation appears relative to the new key signature"

**Comment by mdgood** [comment]
This appears to be a duplicate of #18 which is already fixed. Since it was closed and didn't have your correct Github ID, that would be easy to miss. I'm closing this but please reopen if I am missing something.
