### ISSUE TITLE
Clarify key-octave documentation/definition

### ISSUE THREAD

**Issue by ebrooks01** [w3c/musicxml#126]
The MusicXML XSD documentation for key-octave states in part:

"If the cancel attribute is set to yes, then this number refers to an element specified by the cancel element."

Since the key-octave element can be used with both traditional and non-traditional key signatures, but the cancel element is only used with traditional key signatures, the documentation above and/or the XSD definition should somehow restrict its usage to traditional keys.  Perhaps:

"If the cancel attribute is set to yes, then this number refers to an element specified by the cancel element. The cancel element cannot be set to yes if the key element it is embedded in is a traditional key."

**Comment by mdgood** [comment]
Another way to update the documentation would be something like:

"If the cancel attribute is set to yes, then this number refers to an element specified by the cancel element. The cancel attribute cannot be set to yes if there is no corresponding cancel element within the parent key element."

Does that look good to you?

**Comment by ebrooks01** [comment]
Hi Michael,

I see two problems here.  In the first sentence, it says:

“...an element specified by the cancel element.”

The problem is that the key-octave element does not have a cancel element. It only has a cancel attribute. In addition, the cancel attribute does not “specify” an element, and the parent key element’s cancel element does not “specify” any element either. I think the original intent was to say:

“…the canceling key signature specified by the cancel element in the parent key element.”

If this sounds right to you, then I would suggest that the offending paragraph be rewritten as:

"If the cancel attribute is set to yes, then this number refers to the canceling key signature specified by the cancel element in the parent key element. The cancel attribute cannot be set to yes if there is no corresponding cancel element within the parent key element.”

I think this ties it all together nicely.  Your thoughts?

—Evan

**Comment by mdgood** [comment]
That looks good to me and much clearer than my proposal. Thanks for this suggestion!

**Comment by mdgood** [comment]
I have created a pull request for this issue at https://github.com/w3c/musicxml/pull/141. @ebrooks01, please let me know if this looks good to you - thanks!

**Comment by ebrooks01** [comment]
Looks good. Thanks, Michael.

--Evan
