### ISSUE TITLE
Clarify definition of String element in MusicXML

### ISSUE THREAD

**Issue by ebrooks01** [w3c/musicxml#127]
The String element documentation in the XSD says in part:

'String numbers start with 1 for the highest string."

Other areas of the XSD that deal with string numbers further clarify which string is meant by using the term "highest pitched string".  In this case, however, pitch is not the determining factor (banjo would be a good example), but rather "height from the floor", where the highest string really means the highest one off the floor when the instrument is strung normally and held horizontally.  Upright string instruments would challenge this definition, so maybe further clarification about the orientation of the strings is also required.  

Complicating matters is whether the term "highest string" is referring to the physical string on the instrument, or to the staff line in the music that is representing that string. Tablature generally inverts the two, representing the string that is physically highest off the floor as the lowest staff line off the floor.

So it seems that the term "highest string" is not sufficient in any case, for the above reasons.

**Comment by mdgood** [comment]
Thank you for raising this issue, Evan. The string-number type uses the highest pitched string terminology. This type is what the string element uses, so it would be straightforward to modify the string element documentation in the XSD and DTD from "highest string" to "highest pitched string".

But that does not deal with the banjo issue. Would that be addressed by specifying the "highest pitched full-length string" instead? What do you think, @ebrooks01 and @mscuthbert? Is there another way to better clarify this?

I think the issue of tablature staff lines being counted from the bottom while string numbers are counted from the top is already addressed in the documentation for the staff-line type and the line element, which specifying counting starting from the bottom of the staff.

**Comment by mdgood** [comment]
Pull request #169 addresses this issue.
