### ISSUE TITLE
Multiple Flats or Sharps

### ISSUE THREAD

**Issue by webern** [w3c/musicxml#128]
Consider a note that has the following pitch definition:

< pitch >
  < step >A< /step >
  < alter >4< /alter >
  < octave >4< /octave >
< /pitch >

This cannot be properly represented with accidental marking in MusicXML because the accidental element is an enumeration with no "quadruple-sharp" value.

Maybe this isn't a big deal since maybe these rarely (never?) come up in real music, but it strikes me as an unintended limitation.  I guess most notation programs allow these extended accidentals which are then lost in a musicxml roundtrip.  See image for a Finale -> MusicXML -> Finale roundtrip using the Dolet plugin.

<img width="637" alt="multiaccidentals" src="https://cloud.githubusercontent.com/assets/6260372/15095316/bf9a292e-1475-11e6-9a09-39270109969d.png">

**Comment by mdgood** [comment]
Thank you for this suggestion. I know of no repertoire that makes use of quadruple sharps and flats. Even triple sharps and flats are very rare (see http://homes.soic.indiana.edu/donbyrd/CMNExtremes.htm#pitch). This is an intentional exclusion from MusicXML 3.0 that I believe should be carried over to MusicXML 3.1.

**Comment by mdgood** [comment]
Also, issue #109 will allow more flexibility for specifying accidentals that have SMuFL symbols that go beyond the MusicXML enumeration values. These accidentals are not in SMuFL for the same reason they are not in MusicXML; they don't occur in actual repertoire to the best of our knowledge.

**Comment by mscuthbert** [comment]
I know of one piece of musicological literature that discusses quadruple flats (discussing a passage from Beethoven, I believe, Waldstein, where if not for enharmonic reinterpretation, the passage would go to quadruple flats and then return), but never in actual repertoire.
