### ISSUE TITLE
Add SMuFL articulations supplement range

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#131]
MusicXML could add support for the SMuFL articulations supplement range U+ED40–U+ED4F for better interoperability between applications. The range is documented at https://w3c.github.io/smufl/gitbook/tables/articulation-supplement.html.

This would involve adding support for the soft accent symbol. MusicXML currently represents combinations of articulations (accent plus tenuto, etc.) with two separate articulations for the component parts. This technique would allow MusicXML support for the entire range with the addition of a single new element.

Originally issue #52 included coverage for the visually and semantically similar messa di voce symbol U+E540 in the SMuFL dynamics range. However, the articulations supplement range is more comprehensive and generally useful. Its addition to SMuFL 1.2 supersedes the need for separate messa di voce symbol support.

Robert Patterson (@rpatters1) requested adding the messa di voce symbol on the MusicXML forum: http://forums.makemusic.com/viewtopic.php?f=12&t=2250#p5980. He also requested an inverted version of the messa di voce symbol for a reverse swell. If that were added to the SMuFL dynamics range it could also be added to MusicXML.

**Comment by mdgood** [comment]
One solution for this would be to add a`<xs:element name="soft-accent" type="empty-placement">` to the xs:choice element in the articulations complex type. The corresponding changes would also be made in the note.mod DTD and to30.xsl files.

**Comment by jsawruk** [comment]
For example, support for SMuFL's articSoftAccentStaccatoAbove (U+ED42) would be accomplished with the following code:

```
<notations>
  <articulations>
    <soft-accent placement="above" />
    <staccato placement="above"/>
  </articulations>
</notations>
```

The placement attributes of both elements would need to match to produce the correct SMuFL glyph. If they did not match, the result would then be two glyphs. For example, this code would result in SMuFL's articSoftAccentAbove (U+ED40) appearing above the note with a staccato appearing below the note.

```
<notations>
  <articulations>
    <soft-accent placement="above" />
    <staccato placement="below"/>
  </articulations>
</notations>
```

See the attached notation excerpt for an example. Is this correct?
![musicxml soft accent example](https://cloud.githubusercontent.com/assets/422233/18925243/29254dca-8581-11e6-8520-63bb2517972c.png)

**Comment by mdgood** [comment]
This looks good to me - it is consistent with how MusicXML 3.0 does things. We might want to revisit this in MNX, but for MusicXML 3.1 this seems like the right approach.

**Comment by school510587** [comment]
The document for soft-accent seems not to have leading tabs, which causes inconsistency with document for other elements.

**Comment by mdgood** [comment]
Thanks for catching this issue in the note.mod file. With all the whitespace changes we missed that in the pull request. I'll fix this now.

**Comment by mdgood** [comment]
@school510587, could you please put your GitHub ID in the community group Wiki for contributors at https://www.w3.org/community/music-notation/wiki/Contributors? Or just let me know your name and I can make the edit there. It is helpful to associate GItHub IDs with member names. Thanks so much!

**Comment by school510587** [comment]
Sorry, I don't have an account of your community, so I can't edit the table by myself. My profile is here.
Name: Bo-Cheng Jhan (詹博丞 in Chinese, or you can call me Sponge Jhan)
Organisation: Now I'm a Ph.D. student of Computer Science and Information Engineering (CSIE), National Cheng Kung University (NCKU), Taiwan
GitHub username: school510587
Area of interest: Braille Music, automatic transcription from MusicXML or other formats into Braille
Please let me know if there is any problem about this. Thanks!

**Comment by school510587** [comment]
By the way, I checked out 131-soft-accent-whitespace, and found that there were initial 4 spaces rather than one tab character in note.mod.

**Comment by mdgood** [comment]
Thanks, 詹博丞! Please do join the W3C Music Notation Community Group given your interests. Membership is free of charge. You can start the signup process by clicking the JOIN THIS GROUP button at https://www.w3.org/community/music-notation/.

I reviewed the pull request and I am seeing the leading whitespace as being consistent with the rest of the note.mod DTD. The comments lead with a tab, while the ATTLIST definition leads with 4 spaces. I do not recall why the leading whitespace is handled differently in these two cases. For now we want to keep the new additions consistent with the rest of the file. Does that match what you are seeing?

**Comment by school510587** [comment]
I never view your document on Github. I check them in 2 ways:
(1) git clone (I prefer this method)
(2) download code as musicxml-131-soft-accent-whitespace.zip from Github
Your ATTLIST has no problem. However, I find 4 leading spaces rather than one tab in soft-accent specification from checkouted note.mod using both ways above.

**Comment by mdgood** [comment]
Thank you for the follow-up. I now see what you were seeing. I don't know why I missed it before! It should be fixed now in the current pull request.

**Comment by school510587** [comment]
Ah, sorry, I used Bo-Cheng Jhan for my given/family name, and it seems to be not modifiable.
I have received a letter showing that my membership was approved.
Is it ok? Originally I thought it was better to use a name spelled in English, because almost everyone registered name in English.
Thanks!

**Comment by mdgood** [comment]
This sounds good. You are not listed as a group participant yet, but there is probably a short delay in getting this information updated. I will check again tomorrow and let you know if there is any problem.

**Comment by school510587** [comment]
I think I have caught the problem. I didn't click JOIN THIS GROUP button after creating a W3C account.
@mdgood, could you check my participation again? Thanks!

**Comment by mdgood** [comment]
You are now listed as a participant and we have added your information to the contributor Wiki. Thanks!

**Comment by school510587** [comment]
OK, thanks! I'll try to fill in other fields of my row with data mentioned above.

**Comment by school510587** [comment]
Sorry to ask this silly question.
Now there are accent (greater-than sign in piano scores) and soft-accent (less-than sign followed by greater-than sign) in MusicXML.
However, is there a way to encode an accent mark pointing to the left? Some scores use it rather than a typical greater-than sign.

**Comment by mdgood** [comment]
I am not familiar with that use of an accent mark. SMuFL does include that glyph for guitar fade-in. It is the guitarFadeIn glyph at https://w3c.github.io/smufl/gitbook/tables/guitar.html. So you could use an `<other-articulation smufl="guitarFadeIn"/>` element to specify that symbol.

**Comment by school510587** [comment]
Do you means that I may specify an attribute smufl="guitarFadeIn" for other-articulation element to produce a less-than sign above/below a note to achieve my previous description?
Sorry to provide no detailed data for the accent pointing to the left.
I didn't find any name related to it, and my friends playing piano always say that they determine their performance based on the appearance of articulation/technical marks, rather than name or other textual information.

**Comment by mdgood** [comment]
Right - there's no name because that is not a standard articulation for an accent. This is new to MusicXML 3.1 so it won't be working in application software quite yet.

**Comment by school510587** [comment]
OK, thanks. Braille music has its own way to represent such a "reversed" accent, so I must know how to encode it in MusicXML despite how many applications will support this.

**Comment by mdgood** [comment]
Pull requests #148 and #149 address this issue.
