### ISSUE TITLE
accordion-middle should support zero dots

### ISSUE THREAD

**Issue by webern** [w3c/musicxml#134]
This is what the specification says

`<xs:simpleType name="accordion-middle">
        <xs:annotation>
            <xs:documentation>The accordion-middle type may have values of 1, 2, or 3, corresponding to having 1 to 3 dots in the middle section of the accordion registration symbol.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="3"/>
        </xs:restriction>
    </xs:simpleType>`

This is what I think it should say

`<xs:simpleType name="accordion-middle">
        <xs:annotation>
            <xs:documentation>The accordion-middle type may have values of 1, 2, or 3, corresponding to having 1 to 3 dots in the middle section of the accordion registration symbol.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:nonNegativeInteger">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="3"/>
        </xs:restriction>
    </xs:simpleType>`

Evidence http://www.duckmandu.com/notation/
Shows accordion symbols with zero dots in the middle.

Disclaimer: I don't know anything about Accordion.

**Comment by jsawruk** [comment]
If you're going to change the range of values from 0 to 3, then the documentation should reflect this as well. Here's my proposal based on yours:

`<xs:simpleType name="accordion-middle"> <xs:annotation> <xs:documentation>The accordion-middle type may have values of 0, 1, 2, or 3, corresponding to having 0 to 3 dots in the middle section of the accordion registration symbol.</xs:documentation> </xs:annotation> <xs:restriction base="xs:nonNegativeInteger"> <xs:minInclusive value="0"/> <xs:maxInclusive value="3"/> </xs:restriction> </xs:simpleType>`

**Comment by webern** [comment]
Right, thanks for catching that.

**Comment by mdgood** [comment]
Thanks for raising this issue. 0 dots in a section are represented in MusicXML 3.0 by omitting the corresponding element. I think that the issue here is clarifying the documentation for the accordion-registration element and its children, so I will add a Documentation label here.

**Comment by mdgood** [comment]
This could be clarified by adding "This element is omitted if no dots are present" to the end of the accordion-middle documentation. The sentence "This element is omitted if no dot is present" could likewise be added to the documentation for the accordion-high and accordion-low elements.

**Comment by mdgood** [comment]
Pull request #162 addresses this issue. The documentation updates turned out a little bit different than what I proposed earlier. @Webern, could you please review the pull request to be sure the documentation is clarified appropriately?

The copyright notices were also updated for 2017. That change is in a separate commit from the documentation changes for this issue.

**Comment by webern** [comment]
Yes, the rewrite is more clear.  Thank you.  There is a wrong word typo
If not dots are present
should be
If no dots are present

**Comment by mdgood** [comment]
Thanks for the quick review. The typo should be fixed now.
