### ISSUE TITLE
Remove font attributes from extend element

### ISSUE THREAD

**Issue by ebrooks01** [w3c/musicxml#140]
The extend element has no text in it - it just represents a horizontal line.  As such, the definition of the extend element should not include any font attributes.  The definition of the extend element should be updated to either remove the font attributes (preferred solution), or to add a note indicating that any included font attributes are to be ignored.

**Comment by mdgood** [comment]
Specifically, in the xsd the print-style attribute group in the extend complex type should be replaced by the position and color attribute groups, and similarly for the extend element definition in the note.mod file.

**Comment by mdgood** [comment]
Pull request #155 addresses this issue.
