### ISSUE TITLE
Usage Clarification and Specification for Single-Ended Ties

### ISSUE THREAD

**Issue by ebrooks01** [w3c/musicxml#142]
On occasion, it is necessary to describe single-ended ties in a MusicXML document.  There have been several attempts to explain exactly how such ties are encoded (and therefore interpreted) in MusicXML, but none have been sufficiently unambiguous and complete in their coverage of the possible use cases.

I propose that single-ended ties by officially described and their implementation documented within MusicXML, so that all generating and reading applications can correctly describe and render them.

In conversations, three distinct use cases have been identified, and will be described below, along with the proposed encoding for them:

(1) Tie with no starting note

This describes a tie whose beginning does not start on any note, but whose ending ends on note.  An example of this situation would be a note at the start of a second ending in a repeated section, where the tie (a complete one) is actually also shown going into the first ending.

The implication here is that this case represents a tie that does in fact have a note that it starts on, but it is notated for convenience without starting on any note.

This case is notated by having the tie's ending note containing:

"tie" element, type = stop
"tied" element, type = stop

There are no other "tie" or "tied" elements used on this note to describe this particular tie.

It is up to the application reading this MusicXML file to see that there is no corresponding note element that would correspond to a visual starting note for this tie end note, because without looking at the context within the file, this note could not be distinguished from a tie ending note that does in fact have a tie starting note.

(2) Tie with no ending note ("let ring")

This describes a note in the middle of piece, rather than at the end, in which the author's intent is to "let the note ring".  There is no note in the document that would serve as an "ending note" to the tie.

This case is notated by having the tie's starting note containing:

"tied" element, type = start
"tied" element, type = stop

Note that there are no "tie" elements on this note, indicating that there is no real note that this note is tied to.

It is up to the application reading this MusicXML file to see that there is no corresponding note element that would correspond to a visual ending note for this tie start note, because without looking at the context within the file, this note could not be distinguished from a tie starting note that is in the middle of a chain of two "tied"s.

(3) Tie with no ending note

This describes, for example, a note at the end of a repeated section, which is tied to a note back at the beginning of that repeated section.  There is an actual note in the document that would serve as an "ending note" to the tie, but as a graphical convenience, it is notated as a tie with no ending note.

This case is notated by having the tie's starting note containing:

"tie" element, type = start
"tied" element, type = start

Note that there is a "tie" element on this note, indicating that there is a real note that this note is tied to.

It is up to the application reading this MusicXML file to see that there is no corresponding note element that would correspond to a visual ending note for this tie start note, because without looking at the context within the file, this note could not be distinguished from a tie starting note that does in fact have a tie ending note.

---

There is a school of thought that prefers having an encoding of these three circumstances that does not rely on having to do a contextual search of the rest of the document in order to determine that these ties are single-ended.

Such an implementation could, for example, supplement the above suggestions with an additional <single-ended> element, thus making explicit that the given tie is only attached to the given note, and not to any others.

From a MusicXML parsing perspective, having this additional clue would be much more efficient.

---

Comments would be appreciated.

--Evan

**Comment by Glenn-smufl** [comment]
On 9/6/2016 4:07 PM, ebrooks01 wrote:

> There is a school of thought that prefers having an encoding of these
> three circumstances that does not rely on having to do a contextual
> search of the rest of the document in order to determine that these ties
> are single-ended.

I would be counted in with members of this school of thought.  Explicit 
is better than implicit.

**Comment by mscuthbert** [comment]
The last type of "tie" that is unsupported explicitly and can only be faked in the music notation software I've used is the enharmonic tie, for instance, a D# tied to Eb -- rendering systems will generally treat this as a slur, but the Eb should not be rearticulated.

**Comment by webern** [comment]
I would recommend a new feature to support this.  I call these "LV Ties" for lack of a better name.  The typical use case that I am familiar with is with instruments like harp or percussion, there is a small, unterminated tie after a note that does not extend very far which indicates that the note should not be dampened.

I would request a new `<notations>` element for this.  Something like `<lv-tie>` which does not have a start-stop-continue attribute.  Instead it is a "one time element" which only appears on the note that has the LV tie (as if the LV tie were a Glyph like an articulation).

A  `<tied type="start">` without a `<tied type="stop">` would be a horrible way to implement this, IMO.

Another possible solution would be to have a new enum for `<tied>`, e.g. `start-stop-continue-unterminated` or `start-stop-continue-lv`

**Comment by jsawruk** [comment]
I actually like your proposal of `start-stop-continue-lv` the best. It makes the smallest change to the schema and makes semantic sense. You are still adding a tie; it just doesn't terminate. Although I think the term `lv` in this context is self-explanatory, it might not be the best option to represent a generic case (I'm only saying this because lv is an abbreviation). Perhaps `<tied type="let-ring" />` would be clearer both in semantic intent and in terms of human-readability?

I don't think this use case necessitates the use of a separate element; I think adding a new attribute type is the path of least resistance.

**Comment by mscuthbert** [comment]
In favor of this proposal. I think there are other situations that also need to be considered such as enharmonic ties and ties into fragments or second endings that should be included as well but I wouldn't let the perfect be the enemy of the very good.

**Comment by mscuthbert** [comment]
Also in favor of let-ring as a term

**Comment by mdgood** [comment]
The current approach to doing all these single-ended ties in MusicXML 3.0 is to use two `<tied>` elements on a single note: a `<tied type="start"/>` and a `<tied type="stop"/>`. This indeed does not seem ideal. It gets especially awkward in trying to maintain the numbering, as these could be combined on the same note with a regular `<tied>` element coming from the previous note.

I like @jsawruk's proposal to add a "let-ring" type to the tied element. This covers the largest use case, and the existing MusicXML practice of using two tied elements can suffice for the others.

Given all the interest in this, I would like to bring it into scope for MusicXML 3.1.

**Comment by webern** [comment]
Upon further reflection...

I think the case of enharmonic ties are already handled with precision by MusicXML 3.0.  It's the notation programs that may not be treating these correctly, but MusicXML 3.0 contains all the information necessary to treat them correctly.

If we simply add both `let-ring` and `single-incoming` (help with better name) then we would effectively have all the cases from this issue covered.  If we agree I'll be happy to try and set it up for a pull request.  It would be nice to make a contribution...

**Comment by mdgood** [comment]
I agree that MusicXML 3.0 already handles ties between enharmonic notes.

I think I would like to limit the additional type to a "let-ring" type since this is different semantically than the other situations, and is the most common use case. A tie at the end of a D.S. al Coda section, for instance, is not a let-ring tie even if it is single-ended.

Ties that are split across repeat structures or ties that are single-ended because they are from an excerpt of a score could be handled by including both start and stop tied elements on the note. The documentation for the tied element could be clarified by including this recommendation.

**Comment by mscuthbert** [comment]
Works for me.

**Comment by webern** [comment]
I did the best I could with a pull request #186.  DTD and xsl syntax are pretty evil.  I have a program called Xmplify which gives parse errors, but it was giving parse errors before I made changes so that wasn't too helpful.

Michael Good (and others), what software do you recommend for validating the dtd, xsd and xsl schema documents?

**Comment by webern** [comment]
Oops.  Fixing.

**Comment by webern** [comment]
#187

**Comment by mdgood** [comment]
I use oXygen Developer on Mac and XMLSpy on Windows, but I purchased XMLSpy before they increased the price a lot. The oXygen Developer software is powerful and pretty affordable.

Those will help with XSD and XSLT validation, but not DTDs which are not in XML format. One way to test is to drop all these files into the DTD folder of the Dolet for Finale plug-in, and test them during import into Finale, using both DTD and XSD validation. You can probably do that with other validating XML software as well, but the Dolet for Finale plug-in is easy to uninstall / reinstall to get the 3.0 DTD / XSD back.
