### ISSUE TITLE
Remove reference to type attribute from multiple-rest complex type

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#15]
Evan Brooks (@ebrooks01) found an error in the XSD documentation for the multiple-rest complex type. The last sentence references a non-existent type attribute and should be removed. 

This is at line 2505 in the musicxml.xsd file in MusicXML 3.0. The DTD documentation does not have this error.

See the MusicXML forum discussion at http://forums.makemusic.com/viewtopic.php?f=12&t=2742.

**Comment by mdgood** [comment]
The fix for this is in the issue description: removing the last sentence in the XSD documentation for the multiple-rest complex type. This is on line 2506 of the current 3.1 draft.

**Comment by mdgood** [comment]
https://github.com/w3c/musicxml/blob/5d84a04a19d9603729b882be2a96dfa353ceea53/schema/musicxml.xsd#L2506

**Comment by mscuthbert** [comment]
The element text is currently positive-integer-or-empty.  If it is empty, is there a default number of measures to span? My sense is best to change to positive-integer required to prevent ambiguity.  (Or set to one; but in any case, to specify the number somewhere)  Thanks!

**Comment by mdgood** [comment]
Sorry I missed this, @mscuthbert. At this point I don't recall the original intent - either to not display a number, or to rely on the application. Could you please create a separate issue for this so we can address it in the future? Thanks!

**Comment by mdgood** [comment]
Pull request #119 addresses this issue.

**Comment by mscuthbert** [comment]
Done in #249
