### ISSUE TITLE
Allow musical symbols to mix with text in directions and credits

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#163]
Sometimes musical symbols are interspersed with text in musical direction. For instance, a direction such as "Straight eighths" might have an eighth note followed by an "s", rather than using text.

MusicXML 3.0 does not have any standard, interoperable way to represent this in the general case. This is in part because there was no comprehensive listing of musical symbols available.

However, with MusicXML 3.1 and SMuFL support, we now have a "smufl-glyph-name" simple type in the MusicXML 3.1 schema that allows a semantic specification of any musical symbol. With this feature already in MusicXML 3.1, it becomes much easier to add a general symbol element that allows for arbitrary musical symbols to be interspersed with text. Adding this as a sibling element to the words and credit-words element is one possibility.

While we want to revisit MusicXML's text handling for MNX, adding a symbol element to directions and credits doesn't seem to complicate this. The symbol element could use the same text formatting as the words and credit-words element. It seems likely that regardless of how we would redo text handling for MNX, we will still want some kind of semantic difference between regular text and musical symbols.

**Comment by mdgood** [comment]
As an example, the "Straight eighths" direction that uses and eighth note followed by the "s" would look like this:

```
      <direction placement="above">
        <direction-type>
          <words default-x="54" default-y="34">Straight </words>
          <symbol>note8thUp</symbol>
          <words>s</words>
        </direction-type>
      </direction>
```

The symbol element would have most of the same formatting attributes as the words element, removing those that do not make sense for a single musical symbol (e.g. xml:lang, xml:space, letter-spacing). 

We would also need to update the rules for how the formatting attributes default. Currently, non-positioning attributes like font family and size default from the previous element. We probably want to change that to default from the previous element of the same tag. In the common case you would only need to specify formatting in the first words element and the first symbol element. In the most common case you wouldn't need to specify either, because formatting for words would come from the word-font element as it does now, while formatting for symbol would come from the music-font element.

The direction and credits element would be defined to always start with a words or credit-words element. We don't want writing applications to use this in place of the correct semantic symbol when the symbol is by itself. This is for interspersed text and symbols. In cases where the mix starts with a musical symbol, the initial words or credit-words element could be empty.

Does this make sense? Comments and suggestions are most welcome!

**Comment by mdgood** [comment]
Here is a proposed implementation.

1) At the top level, the direction-type and credit complex types will be changed. The current choice child of `<xs:element name="words" type="formatted-text" maxOccurs="unbounded"/>` will be replaced with
```
    <xs:sequence>
        <xs:element name="words" type="formatted-text" minOccurs="1"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="words" type="formatted-text"/>
            <xs:element name="symbol" type="formatted-symbol"/>
        </xs:choice>
    </xs:sequence>
```

The credit complex type already has a sequence element to intersperse link and bookmark elements. Within that sequence, the  `<xs:element name="credit-words" type="formatted-text"/>` element will be replaced with
```
    <xs:choice>
        <xs:element name="credit-words" type="formatted-text"/>
        <xs:element name="credit-symbol" type="formatted-symbol"/>
    </xs:choice>
```
2) A new formatted-symbol complex type will be defined similar to the formatted-text complex type. It's definition will be
```
	<xs:complexType name="formatted-symbol">
		<xs:annotation>
			<xs:documentation>The formatted-symbol type represents a SMuFL musical symbol element with formatting attributes.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="smufl-glyph-name">
				<xs:attributeGroup ref="symbol-formatting"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
```

3) The symbol-formatting attribute group will be defined parallel to the text-formatting attribute group. It will include all the same attributes except for xml:lang and xml:space. Originally I proposed to also drop the letter-spacing attribute, but that could be useful with a series of symbol or credit-symbol elements:
```
	<xs:attributeGroup name="symbol-formatting">
		<xs:annotation>
			<xs:documentation>The symbol-formatting attribute group collects the common formatting attributes for musical symbols. Default values may differ across the elements that use this group.</xs:documentation>
		</xs:annotation>
		<xs:attributeGroup ref="justify"/>
		<xs:attributeGroup ref="print-style-align"/>
		<xs:attributeGroup ref="text-decoration"/>
		<xs:attributeGroup ref="text-rotation"/>
		<xs:attributeGroup ref="letter-spacing"/>
		<xs:attributeGroup ref="line-height"/>
		<xs:attributeGroup ref="text-direction"/>
		<xs:attributeGroup ref="enclosure"/>
	</xs:attributeGroup>
```

Originally I proposed updating how the non-positioning formatting attributes default. On reflection I think that would make things too complex for directions, so I propose to leave the current specification as-is: "Non-positional formatting attributes are carried over from the previous element by default."

Parallel changes would be made to the DTD and XSLT files.

Comments and suggestions are most welcome!

**Comment by mdgood** [comment]
Pull request #173 addresses this issue.

**Comment by mdgood** [comment]
Issue #209 and pull request #212 address a problem with the initial design and pull request.

**Comment by mdgood** [comment]
Issue #223 and pull request #224 addressed an issue in MusicXML 3.0 conversion.

**Comment by mdgood** [comment]
Issue #222 and pull request #225 clarified the documentation of this feature.

**Comment by mscuthbert** [comment]
Not part of the spec, but strong recommend to implementers that they use a SMUFL compatible font that adjusts the size of objects so that they do not cause major disruptions in the alignment of surrounding text.
