### ISSUE TITLE
Clarification of Direction Documentation

### ISSUE THREAD

**Issue by webern** [w3c/musicxml#170]
The direction documentation states that direction `A direction is a musical indication that is not attached to a specific note.`

In some applications, some directions (wedges for example) _can_ be tied to a note.  Some clarification here would be helpful.  If I want a direction to point to a specific note, does MusicXML allow this?

**Comment by mdgood** [comment]
I think we can clarify this by:

- Modifying this sentence to read "A direction is a musical indication that is not necessarily attached to a specific note."
- Adding another sentence like "For applications where a specific direction is indeed attached to a specific note, the direction element is associated with the note element that follows it in score order that is not in a different voice."

Would this help, @Webern, or could this be clarified further?

**Comment by mdgood** [comment]
Pull request #194 addresses this issue.

**Comment by mdgood** [comment]
Would you be able to review pull request #194 to see if this meets your expectations, @Webern? Thanks for your help!
