### ISSUE TITLE
Clarification of Concurrent or Overlapping Slurs without number-level Attributes

### ISSUE THREAD

**Issue by webern** [w3c/musicxml#180]
If two or more slur starts occur before the respective stops are encountered, and if no number-level attributes are present, what is the correct behavior with regard to the "spanner stack".  Is it FIFO or LIFO.

example
slur - type=start (A)
slur - type=start (B)
...
slur - type=stop (is it A or B that is stopping?)

I guess that the slur stack is FIFO and it is "A" that is stopping in the above example.  Can someone confirm?

Do the same rules apply for slurs, ties, wedges and tuplets?

**Comment by mdgood** [comment]
There is no default order. If you have overlapping slurs in MusicXML document order, you need to use different number-level values to distinguish them. Not doing this is an error on the part of the exporting program. Please notify the makers of the app that exported this so they can fix it, and do whatever fits the needs of your app best during import (FIFO, LIFO, or just discarding one or the other).

I think the number-level documentation is already clear about this, but if you have suggestions for clarifying it further please let me know.

**Comment by webern** [comment]
Actually what prompted me to ask this question was a Finale export in which I was surprised that simultaneous _tied_ elements were not numbered.  Just now I noticed that this is explicitly covered in the documentation 

> The number attribute is rarely needed to disambiguate ties, since note pitches will usually suffice. The attribute is implied rather than defaulting to 1 as with most elements. It is available for use in more complex tied notation situations.

This is quite clear and there is no action item to be taken here.  However I will part with a small complaint :) in that I would have preferred to use number-level instead of diving into the deeper context of order-encountered plus pitch elements, etc.  Anyhow, like I said, the documentation is clear.  Thanks!
