### ISSUE TITLE
Indicate absence of leger lines for highest or lowest note

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#184]
When writing symbols for a highest or lowest note of indeterminate pitch, it is common to write the note outside the staff without a leger line. Elaine Gould's _Behind Bars_ gives examples of this on pp. 12-13. This notation can also be used with normal noteheads as well as arrow noteheads, and is found in jazz as well as classical writing.

MusicXML 3.0 currently doesn't provide a way to indicate the absence of leger lines for a specific note. In this case the formatting information about leger lines is closely related to the semantics of the note rather than being strictly a style choice, as in the leger line formatting in issue #87.

Currently the Dolet for Finale plug-in is using XML processing instructions to pass this information between applications. It would be better for MusicXML to represent it directly.

**Comment by mdgood** [comment]
This could be done by adding a print-leger attribute with a yes-no type to the note complex type. As with the printout attributes, it is set to yes by default unless the print-object attribute is set to no.

**Comment by mdgood** [comment]
This attribute would also be ignored if a `<rest>` element is present within the `<note>` element.

**Comment by Glenn-smufl** [comment]
Not sure what the implication of the last comment is.  Some rests do need leger lines:
[http://www.hymnary.org/hymn/HOP2015/page/101](example)

**Comment by mdgood** [comment]
The idea is that some rests (like whole and half rests) always need leger lines and some never do, so the attribute would be ignored for rests.

The purpose of this story is to represent highest and lowest pitch notation. We could make this an attribute of the `<pitch>` element, but all the other print- attributes are located at the `<note>` element.

**Comment by mdgood** [comment]
Pull request #197 addresses this issue.
