### ISSUE TITLE
Add zip container media type identification

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#185]
It can be helpful for reading programs to be able to identify compressed MusicXML files by reading the first bytes of a file. EPUB and other zip-based document format support this by including a media type identification file called mimetype as the first, uncompressed file in a zip container. The EPUB 3.1 specification for this file is at http://www.idpf.org/epub/31/spec/epub-ocf.html#sec-zip-container-mime.

It could be helpful for MusicXML to recommend the use of the mimetype file in compressed MusicXML files. The EPUB format requires its use, but this may not be practical for MusicXML at this point since neither MusicXML 2.0 nor 3.0 made this a requirement.

The content of this file would match the media type that we decide to use in issue #51.

**Comment by Glenn-smufl** [comment]
I have to admit to not having read the whole MusicXML spec, compressed or uncompressed... I came into this group from the SMuFL direction, and had earlier mostly ignored MusicXML. But I have read the EPUB 3.1 spec, and am aware of its first, uncompressed, mimetype file.  While that does make a zip container readily identifiable as to type, EPUB clearly specifies a potentially large collection of associated files as part of its specification, and then has further specification for each file. My impression of MusicXML was that it was a single XML file, not a potentially large collection of associated files... 

IF my impression of MusicXML is correct, then adding a file, and forcing a .zip type container compression would only slow down the processing of compressed files... for a single file, a stream-oriented compression like gzip or (newer) brotli is far easier to deal with.  But if there are (frequently) a bundle of files, or if container-based ZIP format is already baked into the MusicXML spec for some reason, then the initial, uncompressed mimetype file isn't a bad solution, although it can be cumbersome to achieve manually with typical compression programs. It isn't too hard to achieve using a program and compression library.

**Comment by mdgood** [comment]
Thanks for the feedback. MusicXML has a zip file version since version 2.0. Today's main use of additional files is for images, which are documented in the MusicXML specification. We also wanted an expandable container for future standardization of other data such as audio, video, metadata, and synchronization files. 

So there is nothing new with the zip compression. This is adding a single mimetype file to the existing zip container. Finale has already been doing this for the past few years.

**Comment by mdgood** [comment]
The group consensus at the Musikmesse meeting was to go ahead with this proposal.

**Comment by mdgood** [comment]
Pull request #206 addresses this issue.

**Comment by mdgood** [comment]
As mentioned in issue #51, we cannot change the MusicXML media type to the standards tree at this time. We will thus need to update the media type content of the mimetype file accordingly.

**Comment by mdgood** [comment]
Pull request #211 reverts back to the current media type for the content of the mimetype file.
