### ISSUE TITLE
Document whether a <note> can contain multiple <bend>s

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/musicxml#203]
I am investigating the MusicXML generated by [Guitar Pro 7](https://www.guitar-pro.com/) (released a few days ago), and I've found that it sometimes puts two `<bend>` elements within a single `<note>`.

This happens in case of a "bend and release" bend. For example, in this screenshot from a Guitar Pro score, the measure contains two notes, each of which has a "bend and release."

![screen shot 2017-04-21 at 11 36 36 am](https://cloud.githubusercontent.com/assets/180401/25272118/f2d6f1f4-2686-11e7-90d8-248041ebd733.png)

Here is Guitar Pro 7's resulting MusicXML (with irrelevant stuff stripped out):

```
 <note>
  <pitch>
   <step>E</step>
   <octave>4</octave>
  </pitch>
  <type>half</type>
  <notations>
   <technical>
    <bend>
     <bend-alter>2</bend-alter>
    </bend>
    <bend>
     <bend-alter>0</bend-alter>
     <release/>
    </bend>
    <string>2</string>
    <fret>5</fret>
   </technical>
  </notations>
 </note>
 <note>
  <pitch>
   <step>E</step>
   <octave>4</octave>
  </pitch>
  <type>half</type>
  <notations>
   <technical>
    <bend>
     <bend-alter>1</bend-alter>
    </bend>
    <bend>
     <bend-alter>0</bend-alter>
     <release/>
    </bend>
    <string>2</string>
    <fret>5</fret>
   </technical>
  </notations>
 </note>
```

My question is: if indeed it's correct to use multiple `<bend>` elements within a single note, can we improve the documentation to clarify this? I'm happy to tackle the documentation; just need to know whether it's correct in the first place. :-)

**Comment by mdgood** [comment]
This looks correct to me, except that I would expect those bend-alter values to be -2 and -1, respectively. I think I was originally thinking that the release would go on the following note, like a pre-bend does, but then where would you put the release on the last note of a piece?

It has been a long time since I looked at bends, and this is one element where the MusicXML design and resulting interchange could use some work. I hope we can solve this better in MNX, but in the meantime it would be good to improve MusicXML as best we can.

**Comment by mdgood** [comment]
Now that I have done some more development work with bends as part of #306, I think that we may want to handle this situation differently. I think there needs to be an invisible note element in the tab that indicates the transition between the bend and the release. This is for a couple of reasons:

- The bend-alter value is relative to the pitch of the note. That means you need to have a reference note (even if invisible) to serve as the starting point for the release. A similar issue applies to the bend-sound playback; it is defined in reference to the parent note.
- Without a reference note for the release, there isn't a way to specify when the bend turns into a release, either semantically or in notation layout.

This is interrelated with #204 and also involves finally better defining how a <release/> element should work.

@adrianholovaty, how does this match up with current implementations? Are applications aside from Guitar Pro using the invisible / intermediate note approach this type of bend / release combination? Or are other techniques being used?

I'm sorry that this area has been underspecified for so long. It would be great to get this cleaned up now.

**Comment by mdgood** [comment]
Thinking about this again in reference to @cyrilcoutelier's comment on #204, we could allow for two bends on a note if we add an optional `<offset>` child element to the `<release>` element. That would address the issue of specifying when the bend turns into a release. 

We would still have to determine in #204 if the `<bend-alter>` value should be relative to the original note or to the end of the preceding bend. I think the `bend-sound` entity could handle this by using different values for the `first-beat` and `last-beat` attributes, e.g. something like 10 and 40 for the first bend and 60 and 90 for the second bend.

**Comment by cyrilcoutelier** [comment]
An offset could give the information of the position of the intermediate release and bends. We need to specify if the offset is based on the note start, or on the previous offset. 
However, I feel that if the position of intermediate release and bends is important, it can as well be specified as distinct 
notes.

**Comment by mdgood** [comment]
Having thought about these two alternatives some more, I believe we do need to go with specifying the note that comes between the bend and the release. This is for the reasons mentioned [earlier](#issuecomment-757017761). In tab this would likely involve including a `<notehead>none</notehead>` within the `<note>` element to specify that no number is printed for that note.

**Comment by mdgood** [comment]
@adrianholovaty and @cyrilcoutelier, could you please review the pull request #391 to see if this is clear enough? Other reviews are most welcome too!

**Comment by adrianholovaty** [comment]
I read the spec change in the pull request a few times but can't wrap my head around it. :-/

It would really help me if we could encode the example notation at the very start of this issue. I'll take a stab at it... Is this correct?

```xml
<note>
 <pitch>
  <step>E</step>
  <octave>4</octave>
 </pitch>
 <type>half</type>
 <notations>
  <technical>
   <bend>
    <bend-alter>2</bend-alter>
   </bend>
   <string>2</string>
   <fret>5</fret>
  </technical>
 </notations>
</note>

<note>
 <pitch>
  <step>F</step>
  <alter>1</alter>
  <octave>4</octave>
 </pitch>
 <type>quarter</type><!-- is this correct? -->
 <accidental>sharp</accidental>
 <notehead>none</notehead>
 <notations>
  <technical>
   <bend>
    <bend-alter>-2</bend-alter>
    <release/>
   </bend>
   <!-- is it correct to omit string and fret here? -->
  </technical>
 </notations>
</note>

<note>
 <pitch>
  <step>E</step>
  <octave>4</octave>
 </pitch>
 <type>half</type>
 <notations>
  <technical>
   <bend>
    <bend-alter>1</bend-alter>
   </bend>
   <string>2</string>
   <fret>5</fret>
  </technical>
 </notations>
</note>

<note>
 <pitch>
  <step>F</step>
  <alter>1</alter>
  <octave>4</octave>
 </pitch>
 <type>quarter</type>
 <notehead>none</notehead>
 <notations>
  <technical>
   <bend>
    <bend-alter>-1</bend-alter>
   </bend>
  </technical>
 </notations>
</note>
```

**Comment by mdgood** [comment]
Thanks @adrianholovaty. I think the following would be better for the tablature. But it's pretty clunky, and the standard notation would be even worse. So I think I'm changing my mind here for going with having the two bends on the single note. Let me work on that and come back with a different example using that approach.

```xml
<note>
 <pitch>
  <step>E</step>
  <octave>4</octave>
 </pitch>
 <duration>4</duration>
 <type>quarter</type>
 <notations>
  <technical>
   <bend>
    <bend-alter>2</bend-alter>
   </bend>
   <string>2</string>
   <fret>5</fret>
  </technical>
 </notations>
</note>

<note>
 <pitch>
  <step>F</step>
  <alter>1</alter>
  <octave>4</octave>
 </pitch>
 <duration>4</duration>
 <type>quarter</type>
 <accidental>sharp</accidental>
 <notehead>none</notehead>
 <notations>
  <technical>
   <bend>
    <bend-alter>-2</bend-alter>
    <release/>
   </bend>
   <string>2</string>
  </technical>
 </notations>
</note>

<note>
 <pitch>
  <step>E</step>
  <octave>4</octave>
 </pitch>
 <duration>4</duration>
 <type>quarter</type>
 <notations>
  <technical>
   <bend>
    <bend-alter>1</bend-alter>
   </bend>
   <string>2</string>
   <fret>5</fret>
  </technical>
 </notations>
</note>

<note>
 <pitch>
  <step>F</step>
  <octave>4</octave>
 </pitch>
 <duration>4</duration>
 <type>quarter</type>
 <notehead>none</notehead>
 <notations>
  <technical>
   <bend>
    <bend-alter>-1</bend-alter>
   </bend>
   <string>2</string>
  </technical>
 </notations>
</note>
```

**Comment by mdgood** [comment]
While I work on the pull request, here is the way the tablature notation would work in the alternate approach. Thanks again @adrianholovaty for putting this in terms of examples which really helps clarify the relative merits of the two approaches.

```xml
<note>
 <pitch>
  <step>E</step>
  <octave>4</octave>
 </pitch>
 <duration>8</duration>
 <type>half</type>
 <notations>
  <technical>
   <bend>
    <bend-alter>2</bend-alter>
   </bend>
   <bend>
    <bend-alter>-2</bend-alter>
    <release offset="4"/>
   </bend>
   <string>2</string>
   <fret>5</fret>
  </technical>
 </notations>
</note>

<note>
 <pitch>
  <step>E</step>
  <octave>4</octave>
 </pitch>
 <duration>8</duration>
 <type>half</type>
 <notations>
  <technical>
   <bend>
    <bend-alter>1</bend-alter>
   </bend>
   <bend>
    <bend-alter>-1</bend-alter>
    <release offset="4"/>
   </bend>
   <string>2</string>
   <fret>5</fret>
  </technical>
 </notations>
</note>
```

**Comment by mdgood** [comment]
Pull request #394 implements this alternate approach of having the bend and release on the same note, as in the previous example. @adrianholovaty, does this pull request make more sense?

**Comment by adrianholovaty** [comment]
I've left some comments on #394. Upshot is that the approach looks good to me, with some small wording suggestions.
