### ISSUE TITLE
Clarify whether <bend-alter> value is absolute or relative

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/musicxml#204]
I'm seeing conflicting real-world data for `<bend-alter>`. We could prevent inconsistency here by clarifying the documentation.

Consider a bend that's rhythmically split over two half notes. The note is bent a half step, then released to the original pitch:

![screen shot 2017-04-21 at 11 52 25 am](https://cloud.githubusercontent.com/assets/180401/25272661/07379778-2689-11e7-8e46-221721a06590.png)

What should the `<bend-alter>` value be for the second note (when the bend is released)? The two, mutually exclusive, approaches I've seen are:

* `<bend-alter>-1</bend-alter>` — relative to the _previous_ note. This is implied in the [MusicXML documentation](http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#EL-MusicXML-bend-alter.htm).
* `<bend-alter>0</bend-alter>` — relative to the _original_ (unbent) pitch. This is how Guitar Pro 7 does it. Here is its MusicXML for the above example:

```
   <note>
    <pitch>
     <step>E</step>
     <octave>4</octave>
    </pitch>
    <duration>2</duration>
    <tie type="start"/>
    <type>half</type>
    <stem>up</stem>
    <notations>
     <technical>
      <bend>
       <bend-alter>1</bend-alter>
      </bend>
      <string>2</string>
      <fret>5</fret>
     </technical>
     <tied type="start"/>
    </notations>
   </note>
   <note>
    <pitch>
     <step>E</step>
     <octave>4</octave>
    </pitch>
    <duration>2</duration>
    <tie type="stop"/>
    <type>half</type>
    <stem>up</stem>
    <notations>
     <technical>
      <bend>
       <bend-alter>0</bend-alter>
       <release/>
      </bend>
      <string>2</string>
      <fret>5</fret>
     </technical>
     <tied type="stop"/>
    </notations>
   </note>
```

I cannot think of any particular advantages of either approach — we just need to clarify which one is the standard. Otherwise, bend data can't be guaranteed to be interoperable across programs.

**Comment by mdgood** [comment]
It should be the negative value, not the zero value. If there's a good way to clarify this let's try to get this into V3.1.

**Comment by cyrilcoutelier** [comment]
I have a preference for having the bend being related to the original (unbent) pitch, as it make the information standalone for the note. 
However I wonder if we should give guideline about the encoding of TAB staff vs normal staff, as the bend above can be encoded with 2 notes on the TAB staff, but require 3 on the normal staff. 
Also on the normal staff, should the pitch be encoded as the sounding pitch? Or should it be the unbent pitch, and it is up to the application to translate it visually?

**Comment by mdgood** [comment]
Thanks @cyrilcoutelier. But isn't the standalone note issue related more to #203 than this issue? That is, if we allow multiple bends per note, then the tab representation in particular better matches the visual appearance of the score.

I am inclined to have the `<bend-alter>` value in the `<release>` element be relative to the previous bend, if any. That way the release values are the same whether or not one is using an intermediate note between the bend and release. In the standard notation an intermediate note better matches the visual representation, but in tab notation it does not.

In normal notation where the intermediate or ending notes are displayed, the visual pitch and the sounding pitch are the same in this situation. The time where an application would need to create a note from an unbent pitch would be if the application needs to create an intermediate note, but the MusicXML does not contain one.

Does that help or am I misunderstanding some of these questions?

**Comment by cyrilcoutelier** [comment]
I think I understand. So the convention would be to encore with the sounding pitch if the note is in normal staff, and with the unbent pitch in a TAB staff, right? 

The value I see in having the `bend-alter` relative to the unbent pitch is that we don't have to go up the chain of bends to have the sounding pitch, we only need the information of the previous note in case of chained bends.

**Comment by mdgood** [comment]
Given the plan to require a `<note>` element between the bend and release in #203, the `<bend-alter>` value for a release will need to be negative.
