### ISSUE TITLE
MusicXML to PDF CLI

### ISSUE THREAD

**Issue by MegaArman** [w3c/musicxml#208]
Does anyone know of a command line tool to convert MusicXML to PDF? This would save a great deal of time as opposed to manually opening scores in a program and then converting them. The rendering for many large scores takes forever on my laptop.

I found this
[http://forums.makemusic.com/viewtopic.php?f=12&t=3213&p=9949&hilit=pdf#p9949](url)

But no reply.

**Comment by webern** [comment]
museScore can do this from the command line.

**Comment by MegaArman** [comment]
musescore 2.0.3 segfaults =(, ex: `musescore mozart.xml -o mozart.pdf `

OS: Fedora 25

UPDATE: It seems to work actually. Still hoping for a better tool or if there's a better way to use that one to avoid segfaulting - I plan to do this in bulk.

**Comment by mogenslundholm** [comment]
Seems to work on PC (Windows 8) also: 
MuseScore Tystnaden.xml -o Tystnaden.pdf

**Comment by shoogle** [comment]
Or via the special [batch processing mode](https://musescore.org/en/node/110796):

```bash
mscore -j job.json
```

With the following in `job.json`:
```json
[
{"in":"score1.mxl", "out":"score1.pdf"},
{"in":"score2.xml", "out":"score2.pdf"},
{"in":"score3.musicxml", "out":"score3.pdf"}
]
```

This avoids loading MuseScore into memory multiple times, which signifcantly saves time compared to:

```bash
mscore score1.mxl -o score1.pdf
mscore score2.xml -o score2.pdf
mscore score3.musicxml -o score3.pdf
```

**Comment by MegaArman** [comment]
That is good to know! Thanks
