### ISSUE TITLE
problem with code-generation of direction-type for MusicXML 3.1 draft

### ISSUE THREAD

**Issue by jsutdolph** [w3c/musicxml#209]
The draft musicxml 3.1 schema defines changes to the words type from:

&lt;xs:element name=&quot;words&quot; type=&quot;formatted-text&quot; maxOccurs=&quot;unbounded&quot;&gt;
	&lt;xs:annotation&gt;&lt;xs:documentation&gt;...&lt;/xs:documentation&gt;&lt;/xs:annotation&gt;
&lt;/xs:element&gt;

to:

&lt;xs:sequence&gt;
		&lt;xs:element name=&quot;words&quot; type=&quot;formatted-text-id&quot; minOccurs=&quot;1&quot;&gt;
			&lt;xs:annotation&gt;&lt;xs:documentation&gt;...&lt;/xs:documentation&gt;&lt;/xs:annotation&gt;
		&lt;/xs:element&gt;
		&lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
			&lt;xs:element name=&quot;words&quot; type=&quot;formatted-text-id&quot;/&gt;
				&lt;xs:element name=&quot;symbol&quot; type=&quot;formatted-symbol-id&quot;&gt;
				&lt;xs:annotation&gt; &lt;xs:documentation&gt;...&lt;/xs:documentation&gt; &lt;/xs:annotation&gt;
			&lt;/xs:element&gt;
		&lt;/xs:choice&gt;
&lt;/xs:sequence&gt;

This creates a headache for those of us who use code generators as this change adds a lot of complexity to the generated code.

**Comment by mdgood** [comment]
This change was made as part of issue #163. I think we could avoid much of the complexity for code generators if we change this to:
```
<xs:choice maxOccurs="unbounded">
	<xs:element name="words" type="formatted-text-id"/>
	<xs:element name="symbol" type="formatted-symbol-id">
		<xs:annotation>
			<xs:documentation>...</xs:documentation>
		</xs:annotation>
	</xs:element>
</xs:choice>
```
The motivation for the original design was to make it impossible to use a <symbol/> element on its own. We don't want XML writers to start using this feature as a way to avoid properly encoding isolated symbols semantically.

We could still specify that the symbol element should not be used on its own, but not enforce that in the XSD. This would also make it easier to handle the case where a symbol is interspersed with text at the very beginning of a direction, avoiding the need for an empty words element.

Similar changes would be made for the `<credit>` element. In that case there is not a direct substitute for the `<credit-symbol>` element like `<other-direction>` within a `<direction>` element, so there would be no prohibition on a single `<credit-symbol>` element.

Does this seem like a reasonable change?

**Comment by mdgood** [comment]
Pull request #212 addresses this issue. @jsutdolph, will that simplify things for your development? This change also better represents when a direction with mixed music and symbols starts with a symbol.
