### ISSUE TITLE
problem with code-generation of grace for MusicXML 3.1 draft

### ISSUE THREAD

**Issue by jsutdolph** [w3c/musicxml#210]
The draft musicxml 3.1 schema defines changes to the grace in note type from:

&lt;xs:sequence&gt;
		&lt;xs:element name=&quot;grace&quot; type=&quot;grace&quot;/&gt;
		&lt;xs:group ref=&quot;full-note&quot;/&gt;
		&lt;xs:element name=&quot;tie&quot; type=&quot;tie&quot; minOccurs=&quot;0&quot; maxOccurs=&quot;2&quot;/&gt;
&lt;/xs:sequence&gt;

to:

&lt;xs:sequence&gt;
		&lt;xs:element name=&quot;grace&quot; type=&quot;grace&quot;/&gt;
		&lt;xs:choice&gt;
			&lt;xs:sequence&gt;
				&lt;xs:group ref=&quot;full-note&quot;/&gt;
				&lt;xs:element name=&quot;tie&quot; type=&quot;tie&quot; minOccurs=&quot;0&quot; maxOccurs=&quot;2&quot;/&gt;
			&lt;/xs:sequence&gt;
			&lt;xs:sequence&gt;
				&lt;xs:element name=&quot;cue&quot; type=&quot;empty&quot;/&gt;
				&lt;xs:group ref=&quot;full-note&quot;/&gt;
			&lt;/xs:sequence&gt;
		&lt;/xs:choice&gt;
&lt;/xs:sequence&gt;

This creates a headache for those of us who use code generators as this change adds a lot of complexity to the generated code.
Since it is foremost a cue note that is a grace, rather than a grace note that is a cue, (since this would be expected to be in a run of cue notes), would it not be simpler to add an optional grace attribute to the cue note?

**Comment by mdgood** [comment]
I don't think this would be simpler for most use cases, unfortunately. This would add complexity with grace notes being encoded one way for cue notes and another way for non-cue notes. I understand that the playback attributes of the grace element are not needed for grace cue notes, but I think this encoding still remains the simplest overall.

With the current design, the only new situation that applications or MusicXML readers need to deal with are notes that have a cue element following the grace element. There are no special cases for one type of grace note or the other. The current design also does not add any unexpected elements to either grace or cue notes beyond the other element needed for grace cue notes (e.g., no tie elements for cue notes, no duration element for grace notes). For applications that do not use code generators, this is about as straightforward as possible for adding this new feature.

I'm sorry for the added complexity for applications with code generators. However I don't see another way to retain the separate elements and do this another way. Some of the possible alternatives would run into problems with Unique Particle Attribution.

If anybody else has some ideas that I am overlooking please let us know!

**Comment by jsutdolph** [comment]
This single decision significantly raises the cost for SeeScore to adopt MusicXML 3.1 for what is a very rare case (a grace note cue), and for which there is an acceptable alternative (the grace flag). With the high cost of MNX adoption looming, We are considering either using a hacked hybrid schema to generate the code, or abandoning plans for early adoption of 3.1.

**Comment by mdgood** [comment]
Hi James,

I apologize for the delay in getting back to you on this; it originally came in while I was on vacation.

Could you please help me understand better how this significantly raises the cost of implementation for SeeScore? Clearly it raises it somewhat, I understand that. But it seems to me that the solution would be to add some getters and setters to the API generated by the automatic tools that lets the code access the data in the same way it did with MusicXML 3.1. However I do not use these types of code generators, so I am aware my understanding could be naive.

The schema design is under constraints for unique particle attribution that push things down a level, but those do not apply to an API. Adding or modifying the results of the generator tools doesn't seem so much of a hack as an expected customization.

I do understand the appeal of the grace flag for your application, but that complicates things further for other applications. It would be great if we could keep the overall simplicity of the separate grace and cue elements with only a small added cost for schema code generator compatibility. It doesn't seem that this would be a prohibitive amount of extra work, especially in comparison with implementation of other MusicXML 3.1 features.

Does anyone else have experience with code generation from the XSD schema that could share their perspective on this issue?
