### ISSUE TITLE
A symbol for Ritardando?

### ISSUE THREAD

**Issue by mogenslundholm** [w3c/musicxml#215]
It seems to me that there is no symbol for Ritardando. It is just a text, and therefore the text is different: Sometimes "rit.", sometimes "ritard" and variants, sometimes with dot and sometimes not. 

Shouldn't this be a symbol like &lt;pp/&gt;? E.g. &lt;ritardando/&gt;?

An example is the MusicXML-test-suite is in Dichterliebe.xml ( line 4189 ). Here the text is "&lt;words&gt;ritard.&lt;/words&gt;" And more than that - the tempo-spec is not in the first part (voice/instrument).   
/Mogens

**Comment by dspreadbury** [comment]
I think this is out of scope for MusicXML 3.1. We do urgently need to come up with a more semantic approach to text-based instructions for CWMNX, and I plan to create an issue outlining some possible approaches to this in due course.

**Comment by mdgood** [comment]
Making text more semantic is something we plan to address in MNX rather than MusicXML, so I am closing the issue here.
