### ISSUE TITLE
Rhythm representation in MusicXML

### ISSUE THREAD

**Issue by ashutoshsaboo** [w3c/musicxml#226]
Hi, 
I have been reading about MusicXML, and I'm new to this, since I was used to MIDI. It seems MusicXML is pretty more extravagant. Although, is there any mechanism as to how the rhythm of a track can be extracted from the MusicXML format? 
Thanks.

**Comment by mdgood** [comment]
MusicXML covers music notation much more completely than MIDI, which accounts for all the extra features in that area. Rhythms are represented by several elements and attributes, including the duration, type, and dot elements, and the attack and release attributes. If you haven't already looked at the MusicXML tutorial at http://www.musicxml.com/tutorial/, that might be helpful.

**Comment by ashutoshsaboo** [comment]
Hi @mdgood Thanks ! I looked at the tutorial already, but there isn't any specific thing mentioned for rhythms actually. Is there a specific page regarding Rhythms in MusicXML that you can point me to, if possible? Thanks!

**Comment by mdgood** [comment]
Rhythms are covered in the tutorial throughout http://www.musicxml.com/tutorial/the-midi-compatible-part/. This could indeed be better documented. However we are holding off on documentation work in favor of developing MNX and making that better suited to a formal specification.

**Comment by ashutoshsaboo** [comment]
Ohh @mdgood ! Thanks I'll look into it! :smile:
