### ISSUE TITLE
Clarify meaning of measure-numbering default-y on multi-staff parts

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#23]
The measure-numbering element within the <print> element is part-specific rather than staff-specific, but still contains a default-y attribute. For multi-staff parts this makes the meaning of the default-y attribute ambiguous - which staff should it refer to? The design intention was that it refers to the top line of the top staff, but this or another meaning should be made explicit.

In MusicXML 3.0, this documentation occurs at line 3090 of musicxml.xsd and starting at line 937 in the direction.mod file.

See the MusicXML forum discussion started by Frank Weinstock at http://forums.makemusic.com/viewtopic.php?f=12&t=2384.

**Comment by mdgood** [comment]
The measure-numbering documentation still refers to printing from the measure element's number attribute rather than from the text attribute added in MusicXML 3.1. While we are fixing the default-y definition for multi-staff parts, it would be good to fix this as well.

**Comment by mdgood** [comment]
In issue #37 we want to be able to specify that measure numbers appear on the top or bottom staff of the system. To better support measure numbering underneath a part on the bottom staff of the system, I think it would be good to add an option to specify which staff the positioning applies to in a multi-staff part, rather than always specifying the top staff.

We could do this by adding a `staff` attribute to the `<measure-numbering>` element that specifies the staff number within the part where the measure numbering is displayed. The `default-y` position would then be measured from the top line of this staff. The value would be 1 if not present.

Usually this type of staff indication is represented by a `<staff>` child element or a `number` attribute. The child element is not available since we avoid mixed content in MusicXML (e.g. a mix of text content and child elements). Using the `number` attribute seems like it would be confusing in the context of a `<measure-numbering>` element. Thus the proposal to add a `staff` attribute instead.

Does this sound like a good plan? Are there better ways to address this issue?

**Comment by jsawruk** [comment]
Maybe `staff-number` instead of `staff`? Otherwise, I think this is a great solution.

**Comment by mdgood** [comment]
Closed by #354.
