### ISSUE TITLE
Allow combination of slash and regular notation

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#231]
Sometimes slash notation in one voice is combined with regular notation in another voice. This can happen with cue notes, or as in the following example with percussion notation:

![slash-plus](https://user-images.githubusercontent.com/11082681/28483571-37172398-6e2b-11e7-8394-23fb07a5a7e7.jpg)

This example cannot currently be directly represented in MusicXML. MusicXML 3.0 represents slash notation with the `<slash>` element, a child of the `<measure-style>` element which is in turn a child of the `<attributes>` element. While the measure-style element has a number attribute that can restrict the style to a single staff, there is nothing to restrict it to a single voice.

MusicXML could add the ability to restrict the `<slash>` and `<beat-repeat>` elements to a single voice. If the restriction were moved up to the `<measure-style>` element, it would also apply to multi-measure rests and full-measure repeats, which may not be as appropriate.

**Comment by jsawruk** [comment]
I think restricting the ```<slash>``` to a single voice would make the most sense semantically. In the example you provided above, the slash notation is restricted to just one voice. My only question with this approach is, would there ever be a time where you would need to apply slash notation to all voices?

**Comment by mdgood** [comment]
Slash notation is already applied to all voices in MusicXML 3.0. That is the most common case. I do think there are cases where you would need to restrict to more than one voice, but I am not sure about that.

**Comment by mdgood** [comment]
We could do this by adding a new `<only-voice>` element to the slash element group, which is used by both the `<slash>` and `<beat-repeat>` elements. This proposal allows for restriction to multiple voices. Removing the maxOccurs attribute would only allow restriction to a single voice.
```
<xs:element name="only-voice" type="xs:string" minOccurs="0" maxOccurs="unbounded">
	<xs:annotation>
		<xs:documentation>The only-voice element is used to restrict slashes to the specified voice. Multiple instances of the element can be used to restrict slashes to multiple voices.</xs:documentation>
	</xs:annotation>
</xs:element>
```
Similar changes would be made to the DTD and XSLT files.

**Comment by mdgood** [comment]
Since the slash notation is always displayed, but additional notes in specific voices may also be displayed in normal notation, it seems the new element should be flipped around. We can call it `<except-voice>` and use it to specify the voices whose notes appear in regular notation in addition to the slash notation. Here is an updated proposal:
```
<xs:element name="except-voice" type="xs:string" minOccurs="0" maxOccurs="unbounded">
	<xs:annotation>
		<xs:documentation>The except-voice element is used to specify a combination of slash notation and regular notation. Any note elements that are in voices specified by the except-voice elements are displayed in normal notation, in addition to the slash notation that is always displayed.</xs:documentation>
	</xs:annotation>
</xs:element>
```

**Comment by mdgood** [comment]
Pull request #234 addresses this issue. I needed to add another level of sequence to the slash group in the XSD; I didn't see any way to get around that. The group definition now looks like this:
```
<xs:group name="slash">
	<xs:annotation>
		<xs:documentation>The slash group combines elements used for more complete specification of the slash and beat-repeat measure-style elements. They have the same values as the type and dot elements, and define what the beat is for the display of repetition marks. If not present, the beat is based on the current time signature.</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:sequence minOccurs="0">
			<xs:element name="slash-type" type="note-type-value">
				<xs:annotation>
					<xs:documentation>The slash-type element indicates the graphical note type to use for the display of repetition marks.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="slash-dot" type="empty" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The slash-dot element is used to specify any augmentation dots in the note type used to display repetition marks.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:element name="except-voice" type="xs:string" minOccurs="0" maxOccurs="unbounded">
			<xs:annotation>
				<xs:documentation>The except-voice element is used to specify a combination of slash notation and regular notation. Any note elements that are in voices specified by the except-voice elements are displayed in normal notation, in addition to the slash notation that is always displayed.</xs:documentation>
			</xs:annotation>
		</xs:element>
	</xs:sequence>
</xs:group>
```
