### ISSUE TITLE
Johnston notation

### ISSUE THREAD

**Issue by bramtayl** [w3c/musicxml#242]
Is in possible to get support for microtonal corrections? In particular Johnston notation www.marcsabat.com/pdfs/EJItext.pdf

**Comment by mdgood** [comment]
Thank you for your suggestion. I believe this should already be handled in MusicXML 3.1 with issue #109, which allows you to specify any SMuFL glyph name for an accidental. The Johnston accidentals are available in SMuFL at https://w3c.github.io/smufl/gitbook/tables/johnston-accidentals-just-intonation.html. The MusicXML alter element can capture the sounding aspect of the alteration.

If there is still something missing from this approach please let us know.
