### ISSUE TITLE
Create Community Report for MusicXML 3.1

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#245]
For MusicXML 3.1 to be published as a W3C Community Group Report, we need to have an HTML file that serves as the report. The main parts of the report will be a pointer to the MusicXML schemas in GitHub with the v3.1 tag, and a list of the changes from MusicXML 3.0 to 3.1.

**Comment by mdgood** [comment]
Pull requests #239, #240, #241, and #243 address this issue.

**Comment by dspreadbury** [comment]
The report looks good to me!

**Comment by mdgood** [comment]
Additional pull requests #247, #248, and #250 address review feedback.

**Comment by mdgood** [comment]
The W3C Community Group Final Report for MusicXML 3.1 is now available at https://www.w3.org/2017/12/musicxml31/.
