### ISSUE TITLE
Unclear what it means for multimeasure-rest to have an empty body

### ISSUE THREAD

**Issue by mscuthbert** [w3c/musicxml#249]
Referring from #15 -- Not clear what it would mean for a multimeasure-rest to have an empty body -- obviously the number of measures wouldn't be displayed but how many measures of rest would to correspond to?  It might be better to make the body type "positive-integer" instead of "positive-integer-or-empty" and add a separate attribute for "show-number" for %yes-no with default yes.

**Comment by mdgood** [comment]
It would seem the only use for having an empty element value would be to let the application determine the length of the multi-measure rest. But that does not seem very practical as many things go into choosing how to break up these types of rests. I wonder if this was simply a mistake, perhaps from copying and pasting a schema type definition without making a change.

If anybody is using empty `<multiple-rest>` elements, please let us know. At this time my plan is to follow @mscuthbert's suggestion to replace "positive-integer-or-empty" with "positive-integer". This means that some valid MusicXML 3.1 files won't be valid MusicXML 4.0 files if you use the XSD for validation. We try to avoid this, but have done it in the past to fix obvious mistakes in the schema that nobody has been using.

**Comment by mdgood** [comment]
Pull request #326 addresses this by changing the `positive-integer-or-empty` type to `xs:positiveInteger`. Looking at the schema I suspect this was a mistake made when copying the definition over from the `<measure-repeat>` element.
