### ISSUE TITLE
Clarify behavior of bezier-x, bezier-y, bezier-x2, and bezier-y2 attributes 

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#25]
Frank Weinstock's question about the interaction of the bezier-offset attribute with the bezier position attribute led Michael Good (@mdgood) to request clarifying the behavior of the bezier position attributes. From the MusicXML forum discussion at http://forums.makemusic.com/viewtopic.php?f=12&t=2488#p6866:

> I also see that we need to more tightly specify the behavior of the bezier-x, bezier-y, bezier-x2, and bezier-y2 attributes. They are measured from the respective end point (start / stop / continue) of the slur or tie. They are not additive with the bezier-offset, the way that relative-x and relative-y are additive with the offset element.

More precisely, bezier-x and bezier-y are not additive with bezier-offset, and bezier-x2 and bezier-y2 are not additive with bezier-offset2.

In MusicXML 3.0, this documentation is starts at line 1565 in musicxml.xsd and at line 292 in the common.mod DTD file.

**Comment by webern** [comment]
This might be a useful clarification for me to have in 3.1 as we will soon be putting user control handles on curves.

**Comment by mdgood** [comment]
If we bring this in, I think it would be good to also bring in #26 and do both at the same time. I think this would be uncontroversial, so let me do that.

**Comment by mdgood** [comment]
Pull request #199 addresses this issue.
