### ISSUE TITLE
Question : midi parameter change equivalent in musicXML

### ISSUE THREAD

**Issue by MartyLake** [w3c/musicxml#251]
Hello,
I want to create a music application for creating electronic music. It would use musicXML as a serialization format. 
I've been though the proposal and could not find the MusicXML counterpart of midi parameter change (cc). Maybe I missed something? Can someone redirect me to the correct help /source?
Best,

**Comment by mdgood** [comment]
MusicXML does not have a general-purpose MIDI control change message. Some of the MIDI controls are represented in the sound element - for example, by using the pan, damper-pedal, soft-pedal, and sostenuto-pedal attributes. You could add your own application-specific information using either XML processing instructions of the MusicXML other-play element.

**Comment by MartyLake** [comment]
Thanks you for your answer!
