### ISSUE TITLE
Clarify sentence of measure-repeat

### ISSUE THREAD

**Issue by ericfont** [w3c/musicxml#254]
https://github.com/w3c/musicxml/blob/af6380bd23e6e6d35844b27d39276e033a4d9626/schema/musicxml.xsd#L2853

says, "The actual music being repeated needs to be repeated within the MusicXML file."

Does that mean that the music elements from the measure(s) before the (multi-)measure-repeat need to be duplicated into the measure(s) of the (multi-)measure-repeat?

Or does that simply mean that the music elements that are repeated need to simply be present somewhere in the file?  In which case simply being present in the original measures would satisfy the condition, without having to duplicate the musical elements into the measure(s) of the (multi-)measure-repeat.

**Comment by mdgood** [comment]
@ericfont I apologize for the long delay in replying. The intended interpretation is the first one, that the repeats need to be included in each measure of the multi-measure repeat. We can see if we can clarify this in the documentation.

To help us in considering this for MusicXML 3.2, could you please join the W3C Music Notation Community Group? You can join by going to our home page at https://www.w3.org/community/music-notation/ and clicking on the "Join Or Leave This Group" button. If you have any questions about joining please feel free to contact me.

**Comment by ericfont** [comment]
Thank you for this reply!!  I got hung up when trying to implement in MuseScore because this distinction makes a big difference...I can now get back to finalizing that feature.

One other thing that would be valuable is an official example of snippet of valid MusicXML code that exhibits this case from an authoritative source (such as yourself).  I of course can write test cases myself, but it would be better if the other MuseScore devs see one "official" test case that came from an authority.

**Comment by mdgood** [comment]
Thanks again @ericfont for raising this issue. Do you think the updates in #319 clarify this sufficiently? If not, could you please let us know what specific wording might work better?

**Comment by ericfont** [comment]
Yes, thank you.  What you wrote in #254 sufficiently clarifies that nagging question I had.

I have regretfully not been involved with development for the last two years. I guess since MuseScore is starting development for a new version 4.0 and now that this MusicXML documentation wording has been clarified, now is a good time for me to get back to implementing the long-outstanding multi-measure repeats issue (https://musescore.org/en/comment/reply/node/10220).

I am curious about MusicXML's design purpose for repeating the actual music within each measure of the MusicXML file.  Is that to allow the MusicXML to be backwards-compatible so programs which don't implement measure-repeats could simply ignore the measure repeat element but would still import the actual music being repeating for those measures?

**Comment by mdgood** [comment]
Thanks. Yes, that is pretty much the rationale. Requiring the repeats also provides better compatibility with applications that deal more with playback and analysis, not just notation editors.

**Comment by mdgood** [comment]
Resolved by #319.
