### ISSUE TITLE
problem generating JAXB from musicxml.xsd

### ISSUE THREAD

**Issue by jamestomk** [w3c/musicxml#256]
I get the following errors using XJC to parse v3.1 XSD to derive JAXB classes.   Is there a version that fixes this?

parsing a schema...
[ERROR] Element "link" shows up in more than one properties.
  line 5406 of file:musicxml.xsd

[ERROR] The following location is relevant to the above error
  line 5397 of file:musicxml.xsd

[ERROR] Property "Segno" is already defined. Use &lt;jaxb:property> to resolve this conflict.
  line 3031 of file:musicxml.xsd

[ERROR] The following location is relevant to the above error
  line 3038 of file:musicxml.xsd

[ERROR] Property "Coda" is already defined. Use &lt;jaxb:property> to resolve this conflict.
  line 3032 of file:musicxml.xsd

[ERROR] The following location is relevant to the above error
  line 3039 of file:musicxml.xsd

**Comment by jamestomk** [comment]
BTW I think a solution lies within the suggestion of [this stackoverflow discussion](https://stackoverflow.com/questions/4394134).   For example I added the following for line 3038, and similar for the two others and it at least generated the classes:

> 
		<xs:sequence>
			<xs:element name="credit-type" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="link" type="link" minOccurs="0" maxOccurs="unbounded">
				
                			<xs:annotation>
                    			<xs:appinfo>
                        			<jxb:property name="linkElement"/>
                    			</xs:appinfo>
                				</xs:annotation>
			</xs:element>

and similar for 3 other errors.  It appears what is generated is correct:
>
@XmlType(name = "credit", propOrder = {
    "creditType",
    "linkElement",
...
public class Credit {
...
    @XmlElement(name = "link")
    protected List<Link> linkElement;

**Comment by mdgood** [comment]
Thank you for sharing your solution to this issue. I think you may want to consider creating a JAXB bindings file, rather than altering the MusicXML schema definition. That way you would not need to redo your work if we release an updated MusicXML version in the future.
