### ISSUE TITLE
part-list/score-part should have an attribute of maxOccurs="unbounded"

### ISSUE THREAD

**Issue by jamestomk** [w3c/musicxml#257]
I wonder if part-list/score-part should not also be defined with an attribute of maxOccurs="unbounded".   I am exporting MusicXML from MuseScore and that seems to be how they interpret score-part; as a List.  If I generate JAXB classes from your def, I only get a single item scorePart of ScorePart class.

> 	<xs:complexType name="part-list">
.
.
.
		<xs:sequence>
			<xs:group ref="part-group" minOccurs="0" maxOccurs="unbounded"/>
			<xs:group ref="score-part"/>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:group ref="part-group"/>
				<xs:group ref="score-part"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

**Comment by jamestomk** [comment]
Thus far what I find is the following.  It will generate correct classes without error, and a round trip of unmarshal/marshal produces identicle MusicXML file.   However, I cannot generate proper XSD from the JAXB Java.   Note two lines are commented out:

>
 		<xs:sequence>
			
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:group ref="part-group"/>
				<xs:group ref="score-part"/>
			</xs:choice>
		</xs:sequence>

**Comment by mdgood** [comment]
Thank you for your suggestion. However, the part-list definition is correct as written in MusicXML 3.1.

Within a part-list element, you must have at least one score-part child element. That element is optionally preceded by one or more part-group elements. After the first score-part element is a mix of score-part and part-group elements.

Your rewritten definition does not appear to require a part-list element to have at least one score-part child element.

There are some parts of the MusicXML schema that can cause problems for some automatic binding tools like JAXB. These generally seem to be issues with the binding tools. Sometimes they also reflect limitations in the way that the XSD schema lets you write language definitions.

Perhaps other JAXB users have some suggestions they can share for working around these issues? Might a JAXB bindings file be able to solve this problem like it could for #256?
