### ISSUE TITLE
Dynamics placement

### ISSUE THREAD

**Issue by mgiu** [w3c/musicxml#258]
Hi! Is there a way to place a dynamic under a note (or chord) without specifying the default-x, default-y position? Trying to explain better: is there a way I can write MusicXml code that can be interpreted by Finale/Dolet-Plugin as a note (or chord) with below a dynamic without specifying the default-x, default-y position?
Thanks in advance,
 Matteo Giuliani

**Comment by mdgood** [comment]
The placement attribute of the `<direction>` element should do this. If that is not working with Finale, you may want to contact Finale technical support.
