### ISSUE TITLE
<lyric> positioning and alignment

### ISSUE THREAD

**Issue by DavidMWebber** [w3c/musicxml#261]
Can anyone tell me where default-y on a <lyric> element is measured from and to?    (From somewhere on the staff to the base line or top of the text???)   The explanation in note.mod isn't very specific.

**Comment by mdgood** [comment]
The default-y attribute is defined in common.mod rather than note.mod. It nearly always is in reference to the top line of the staff, and this is true for the `<lyric>` element.

The exceptions are the `<credit-words>` and `<credit-image>` elements, which are outside of the musical structure and do not have a staff to reference. For those elements, default-y refers to the bottom left corner of the page.

**Comment by DavidMWebber** [comment]
Thanks for this Michael.    Up to now I haven't been exporting the default-y attribute on lyrics, and just letting any importing software cope with it, but I'm trying to do better :-)

I was also concerned about the 'other end': default-y could be for the top of the text line area, the bottom of the text line area, half way up the text line area, or the text base line.   Base line would make general sense, but when programming Windows any of the others would too  :-).   [Thus far my (limited) experiments seem to indicate that "half-way-up" seems to work, but I'm not sure I''ve resolved the difference between that and the text base line.]

**Comment by mdgood** [comment]
@DavidMWebber I apologize for the delay in answering this second question. I see the issue now. We either need to document the vertical alignment for lyric text, and/or add a valign attribute to either the`<lyric>` or `<text>` element to allow this to be specified exactly.

To help us consider this for MusicXML 3.2, would you be able to join the W3C Music Notation Community Group? You can join by going to our home page at https://www.w3.org/community/music-notation/ and clicking the "Join Or Leave This Group" button.  Please let me know if you have any questions about joining the group. Membership is free of charge. Thanks!

**Comment by DavidMWebber** [comment]
Thanks Michael,

 

I worked out the optimum lyric positioning by trial and error – propbably good enough for the moment.

Thanks for the invitation.  I’ve joined the group.  I hope I’ll be able to contribute (after the next week or so when I’m abroad on business).  My MusicXML work goes in fits and starts – I have periods when I improve my MusicXML import/export module, and long periods in between when I don’t touch it.     But it will be good to keep in touch with MusicXML developments.

Best regards,

Dave

 

David Webber

Mozart Music Software

http://www.mozart.co.uk

**Comment by mdgood** [comment]
Hi @DavidMWebber or other - Have you found any applications that are using something other than baseline for lyric vertical alignment? If we don't have a practical use case for adding a vertical alignment option, I would rather just document the baseline alignment. On the other hand if we have a missing feature that is causing exchange problems, now is the time to work on it. Thanks!

**Comment by DavidMWebber** [comment]
Hello Michael,

For actual lyrics along the line under/over the notes, baseline alignment would be universal, I think.

Some related thoughts: (you’ve probably got these covered but it’s a year or two since I worked on my MusicXML module and my memory of the scope and syntax is getting a bit iffy, so please forgive me if these are completely irrelevant).


1 If the music switches from (say) three lyric lines to two, then the vertical position of the baselines will usually change.  Schematically:

 

…

     …

…

     …
…

 

2. There are other things which sit in a line above/below the staff.

Chord names or roman numerals will usually be aligned on their baseline.

But I guess ‘polychords’ – (two chord names vertically arranged with  line between them) eg

C
_

G7

may be vertically aligned on their centre?

Also Basso Continuo symbols (eg)

5
3

 

may be vertically aligned on their centre?



(These are things I’ve had to think about in my own software, but have not yet looked at in MusicXML, so please ignore it all if it is irrelevant!) 


All the best for 2021,

 

Dave

 

David Webber
Mozart Music Software
https://www.mozart.co.uk

**Comment by mdgood** [comment]
Thanks @DavidMWebber! Each individual lyric can be positioned independently, so I think we are good there. Similarly, each part of a polychord can be positioned and aligned independently, and each figure within figured bass can be positioned independently. Figured bass currently does not allow for specification of alignment. As with lyrics, it seems like a good idea to explicitly specify baseline alignment.

**Comment by mdgood** [comment]
However, since neither justification nor alignment (horizontal or vertical) can be specified for figured bass, it seems good to address that in a separate issue. It could be helpful to be able to specify justification as one can for lyrics.
