### ISSUE TITLE
Question: tempo equivalence

### ISSUE THREAD

**Issue by cecilios** [w3c/musicxml#264]
When there is a change in time signature there could exist a metronome mark to establish the equivalence between the old tempo and the new tempo, e.g. 'doted quarter = quarter'. I understand that this is visually notated using the 'metronome' directive. But for playback, is it necessary to include also a 'sound' directive or the player must infer the tempo change from the metronome tag? If it is necessary to include a sound directive, how will it be encoded? perhaps by using the divisions element?

Please, could any one provide an example? Thank you very much.

**Comment by mdgood** [comment]
With all metronome directions, it is best if the application includes a `<sound>` element with a tempo attribute to specify the desired playback. This includes metric relationships.

The tempo attribute value is expressed in quarter notes per minute. A metric relationship will usually specify some sort of scaling of the tempo value from what was specified earlier. The exception would be a case like eighth = eighth when moving from 2/4 to 6/8.

**Comment by cecilios** [comment]
Thank you Michael.

For checking my understanding:

Lets assume that initially there is `<sound tempo=100 />`

Case a) If moving from 2/4 to 6/8 and we would like eighth = eighth then no `<sound>` tag is necessary in the same measure than the 6/8 time signature as the tempo, in quarter notes per minute, will be the same.

Case b) If moving from 2/4 to 6/8 and we would like quarter dotted = quarter then we would need to include `<sound tempo=150 />` in the same measure than the 6/8 time signature.

Is this correct?

Now another question related to case b. If the initial sound tag is `<sound tempo=0 />` (prompt the user), how should be encoded the second sound tag?

Thank you.

**Comment by mdgood** [comment]
@cecilios I apologize for the delay in replying. Your understanding seems fine to me. There is not really a good way to handle the `<sound tempo="0"/>` case. I don't think the "prompt the user" semantics is widely supported either.

**Comment by mdgood** [comment]
I am closing this issue as it appears to be resolved. If we do not already have an issue for the overall `<sound tempo="0"/>` feature, I will open one. It needs revised documentation and perhaps is a target for deprecation.
