### ISSUE TITLE
Add defaults to xsd schema?

### ISSUE THREAD

**Issue by mscuthbert** [w3c/musicxml#265]
Looking at the reference for musicxml, for instance:
https://usermanuals.musicxml.com/MusicXML/Content/CT-MusicXML-tuplet.htm

There are a lot of places where default is left blank but a default is actually specified in comments.  Would the group like a pull request where some of these defaults are included in the .xsd files?  Thinking of things like "show-number" where it is easy to add `default="actual"` to the .xsd file.

**Comment by mdgood** [comment]
Thanks for this suggestion. This was a deliberate design choice. In the very early days we did have default values for most attributes. However we found that supplying default values tends to increase memory consumption in validating DOM parsers, and MusicXML is already pretty heavy with memory use. 

In some cases it seemed to make sense, where for readability you would probably want to specify the default value in the document anyway. In most cases the tradeoff did not seem to be worth it.

We can of course revisit this, but I wanted to share the rationale for why it works this way in MusicXML 3.1.

**Comment by mscuthbert** [comment]
If it's deliberate choice then I understand.  I just thought that if it were a machine-readable default then I could set a parser to automatically set the values, but if the tradeoff is not worth it, then that's okay.

(this just came from a potentially ambiguous reading of the slash attribute for grace; I can't remember if the default used to be "yes" "no" or up to the parser.  I figure that grace notes by default have slashes (otherwise it's not a grace note)).
