### ISSUE TITLE
Namespace for MusicXML

### ISSUE THREAD

**Issue by josteinaj** [w3c/musicxml#266]
Is there a namespace that can be used for MusicXML, in case I want to mix it with other XML vocabularies? Maybe something like `http://www.w3.org/2017/MusicXML`?

**Comment by mdgood** [comment]
Unfortunately, MusicXML 3.1 does not have a standard XML namespace. Adding a namespace in a future version would make future MusicXML files incompatible with current MusicXML files and could break a lot of applications. 

However, an individual application could add a namespace, and modify a local version of the schema accordingly.

**Comment by josteinaj** [comment]
Ok, thanks.

Do you have a preference or a suggestion for what namespace could be used?

**Comment by mdgood** [comment]
@josteinaj At the moment I do not have a suggestion. I do see the value in adding a suggested namespace for applications to use when MusicXML is mixed with other vocabularies.

To help us consider this for MusicXML 3.2, would you be willing to join the W3C Music Notation Community Group? You can join by going to our homepage at https://www.w3.org/community/music-notation/ and clicking the "Join Or Leave This Group" button. Please do join on behalf of NLB or DAISY as appropriate. If you have any issues while joining, please let me know. Thanks!

**Comment by josteinaj** [comment]
Hi. Sorry for the late reply. I wouldn't have much to contribute to the group personally, and I don't really have time for it either. My only suggestion at this point is to define a namespace so that it's easier to have it flowing through systems together with other content.

**Comment by mdgood** [comment]
@josteinaj I was mistaken. While doing our initial update to MusicXML 4.0, I see that we already have specified this in MusicXML 3.1:

> Those who need to import the MusicXML XSD into another schema are advised to create a new version that uses "http://www.musicxml.org/xsd/MusicXML" as the namespace.

**Comment by josteinaj** [comment]
That's perfect, thanks!
