### ISSUE TITLE
Clarify use of tie / tied without type=stop

### ISSUE THREAD

**Issue by ewanmellor** [w3c/musicxml#272]
Please clarify the use of tie / tied with a type=start but without a corresponding type=stop.

The following extract is from a file generated by Dolet 6.1 for Sibelius.  As you can see, the XML uses `<tie type='start' />` and `<tied type='start'/>` on the first note, but there is no 'stop' element on the second note for either of those.

                        <software>Sibelius 6.2</software>
                        <software>Dolet 6.1 for Sibelius</software>
                         ...
                        <note>
                                <pitch>
                                        <step>B</step>
                                        <alter>-1</alter>
                                        <octave>6</octave>
                                </pitch>
                                <duration>256</duration>
                                <tie type='start'/>
                                <voice>1</voice>
                                <type size='cue'>eighth</type>
                                <time-modification>
                                        <actual-notes>6</actual-notes>
                                        <normal-notes>4</normal-notes>
                                        <normal-type>16th</normal-type>
                                </time-modification>
                                <staff>1</staff>
                                <beam number='1'>end</beam>
                                <notations>
                                        <tied type='start'/>
                                        <tuplet number='1' type='stop'/>
                                </notations>
                        </note>
                        <note>
                                <pitch>
                                        <step>B</step>
                                        <alter>-1</alter>
                                        <octave>6</octave>
                                </pitch>
                                <duration>128</duration>
                                <voice>1</voice>
                                <type size='cue'>16th</type>
                                <time-modification>
                                        <actual-notes>6</actual-notes>
                                        <normal-notes>4</normal-notes>
                                </time-modification>
                                <staff>1</staff>
                                <beam number='1'>begin</beam>
                                <beam number='2'>begin</beam>
                                <notations>
                                        <tuplet number='1' type='start'/>
                                </notations>
                        </note>

Looking at the rendered score, this is obviously intended to be a tie between these two notes. 

<img width="97" alt="screen shot 2019-02-17 at 5 02 59 pm" src="https://user-images.githubusercontent.com/894011/52922410-eb61f880-32d5-11e9-9edd-04806dccbb28.png">

However, from the schema documentation, I don't see anything that says that you are allowed to omit the stop element in this way.  It says "A tied element which joins two notes of the same pitch can be specified with tied-type start on the first note and tied-type stop on the second note.  [...]  For other ties that are visually attached to a single note, such as a tie leading into or out of a repeated section or coda, use two tied elements on the same note, one start and one stop."

That implies that omitting the stop element isn't allowed, but it's not definitive, and it doesn't say how the XML should be interpreted in that case.  Obviously, it makes it much harder to interpret the XML if you have to search an arbitrary distance forward for stop elements that may or may not be present.

Please clarify the documentation in this regard.  In my opinion, Dolet 6.1 has generated invalid MusicXML here, but I would like to have that confirmed.

Note that I have seen #142, and I don't think that this issue is related.  That issue is specifically for ties that intentionally have no end note, whereas the notes in this issue are meant to be tied together.  Besides, type='let-ring' is not in use here.

**Comment by mdgood** [comment]
@ewanmellor I agree this looks like an incorrect export by the Dolet for Sibelius plug-in. If you could email me the Sibelius file that causes this problem that would be great.

To help us address this in the MusicXML 3.2 documentation, would you be willing to join the W3C Music Notation Community Group? You can do this by going to our home page at https://www.w3.org/community/music-notation/ and clicking the "Join Or Leave This Group" button. If you have a problem while signing up please let me know. Thanks!

**Comment by ewanmellor** [comment]
Sorry, but I don't have the Sibelius file.  This was purchased as a MusicXML file and PDF.

**Comment by benspratlingdriveclutch** [comment]
I have many many examples of Sibelius 7 exporting invalid MusicXML files.

**Comment by mdgood** [comment]
@benspratlingdriveclutch If these are exported by the Dolet for Sibelius plug-in I would be interested in seeing them. I cannot do anything about Sibelius's native MusicXML export though. 

In any event it would be good if we could clarify this issue, especially from the perspective of someone creating MusicXML files.

**Comment by scorio-dev** [comment]
How do you differentiate between incoming and outgoing ties?

Can anybody please give me the correct MusicXML 3.1 encoding of tie/tied for the red and for the blue note in this example:

![grafik](https://user-images.githubusercontent.com/20552494/61939007-a0d65d80-af92-11e9-9aa9-8f29c5cb0e80.png)

The schema documentation says: "For other ties that are visually attached to a single note, such as a tie leading into or out of a repeated section or coda, use two tied elements on the same note, one start and one stop." 
The schema documentation for 3.1 says: "Ties that are visually attached to only one note, other than
undamped ties, should be specified with two tied elements on the
	same note, first type="start" then type="stop". This can be used
	to represent ties into or out of repeated sections or codas."

**Comment by mdgood** [comment]
@jofeux I apologize for the long delay in replying. These could be disambiguated using the number attribute, but ordering should also suffice. If you have 3 tied elements on the red note, the first should be a stop (from the preceding note), the second should be a start, and the third should be a stop to go with the start. I think we could clarify this in the documentation.

**Comment by mdgood** [comment]
The documentation clarification looks like it could be part of #8. I am closing this issue as it reporting a software bug rather than a MusicXML issue.
