### ISSUE TITLE
Mark notes on the same stem as being different parts

### ISSUE THREAD

**Issue by samuelbradshaw** [w3c/musicxml#277]
This issue applies to hymn singing; I'm not sure how common the issue is in other domains. In hymnals, sheet music is normally written as a piano score, with lyrics written between the two staves. This becomes a problem in a digital application that allows you to show or hide parts. For the singer, there are four parts (SATB), but the music is notated with only two parts (left hand and right hand) because displaying the notes as chords takes up less space and is easier for the accompanist to play.

A great feature some MusicXML-rendering applications provide is the ability to show or hide (or play back) individual parts in the score. However, in this case, the application only recognizes two parts. There's no way to show only the soprano part (for example) using the same MusicXML file that shows all four parts.

Is it possible to mark notes on the same stem, or in the same chord, as actually being different parts?

![hymn-combined-parts](https://user-images.githubusercontent.com/7323052/54478855-6b4b8780-47dc-11e9-9ae5-95f8a87a2b22.png)

**Comment by mdgood** [comment]
MusicXML can do this by using different `<instrument>` elements for each note in the chord. I don't believe this is clearly documented though and I doubt that it is widely implemented. This could be addressed more systematically as we try to improve part support in MusicXML 3.2.

**Comment by mdgood** [comment]
Thanks again @samuelbradshaw for raising this issue. One thing we could do here is to add zero or more `<part-instrument>` child elements to the `<part-link>` element we added as part of #278. This would refer to a `<score-instrument>` ID and indicate which instruments are included in which parts.

For instance, a score that has first and second clarinets as one part in the score but in separate two parts files could use two `<score-instrument>` elements and two `<part-link>` elements. Each `<part-link>` element would contain a single `<part-instrument>` element pointing to the correct `<score-instrument>`.

if we also add an optional `<part-group>` child element to the `<part-link>` element, that could help resolve the issue of including condensed scores that @mscuthbert raised in #278.

**Comment by mdgood** [comment]
However we currently only allow one `<instrument>` element per note. The tenor and bass would work in bar 4 if there were two separate notes, one for the tenor and one for bass. However it is common in much writing to have a single note for both parts - not even double-stemmed as in bar 4, if it is a long section where the two voices sing together.

We could perhaps address this by allowing more than one `<instrument>` element per note. However that may have some impact on applications that rely on that single instrument maximum. 

I am afraid that we may need to move this out of the 4.0 milestone, unless someone has a great idea on how to address this that is low risk to add at this stage.

**Comment by mdgood** [comment]
On second thought, I think we can avoid the problems I was seeing by adding a `sound` attribute to the `<instrument>` element. This attribute controls which sound to use for a note if multiple `<instrument>` elements are present. Only one `<instrument>` per not may have `sound="yes"` set. By default, the first `<instrument>` has `sound="yes"` and the rest have `sound="no"`.

That way we can specify multiple instruments per note both for interactivity and mapping from score to part, without causing problems for applications doing straight MIDI playback off of a MusicXML file that need to know which sound to use for a given note.

I will need to think about this some to see if this is really something we want to change at this point. Other suggestions are most welcome, along with your thoughts on whether we should keep this issue in 4.0 or not. Thanks!

**Comment by mdgood** [comment]
We can probably do this just by increasing the number of `<instrument>` elements allowed in a `<note>` element, without needing to add a new attribute. I am working on this now and plan to have a pull request ready for review soon.

**Comment by mdgood** [comment]
Pull request #396 addresses this issue. There are some differences from what was described above:

- The names of the optional child elements are `<instrument-link>` and `<group-link>` rather than `<part-instrument>` and `<part-group>`. The `<part-group>` name is used elsewhere and it seemed good for the child elements to have consistent naming.
- A `<note>` element can now have more than one `<instrument>` child elements.

I think this should address both @samuelbradshaw's issue here, along with improving the score and parts support from #278 along the lines suggested by @mscuthbert. If you two have a chance to review this that would be great - thanks!

**Comment by samuelbradshaw** [comment]
Sounds like a good plan to me! Thanks.

**Comment by mscuthbert** [comment]
I missed this when it was discussed, but I am EXTREMELY happy with this change and also with not having the restriction of only one instrument sounding -- MIDI performances from musicxml that cannot handle more than one instrument at a time can ignore all but the first instrument element on a note, just as the `to31.xsl` stylesheet does it.  There was something I think that was missed about octaves that I will address in another Issue.
