### ISSUE TITLE
Include both score and parts information in a single file

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#278]
One source of problems when moving MusicXML scores between applications is that MusicXML 3.1 is oriented around the score. There is no standard method for including data for both the score and each individual part within a single MusicXML file.

Many different musical elements can differ between score and parts. These include formatting issues such as page sizes, system breaks, and multi-measure rests, but also more semantic issues such as enharmonic pitch spelling.

While MNX is working on designing this capability in from the beginning, we still want to be able to communicate this information in MusicXML. This is true even if the solution is not as elegant as we could design in MNX, given the need for MusicXML to maintain compatibility with older versions.

Perhaps the simplest way that could work is to simply include each part in MusicXML format within a compressed MusicXML files. The main score file that is referenced in the META-INF/container.xml file could then contain links to the individual part files. These links could be done by adding an optional `<link>` element as a child of a `<score-part>` element.

For an earlier discussion on this issue, see https://forums.makemusic.com/viewtopic.php?f=12&t=2206 from the MusicXML forum / mailing list.

**Comment by jsawruk** [comment]
I like this approach because the score and parts are collected together into a single file.

**Comment by mscuthbert** [comment]
Will other related scores be able to be included?  For instance, band collections often include both a Full Score and a Condensed Score.  Also thinking that researchers might want to include different versions of the same piece within a collection (the 1913 version vs. the revised 1947 version of a score), etc.

The specifics of how to do things like this are beyond the scope of this issue, but thinking about these issues for even a few minutes will presumably enable these applications in the future.

**Comment by mdgood** [comment]
MusicXML does include a `<group>` element that was intended to distinguish different types of uses for an individual `<score-part>`. This has not been used in the past but perhaps we could get it used now with scores and parts in a single compressed file.

Because applications are not looking for this element, I don't think we want to put the part versions in the same uncompressed MusicXML text file as the score versions. Separate MusicXML files within a compressed MusicXML file with a `<link>` element at the start of the `<score-part>` element still seems like the right way to go. However we could encourage apps that do this to use `<group>score</group>` for the `<score-part>` elements in their score file, and `<group>parts</group>` for the `<score-part>` elements in their parts files.

This might then give us a way to handle multiple versions, at least for distinct types like a condensed score. @mscuthbert, if you have any particular suggestions for how this might work please feel free to share.

If people have other ideas for how to combine score and parts in one file, please share them here. If the current approach seems good I would like to get a pull request in later this week. If there are alternatives this would a great time to discuss them - thanks!

**Comment by mdgood** [comment]
Pull request #334 addresses this issue. Instead of adding a `<link>` element to the `<score-part>` element, it uses a `<part-link>` element instead to reflect the more specific semantics. The child elements of the `<link>` element are not applicable here, for instance. There may be 0 or more `<part-link>` elements, which supports the case of a "Clarinet 1 and 2" MusicXML part in the score linking to separate "Clarinet 1" and "Clarinet 2" parts in the .mxl file.

This is one of the major new features for MusicXML 4.0. It would be great if folks could review this pull request to make sure it is meeting the needs for your applications. Thanks!
