### ISSUE TITLE
Represent transpositions in concert pitch scores

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#279]
In MusicXML 3.1, the `<transpose>` element represents what must be added to written pitch to get the correct sounding pitch. In concert pitch scores we have a need to go in the other direction: what must be adding to the sounding pitch to get the written pitch for transposed parts?

Issue #278 could address this by the inclusion of each transposed part in a compressed MusicXML file. However, it seems that the transposition information would best be represented directly in the MusicXML representation of the concert score. This would allow the transposition information to be represented in an uncompressed MusicXML file without the need for extra part files.

A solution to this issue should also take into account issue #39, where octave transpositions from written to sounding pitch are still needed in concert scores.

The new data to represent this information should be added in a way that will not confuse applications that only support MusicXML 3.1 and earlier versions. 

For an earlier discussion on this issue, see https://forums.makemusic.com/viewtopic.php?f=12&t=2206 from the MusicXML forum / mailing list.

**Comment by jsawruk** [comment]
Initial suggestion: Since we don't want to break the `<transpose>` element, and this element means written -> sounding, could we create a new element that would mean sounding -> written?

For example, we might call it `<transpose-to-written>` or something to that effect. Having a separate tag name would not break any previous applications, even though this is probably not the most elegant solution.

**Comment by mdgood** [comment]
@jsawruk I like this idea. Perhaps we could call that element `<to-transpose>` to indicate that it is what you need to create a `<transpose>` element in the corresponding part.

I am wondering if we should also have an element somewhere in the score-header group that identifies a concert vs transposing score so the application does not have to search for the presence of `<to-transpose>` elements to detect a concert score. A concert score might still have `<transpose>` elements for octave transpositions. Perhaps that could be somewhere within the `<defaults>` element?

**Comment by mdgood** [comment]
I still like this idea of having a separate element representing what needs to be added to go from the pitch in the score to the pitch in the part, and an additional `<defaults>` child element to indicate a concert / C score.

Maybe we could us `<part-transpose>` to indicate this is what needs to be added to go from the score pitch to the part pitch? 

To quickly indicate a concert / C score, we could add an empty element to the `<defaults>` element. But what to call it: `<concert-score/>`, `<c-score/>`, or something else? Concert scores can still include instruments with octave transpositions.

**Comment by mdgood** [comment]
After reviewing #39 and #55, it seems another alternative would be to add an optional `<for-part>` to the `<attributes>` element. This could then contain `<clef>` and `<transpose>` elements. Since they are in a separate child element, reusing the existing element names could work. Or we could make these `<part-clef>` and `<part-transpose>` elements if people prefer.

**Comment by mdgood** [comment]
Addressed by #340.
