### ISSUE TITLE
Improve cross-staff arpeggio support

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#281]
In MusicXML 3.1, arpeggios that go cross staff across two sets of chords are indicated by having the number attribute of the `<arpeggiate>` element be the same value for both chords. In practice this has not worked very well, and cross-staff arpeggios typically do not transfer well between applications.

We should see what we can do to improve this situation. Perhaps it could be a matter of seeing if cross-staff arpeggio support can be improved in applications using the existing arpeggiate feature. If not, perhaps there is something we can add to the `<arpeggiate>` element to make this transfer work better. In any event it would probably help to clarify the documentation.

**Comment by hhpmusic** [comment]
I'd prefer to use an additional attribute, since the numbers are limited to 6 usually, while there may be cases that a measure may contain more arpeggios such as an imitation of harp in piano part, 8 8th notes in 4/4 time. If the right hand is stated completely first, then the number has to be raised to 8 for lh to match. Am I right?

**Comment by mdgood** [comment]
Another suggestion that @hhpmusic and the DAISY Music Braille Project have made for this is:

> For arpeggiated lines, include an attribute to indicate whether it's for two staves, thus a connect-staff arpeggio. A length value doesn't make any sense for braille transcription. Although the software may not export this attribute automatically (if the developers don't change the behaviour of the software), we can still manually mark it up with the attribute to get correct braille signs.

**Comment by mdgood** [comment]
We could add an `unbroken` attribute to the `<arpeggiate>` element to offer a hint that the arpeggio is unbroken across multiple staves in the part. The value would be yes or no, and typically would only be specified if the value is yes. The "unbroken" terminology for cross-staff arpeggios is used by both Gould and Read.

As @hhpmusic suggests, it would be good to increase the range for the `number` attribute to at least 1 through 8. If we increase the `number-level` range in #297 we can leave the `<arpeggiate>` definition as is. Otherwise we could change the `number` attribute to use a new type with a larger numeric range.
