### ISSUE TITLE
Update imported schemaLocation attributes

### ISSUE THREAD

**Issue by deepio** [w3c/musicxml#285]
Successfully validating musicXML files has not been possible until the modification of a few strings in the schema, more information is available in the pull request here: https://github.com/w3c/musicxml/pull/284 

I would like to know:
  - Is there a better solution than the one I proposed in the pull request?
  - If the problem does not come from the schema but the python `lxml` module, what part of these two lines is being misinterpreted?

**Comment by mdgood** [comment]
Instead of the change proposed in the pull request, have you tried changing the http:// in the schema location to https://? Maybe something in that module cannot handle the redirection to https://?

It seems it would be good to update this schemaLocation to https in MusicXML 3.2. We can also see how this might interact with the catalog issue #259.

**Comment by deepio** [comment]
Using https on `w3.org` or `musicxml.org` did not work, the error might then come from the lxml module not being able to handle https for xml validation. Odd for a module that has been around for so long, I will investigate further at a later date.

**Comment by mdgood** [comment]
This was later undone by #384, fixing issue #259. Using catalogs seems a better way to fix this overall issue.

**Comment by mirabilos** [comment]
Undoing this in #384 is **bad**.

It says:

> The XML catalog at catalog.xml supports validating against a local copy of this DTD rather than the networked version in the system ID. Software often has trouble using system IDs due to factors such as restrictions on network access, or resources having moved from the original specified location.

However, most XML validation software cannot work with catalogues. They need DTDs or XSDs, many accept either. I’ve never seen XML/SGML catalogues used in the wild, *anywhere*, in over two decades.
