### ISSUE TITLE
Challenging notation

### ISSUE THREAD

**Issue by maximumspatium** [w3c/musicxml#286]
During the development of our optical music recognition system [Audiveris](https://github.com/Audiveris/audiveris/tree/master), we encountered the following uncommon notation:

![counter-melodie](https://user-images.githubusercontent.com/6561800/58553843-46c94e00-8216-11e9-8fad-cd71de559468.png)

This case has been already described by Elaine Gould in her book [Behind bars](https://www.fabermusic.com/news/elaine-goulds-behind-bars-is-a-worldwide-hit-567) (page 311) as follows:

> It is accepted convention to visually point a melodic line with separate stems but without additional rests.
> [...] Separate stems can also function to point counter-melodies. Nineteenth-century composers, in particular, commonly added beams as well, to show the progression of simultaneous parts.

To demonstrate the issue, she points to the final movement of Schumann's [Piano Sonata No.3, Op.14](https://imslp.org/wiki/Piano_Sonata_No.3,_Op.14_(Schumann,_Robert)). Below two excerpts from Breitkopf & Härtel edition from 1887:
![Schumann Piano Sonate 3rd movt 1](https://user-images.githubusercontent.com/6561800/58555548-0bc91980-821a-11e9-9d7b-877b9a7f4e5c.png)
![Schumann Piano Sonate 3rd movt 2](https://user-images.githubusercontent.com/6561800/58555555-0e2b7380-821a-11e9-8f3f-d0464c8c191b.png)

I'm afraid the beaming in the latter example is practically impossible to recreate with the state-of-the-art notation software except the old famous [SCORE](https://en.wikipedia.org/wiki/SCORE_(software)) and maybe Finale.

Audiveris is already capable of recognizing all notational elements (including that challenging beaming) correctly. Our problem arises when we're trying to map the graphical representation to MusicXML so the music can be exported from Audiveris and imported in a notation editor for further editing. For further details, please refer to the dedicated Audiveris issue https://github.com/Audiveris/audiveris/issues/279.

The rhythm in the upper voice of the first example is strictly speaking wrong. It's still possible to recreate it in a notation editor using hidden tuplets and rests. The following example shows how it can be done in Musescore (the gray elements are hidden):

![separate stems with beams Musescore](https://user-images.githubusercontent.com/6561800/58556472-6bc0bf80-821c-11e9-9c08-0a4e1e7854d7.png)

The question is how to model this kind of notation in MusicXML, in particular, how to encode beams over rests and hidden rests/tuplets. Another question is whether the graphical representation shown above can be retained during MusicXML export/import.

Thank you in advance for your help!
Max Poliakovski, Audiveris OMR project

**Comment by mdgood** [comment]
@maximumspatium I apologize for the delay in replying to this. 

I believe that everything here can already be done in MusicXML 3.1. You can hide various objects using the `print-object="no"` attribute. In the first bar of the first Schumann example, you might want to use a `<note print-dot="no">` element to hide the dot that is needed on the downstem C eighth note. Beaming over rests is handled automatically as long as the beam elements are specified correctly in the same voice.

Finale is usually good about exporting these types of cases. You may want to try encoding these examples in Finale - making sure they both play back correctly and look correct - and then see how they get exported.

If there is anything you believe is missing from MusicXML 3.1 please let us know.

**Comment by mdgood** [comment]
I am closing this as it does not appear to require any changes in a future MusicXML version. If you believe things are still unresolved please let me know and we can reopen if needed.
