### ISSUE TITLE
Add new metronome-relation element values

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#29]
The metronome-relation element currently only defines the value of "equals" for an = relationship within a metronome mark. It would be more flexible to allow other standardized values, such as a wavy equals sign to indicate an approximate value. If more values are added, the XSD definition might want to change from a string to an enumeration of acceptable values.

See the MusicXML forum discussion started by Jari Williamsson at http://forums.makemusic.com/viewtopic.php?f=12&t=1941.

**Comment by jsawruk** [comment]
The only other relation that I think would be needed is approximately (two squiggly lines ≈, U+2248). One squiggly line could also mean approximately, which could be represented as a tilde ~ or as U+223C by the notation software, though I don't recall seeing this in music notation.

I do not see a reason to add any other relation, such as not equals, or greater than / less than relations.

My recommendation is to change the defintion from xs:string to xs:enumeration and add the value "approximately" (or "approximate"). The client could then determine how to represent this value, either as 1 or 2 squiggly lines, or as "= c. " for "equals circa". Alternatively, you could get more explicit and define these three separate approximate notations.

**Comment by mdgood** [comment]
Another value we could include would be "none", when the beat is followed directly by the numeric values without an equals sign, as found in scores by Hindemith.

**Comment by mdgood** [comment]
The metronome-relation element is only used by the markings that Elaine Gould refers to as tempo equations in _Behind Bars_, pp. 185-187. Its main purpose is to mark the dividing line between groups of metronome-note elements. I would like to take this out of scope for version 3.1.

**Comment by mdgood** [comment]
Given the clarification of how the metronome-relation element works, I am closing this issue.
