### ISSUE TITLE
Clarify ending element documentation

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#291]
Currently the documentation for the `<ending>` element states that "the number attribute reflects the numeric values of what is under the ending line." This is not entirely correct. When using a comma-separated list of numbers, the number attribute represents on which passes the ending is played back, similar to how the time-only attribute is used with other elements. 

Besides formatting differences such as punctuation, the list of passes can be different in situations such as a first and second ending contained within a larger D.S. repeated section. In this case the number element can be used to represent whether or not the first ending is used during the D.S. repeat.

**Comment by mdgood** [comment]
Pull request #318 addresses this issue.

**Comment by seffka** [comment]
I posted some clarification to #322 claiming that it's not a duplicate of #291, because the problem described may appear without `<ending>` element. `<repeat>` element and "D.C. al Coda" is enough. Could you please check #322 again?

**Comment by mdgood** [comment]
Thank you for the clarification. You are correct that #322 is not a duplicate of this issue so I have reopened it.
