### ISSUE TITLE
Allow virtual instrument changes similar to MIDI instrument changes

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#293]
In MusicXML 3.1, the `<sound>` element can contain `<midi-device>` and `<midi-instrument>` child elements. This allows for MIDI playback changes for parts that change sounds, such as woodwind doublings between saxophone and flute.

However, no such capability exists for switching virtual instrument playback using the `<instrument-sound>`, `<solo>`, `<ensemble>`, and `<virtual-instrument>` elements. There thus is no direct way to represent the same type of playback change for parts with doublings in virtual instrument terms as there is in MIDI terms.

One can workaround this by using the `<other-play>` element, or by using multiple `<score-instrument>` elements and specifying the `<instrument>` for each note. This approach however was meant for percussion parts and condensed scores, not for parts with doublings where only one sound is being played at any given time.

MusicXML could address this by allowing the `<instrument-sound>`, `<solo>`, `<ensemble>`, and `<virtual-instrument>` elements to also be child elements of the `<sound>` element.

**Comment by jsawruk** [comment]
I think that's a reasonable approach.

**Comment by mdgood** [comment]
Pull request #328 addresses this issue. In order to add a reference back to a particular score-instrument, I needed to add an `<instrument-change>` element to group together the `<instrument-sound>`. `<solo>`, `<ensemble>`, and `<virtual-instrument>` elements.

While working on the to31.xsl file, I noticed a transformation that is not used. I removed it from the other .xsl files as well.
