### ISSUE TITLE
Info on 2.0 compressed files

### ISSUE THREAD

**Issue by dbolton** [w3c/musicxml#296]
Is there some information (or better yet) a sample of a version 2.0 compressed MusicXML file? I would like to make sure I can parse them correctly. 

The 3.0 docs mention there was no META-INF folder until 3.0, but seems to lack details on 2.0 compressed files.

**Comment by mdgood** [comment]
@dbolton Aside from version numbering, nothing has changed in the layout of compressed MusicXML files from version 2.0 through version 3.1. The META-INF folder has always been there, and the META-INF/container.xml file has always been the starting point for reading a compressed MusicXML file.

Could you please point me to the documentation that led you to believe that things have changed in version 3.0? It would be great to remove any confusion in the documentation for MusicXML 3.2.

**Comment by dbolton** [comment]
@mdgood Thank you for the reply. Good to know. 

Rereading http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#TutMusicXML9-1.htm%3FTocPath%3DMusicXML%25203.0%2520Tutorial%7C_____10 I'm not sure why I came to that conclusion, but remember trying to verify that conclusion and coming up short: 
 1. I couldn't find 2.0's documentation (for example, the index.html file just says, "This is a placeholder for now. The latest version of the specification will be uploaded to the repository within a few weeks." https://github.com/w3c/musicxml/releases/tag/v2.0 )
 2. The versions of Finale have offer to save 2.0 uncompressed files, but don't offer to save 2.0 compressed (I understand this simplicity is good for users). 

However, your answer clarifies. I appreciate your work on MusicXML. It is an enormous benefit for users of music notation software.

**Comment by mdgood** [comment]
@dbolton Current versions of Finale let you export any valid combination of MusicXML version and compressed / uncompressed file. Hopefully that will avoid confusion in the future.

If there are not any specific documentation tasks to do to clarify this, I will plan to close this issue in a few more days.
