### ISSUE TITLE
Notation classical guitar extension

### ISSUE THREAD

**Issue by GualtieroChiapello** [w3c/musicxml#300]
[notation.pdf](https://github.com/w3c/musicxml/files/4129005/notation.pdf)

In the final page of the score "Pictures at an Exhibition" (Mussorgsky - Mar.1981) of the arrangement by the classical guitar master Kazuhito Yamashita there are elements of notation with their meaning: strangely they have not yet been considered.

Please see the attached file.

**Comment by mdgood** [comment]
@GualtieroChiapello Thank you for this suggestion. I apologize for the delay in responding.

I believe that most, if not all, of these elements can already be represented in MusicXML. Some have their own elements. Others may need to make use of the smufl attribute to specify the SMuFL symbol associated with a notation not directly represented in MusicXML 3.1.

Are there specific notations that you believe cannot be represented in MusicXML 3.1? Or notations that may currently require a smufl attribute that you believe should be promoted to its own element?

**Comment by mdgood** [comment]
@GualtieroChiapello I am closing this issue as I believe these notations can be represented in MusicXML 3.1. If there are specific notations that you believe are not covered by 3.1, please open a separate issue for those.
