### ISSUE TITLE
Unable to simultaneously render Chord Symbols and Functions for Notating Modulations

### ISSUE THREAD

**Issue by kianwilcox** [w3c/musicxml#301]
I'm trying to render functional harmonic analyses to MusicXML, and I need to, in a vertically-aligned fashion above the staff, list the following: Chord Symbol, Functional Interpretation in Originating Key, and optionally Functional Interpretation in Destination Key. Is this something that is currently possible with the <harmony> element? If not, is it possible to (in an easy way) abuse the lyrics element to accomplish this?

Examples:

If C is my originating Key and G is my Destination Key I'd like to be able to render it as follows, with each column below appearing above a chord in the sheet music:
     &nbsp;&nbsp;&nbsp;&nbsp;C  F G e a  D G
C:  I  IV V iii  vi
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;G: I  vi  ii  V  I

Is this currently feasible, and if not, is there any plan to support this in the future?

**Comment by mdgood** [comment]
@kianwilcox I think the best way to do this in MusicXML 3.1 is with three separate `<harmony>` elements, with the different vertical positions represented with the default-y attribute. Would this work for your needs?

**Comment by mdgood** [comment]
@kianwilcox Since I believe this can be done with current MusicXML 3.1 features, I am closing this issue. Please re-open if you believe there is something missing from 3.1 that should be addressed in a future version.
