### ISSUE TITLE
Represent piano pedal lines without a "pedal up" at the end

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#302]
Sometimes piano pedal lines do not explicitly stop. They may introduce a pattern and the line will be discontinued without a pedal up marking at the end. Often this may be followed by an indication such as "simile".

![Pedal simile](https://user-images.githubusercontent.com/11082681/77970758-d5c54d80-72a1-11ea-83c7-84b63dc82fd0.png)

There is no standard way to accurately represent this notation in MusicXML 3.1.

One way to encode this would be to add a "discontinue" value to the type attribute for the `<pedal>` element. Like the "change" and "continue" values, this would only be used when the line attribute is "yes". This would reuse the terminology from the `<ending>` element type for a similar graphical situation. 

Other suggestions for representing this type of notation are welcome!

**Comment by PianoBench** [comment]
This is an important issue and this solution is a good one.
