### ISSUE TITLE
Support percussion staves with widely spaced lines

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#305]
Percussion staves with either 2 or 3 lines are commonly spaced more than one staff line apart. For instance, 2-line staves can use lines 2 and 4 of a 5-line staff, while 3-line staves can use lines 1, 3, and 5. In both cases, the distance between staff lines is twice as big as for a normal 5-line staff. 

This also allows parts to specify different display pitches for a note hanging on top of a staff line vs a note hanging below the staff line above it. Kurt Stone's _Music Notation in the 20th Century_ shows two examples of this on page 223 for gradual changes in drum head pitch or from one striking location to another. Elaine Gould also shows an example on page 285 of _Behind Bars_, though in this case it is as a counter-example to recommended practice.

These widely spaced staves cause two problems in MusicXML 3.1:

1) MusicXML 3.1 can indicate the double-wide spacing with a `<staff-size>` element set to 200. However there is no indication if the `<staff-size>` also corresponds to a scaling effect for all the notation elements on the staff. This can lead to unreliable transfer of widely spaced percussion staves between applications.

2) There is no way in MusicXML 3.1 to distinguish between a note hanging above a staff line and a note hanging below the staff line immediately above. In a 2-line staff in percussion notation, both of those staff locations would lead to an unpitched value of F4 - the pitch midway between the first and second lines of the clef.

Supporting staves with widely spaced lines would allow more accurate transfer of percussion music between applications. The first problem could be addressed by adding an attribute to the `<staff-size>` element. The second problem could be addressed by allowing hidden lines on a staff, most likely someplace else within the `<staff-details>` element.

**Comment by mscuthbert** [comment]
I think that we might need within the `<staff-details>` a `<line-details>` complex type which can be used instead of the simple `<staff-lines>` tag as a CHOICE option.   If `<line-details>` is defined then all lines present must be defined.  The basic principle for interoperability with other musicxml assumptions is that a staff line is something that defines that a note can go on it or on the space above it.  A simple use of a five line staff with only the outer and middle lines (E, B, F in treble) showing, but occasionally notes on the second-line (G) that get ledger lines would be:

```
<staff-details>
    <line-details>
          <line>
                <number>2</number> <!-- 2 lines above center -->
                <staff-line-type>solid</staff-line-type> <!-- staff-line-type: solid, dashed, ledger, none -->
          </line>
          <line>
                <number>1</number> 
                <staff-line-type>none</staff-line-type> <!-- notes that appear here are as if on a space -->
          </line>
          <line>
                <number>0</number> <!-- center -->
                <staff-line-type>solid</staff-line-type>
          </line>
          <line>
                <number>-1</number>
                <staff-line-type>ledger</staff-line-type>  <!-- notes that appear here are like ledger lines -->
          </line>
          <line>
                <number>-2</number>
                <staff-line-type>solid</staff-line-type>
          </line>
    </line-details>
</staff-details>
```
This method would allow for all of Gould's (a-d) as well as Stone's example.

We could also say that any number in -2, -1, 0, 1, 2 not mentioned is assumed to be solid, and any number < -2 or > 2 is assumed to be absent, making it simpler:

```
<staff-details>
    <line-details>
          <line>
                <number>1</number> 
                <staff-line-type>none</staff-line-type>
          </line>
          <line>
                <number>-1</number>
                <staff-line-type>ledger</staff-line-type>
          </line>
    </line-details>
</staff-details>
```
For some pedagogical purposes AND for transcriptions of chant, `line-color` and `line-width` would also be good to support.

We could also imagine that lines could specify their distance (in tenths) from their normal position.  For instance, while Gould's "acceptable layout (b)" could either be done as a ten-line staff with two hidden lines as above, perhaps we want to call it an 8 line staff with some lines much closer to each other than others:

```
<staff-details>
    <line-details>
          <line>
                <number>3</number>
                <line-position>10</line-position>
                <staff-line-type>solid</staff-line-type> <!-- needed because would not otherwise be a line 3 -->
          </line>
          <line>
                <number>2</number>
                <line-position>10</line-position>
          </line>
          <line>
                <number>1</number>
                <line-position>10</line-position>
          </line>
          <!-- lines 0 and -1 are in their normal positions -->
          <line>
                <number>-2</number>
                <line-position>-10</line-position>
          </line>
          <line>
                <number>-3</number>
                <line-position>-10</line-position>
                <staff-line-type>solid</staff-line-type> <!-- needed because would not otherwise be a line -3 -->
          </line>
          <line>
                <number>-4</number>
                <line-position>-10</line-position>
                <staff-line-type>solid</staff-line-type> <!-- needed because would not otherwise be a line -4 -->
          </line>
    </line-details>
</staff-details>
```
However, I think that such details are unlikely to be honored by most rendering systems (adjusting beam position for changed staff-line separation?) and while I would advocate for supporting it, probably using the 10-line system with omitted lines is a better approach.

**Comment by mscuthbert** [comment]
I don't think that we should distinguish between notes hanging below a staff line and notes above the next staff line down.  If people want the appearance of that, they should use a hidden staff line below it, perhaps with `<line-position>` tags placing that staff line closer to or farther from the previous one than normal.

**Comment by jsawruk** [comment]
@mscuthbert I read your (very thorough) proposal for `<line-details>` and I like it. I think it covers a wide range of use cases, and I fully support it, even if current renderers/notation software doesn't. (Could SMuFL help here?)

My concern with the 10-line system is that it limits future flexibility. We could adopt it, but then I would still advocate your more flexible approach, which would require a way to translate between the representation.

If this becomes out of scope for MusicXML, we should certainly consider this for MNX.

**Comment by mdgood** [comment]
Thanks for this proposal @mscuthbert and for your review @jsawruk! I like the ideas, but want to tweak them to be closer to other MusicXML features such as the `<staff-tuning>` element. The changes I would propose are:

1) Have `<line-details>` come after a `<staff-lines>` element, so that one cannot have `<line-details>` without first specifying `<staff-lines>`. That way we only need to specify the lines that are not the default (hidden lines, different styles and colors, etc.). Or perhaps we don't need a `<line-details>` container element - we can just have a sequence of `<line-detail>` or `<staff-line>` elements, similar to the `<staff-tuning>` elements.

2) Let's refer to lines in the standard MusicXML way where 1 is the bottom line and the content of `<staff-lines>` is the top line. The difference here is that some lines may be hidden, so the number of staff lines visible on the page may not match the content of the `<staff-lines>` element. This is not ideal, but I don't know how else to add this in a way that is compatible with earlier MusicXML versions.

3) To keep the parallel with the `<staff-tuning>` element, use a required `line` attribute rather than the `<number>` element. To avoid confusion with the element name, we could use `<line-detail>` or `<staff-line>` as suggested above.

4) I would like to reuse as many standard attributes as possible for use with the element for each individual line. We could use `print-object` to indicate hidden lines,  and `color` and `line-type` for the different graphical display. We don't have a standard attribute for line width, but we could add a `width` element specified in tenths.

Since the Gould example can be done with hidden lines, and hidden lines are needed for the Stone examples, I would like to keep to having just one way to represent these. Thus I am not inclined to add variable width between staff lines unless there is some repertoire that cannot be represented accurately without it.

For the first issue of widely spaced staves, I think we can use a simpler approach of adding an attribute to the `<staff-size>` element to indicate whether or not the staff should be scaled in accordance with the `<staff-size>`, or if it just the distance between lines that changes. Perhaps we could call that `scaling` with values of yes or no. This would let us avoid having to use hidden lines for a more common case in percussion notation.

Does this sound like it would meet our needs? 

It would be great to see examples where color and width would be useful. I know I have seen them in the past but it would be great to have references to them here. Thanks!

**Comment by mscuthbert** [comment]
#1 sounds totally great.
#3 no problem with it -- my preference is generally attributes for simple elements anyhow.
#4 of course.  

Will get back with some colored line examples and line width besides the many uses in the Read Proposed Music Notation Reforms.  A lot of chant examples have used colored F and C lines.  And after using Vexflow, my preference is definitely for all five lines to be a medium gray instead of black (not sure if that's already possible with other means).

For #2 about numbering lines -- agreed that we can use 1-X instead of -X/2 - 0 - X/2  but  I'd like to talk a little more about #351 before completely committing to a numbering where the first line that is present is called 1, no matter where it is.  If we do that then there will need to be a way to specify which "normal" line the first line represents in, say, a one or two-line staff.

**Comment by mdgood** [comment]
Now that we have discussed #351 more thoroughly, does the current proposal still sound good? Allowing hidden staff lines seems to handle much of @mscuthbert's concerns, along with 1) specifying that the `<line>` element in a clef definition only applies to pitched staves, and 2) specifying that `<pitch>` elements should not appear when percussion clef is used. Thanks!

**Comment by mscuthbert** [comment]
I think that this is the best approach that does not invoke any past incompatibilities. I'm not liking that the common-case of a one-line mid-line staff with a pitched clef is modeled by stafflines = 5 with lines 1, 2, 4, and 5 being hidden, but at least it would work.

**Comment by mdgood** [comment]
For the first problem in the original issue, I am thinking of adding a `scaling` attribute to the `<staff-size>` element that is specified if the scaling of notation on the staff is different than what is specified in the `<staff-size>`. The documentation for the `<staff-size>` element indicates that scaling was intended, but that does not handle the situation for widely spaced percussion staves or some tablature styles.

Does this sound good? Are there better names to use instead of `scaling`? It duplicates an element name, but other names like `scale` didn't seem quite as readable.

**Comment by mdgood** [comment]
We might actually need to always specify the `scaling` attribute, even if it is the same as the `<staff-size>` contents. Otherwise MusicXML importers would need to handle 4.0 files differently than 3.1 and earlier files, and it seems likely that exporting applications might omit the scaling even when it should be different.

**Comment by mdgood** [comment]
Pull request #392 should fix both this issue and #351 along the lines that we have discussed. I cleaned up a related schema bug and documentation error along the way. 

@mscuthbert, if you have a chance to review this that would be much appreciated. As you mentioned above, it's not ideal, but I think it's the best we can do while staying compatible with previous MusicXML versions and software.

**Comment by Lr-2002** [comment]
Hi , I'm new here with urgnet demand to change the music note ,may i ask about whether is musicxml support to change the color of it? Or not ,may i try to write it from the coding??

**Comment by mdgood** [comment]
@Lr-2002 Yes, MusicXML lets you represent the color of notes and most other notations using the color attribute. The values can be either RGB or ARGB. For instance, `<note color="#800080">` would be a purple note, while `<note color="#40800080">` would be a transparent purple note.
