### ISSUE TITLE
Specify different styles of guitar bend notation

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#306]
Guitar bend notation is commonly represented in one of two graphical styles:

- Angled lines between noteheads
- A curved line with an arrowhead, usually with one of the noteheads hidden. In this style a pre-bend uses a straight line with an arrowhead.

Tablature staves generally use the curved line form, but standard notation can use either form.

MusicXML 3.1 does not provide a way to specify which form is being used. This can lead to inaccuracies in transferring bends between applications. This could be supported by adding an attribute or child element to the `<bend>` element. Since this is specifying graphical appearance, the attribute may be more appropriate.

**Comment by mdgood** [comment]
We could do this by adding a shape attribute to the `<bend>` element that takes the values "angled" or "curved". There doesn't seem to be any particularly standard terminology to distinguish these two graphical styles, so some type of descriptive naming seems like our best choice.

**Comment by jsawruk** [comment]
That terminology seems fine to me. I tried to think of other possibilities, but I think "angled" and "curved" are unambiguous.
