### ISSUE TITLE
Clarification of ties in middle of tie chain

### ISSUE THREAD

**Issue by joshwd36** [w3c/musicxml#309]
From what I can see of the schema, the `tied` element has type start-stop-continue, which to me would imply that a note in the middle of a tie chain would have the following to define its ties:
`<notations>
 <tied type="continue"/>
</notations>`
However, from what I've seen from software exporting MusicXML the following is used instead:
`<notations>
<tied type="stop"/>
<tied type="start"/>
</notations>`

Could I get some clarification on what the correct behaviour should be here?

**Comment by mdgood** [comment]
I think you may be looking at an older version of the MusicXML schema. Alas, the MusicXML 3.0 documentation on the musicxml.com site is out of date. It would be great if we could figure out how to update that and bring it over to the W3C site for MusicXML 3.2.

The MusicXML 3.1 schema gives the`<tied>` element a type of tied-type, which has values of start, stop, continue, and let-ring. As that type documents, "In start-stop cases, ties can add more elements using a continue type. This is typically used to specify the formatting of cross-system ties."

So as you see in other software, a note that is both tied into and tied out of will have two tied elements. The first will have a type of "stop" and the second will have a type of "start".
