### ISSUE TITLE
Specify measure numbering style for multiple rests

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#310]
Parts with a `<multiple-rest>` element that display measure numbering have several different options for displaying measure numbers on the multiple rest:

- Do not display any measure numbers
- Display the first measure number
- Display the first and last measure numbers as a range

MusicXML 3.1 currently does not provide a standard way to specify how this formatting is being done. 

This could be done by adding a "multiple-rest" attribute to the `<measure-numbering>` element with possible values of none, first, or range. Alternative approach would be to add something to the `<appearance>` element or the `<multiple-rest>` element.

**Comment by mscuthbert** [comment]
All good ideas.  My vote would be to put a numbering element on the `<multiple-rest>` element and not a multiple-rest attribute to `<measure-numbering>` just on a hunch that more almost every consumer that supports complex `multiple-rest` will support `measure-numbering` but not vice-versa.

**Comment by mdgood** [comment]
@mscuthbert Thanks for the feedback. Thinking about this some more, the `<measure-numbering>` element still seems like  a better fit. 

Usually measure numbering for multiple rests stays consistent though a part. The `<measure-numbering>` element already effects the rest of the part that follows on after the element. The `<multiple-rest>` element on the other hand only applies to the particular rest. Putting it there feels too atomic, while specifying it in the `<appearance>` element feels too general.

Specifying this within the `<measure-numbering>` element lets us encode this formatting once per part for the common case, while still allowing changes within a part when necessary.

**Comment by mdgood** [comment]
However, it seems there should be two different boolean attributes to cover two different aspects of measure numbers on multiple rests when the `<measure-numbering>` value is something other than `none`:

- A `multiple-rest-always` attribute to indicate that a measure number should always be displayed at the start of a multiple rest. This only changes things for multiple rests that start mid-system when`<measure-numbering>system</measure-numbering>` is used.
- A `multiple-rest-range` attribute to indicate that the multiple rest measure numbers should be displayed as a range rather than a single number.
