### ISSUE TITLE
Is rehearsal element for all section names?

### ISSUE THREAD

**Issue by benspratling4** [w3c/musicxml#311]
I have a technical question about MusicXML <direction-type><rehearsal>.    Finale is exporting all section names, like “Verse” or “Bridge” as these <direction-type><rehearsal> elements, while Sibelius only sends letters or numbers, such as “A” or measure numbers, like “29”, and sends section names as mere text.    My app only obtains content by importing MusicXML files, and it has a very strong need to know section names if the user has explicitly specified them, in fact the ability to specify section names with the <direction-type><rehearsal> was one of the key reasons I picked MusicXML.  Differentiating the section name text from other kind of text is a mere guess.    Which is the correct use of the rehearsal element?   If it is merely letters like "A", can we add a feature for marking user-specified section names which are names instead of merely letters?

**Comment by mdgood** [comment]
@benspratling4  This is a great question. I can see where the confusion comes in as the MusicXML schema and DTD are silent on this topic. All it mentions is that `<rehearsal>` refers to a rehearsal mark and has a square enclosure by default, while `<words>` has no enclosure by default. The DTD is also missing some of the documentation present in the XSD.

We could clarify the documentation to indicate the rehearsal marks in the `<rehearsal>` element include letters, numbers, and section names that are notated in the score for reference during rehearsal.

**Comment by mdgood** [comment]
I have updated the issue name and created a pull request to address this. @benspratling4, could you please review and let us know if this looks good to you? Thanks again for raising this issue.
