### ISSUE TITLE
Question about non-traditional keys.

### ISSUE THREAD

**Issue by p-groarke** [w3c/musicxml#312]
Can non-traditional keys be used to represent traditional keys?

For example, is representing C Major using non-traditional elements (an empty `key` element) valid? 

thx

**Comment by webern** [comment]
For some context, this discussion https://github.com/webern/mx/issues/89, my C++ library's 'api' currently makes it impossible to create an empty `<key/>` element and we're wondering if that's a valid construct (in practice more so than in theory). Looking at the xsd, I think that would be valid MusicXML as the `key` element would be a `non-traditional-key` group with zero members.

**Comment by mdgood** [comment]
An empty `<key/>` element is not valid MusicXML. You either need at least a `<fifths>` element or a single `<key-step>` / `<key-alter>` pair.

The standard way to represent keyless music is with:

```
<key>
  <fifths>0</fifths>
  <mode>none</mode>
</key>
```

**Comment by p-groarke** [comment]
Thank you for clarifying 👍
