### ISSUE TITLE
transposing musicxml

### ISSUE THREAD

**Issue by AlbertHart** [w3c/musicxml#317]
I am working on a function and web page to load a musicxml score , transpose it to a different key and then use it or save it.

Does anyone have a use for this or an interest in this?

**Comment by mdgood** [comment]
Thanks for letting us know Albert. It looks like this is part of OpenSheetMusicDisplay? If so we already have that listed on our MusicXML software page at https://www.musicxml.com/software/. If I am misunderstanding and this is something that should be listed separately, please let me know.

This might be something best discussed on the Music Notation Community Group mailing list. It does not seemed directly related to an issue in the MusicXML spec, so I will be closing this. Please re-open if I am misunderstanding something about this request.

**Comment by AlbertHart** [comment]
OSMD never replied or gave us permission to add it.

We have placed Transposition code and several more MusicXML manipulation routines  in a new open source GitHub project

https://github.com/AlbertHart/music

 and also made it available on a deployment MusicXML processing site where anyone can use it to manipulate MusicXML files.

![image](https://user-images.githubusercontent.com/8965352/88469000-eaf56600-cea8-11ea-9cb8-ba07a91a94a8.png)


http://adjustmymusic.com/

We would love to have the **Adjust My Music** site listed on your /software page.
