### ISSUE TITLE
Expand the allowable SMuFL accidental glyph names

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#330]
In the MusicXML 3.1 schema, the names of SMuFL glyphs that can be used in the `smufl` attribute of the `<accidental>` element are restricted to those starting with "acc". This is defined in the smufl-accidental-glyph-name simple type.

This covers most of the SMuFL accidental glyphs, but not those in the Medieval and Renaissance Accidentals and Kievan Square Notation ranges. Those ranges have accidental glyph names that begin with "medRenFlat", "medRenNatural", "medRenSharp", and "kievanAccidental".

Allowing these glyph names for accidental SMuFL glyphs would address a gap in MusicXML's handling of accidentals in early music.

**Comment by mdgood** [comment]
Pull request #332 addresses this issue.

**Comment by mdgood** [comment]
Could @mscuthbert, @dspreadbury, or someone else please confirm that this covers all the early music accidentals from SMuFL 1.3 that we were missing in MusicXML 3.1? Are there any other SMuFL accidentals with glyph names that start with a different set of characters?

**Comment by dspreadbury** [comment]
Yes, this list looks good to me.
