### ISSUE TITLE
Consider adding support for placement of figured bass

### ISSUE THREAD

**Issue by meastwoods** [w3c/musicxml#336]
Some publishers prefer figured bass to be above the stave rather than below. This typically happens in the full score rather than the parts, to keep the figures within the bounds of the system rather than taking up more room. (This could arguably make the distinction in MusicXML less useful, given that everything is fundamentally a part.)

Here's one such example:
![NBA](https://user-images.githubusercontent.com/71489658/93571938-0c486f00-f98d-11ea-8f54-df1720cc6847.jpg)

This comes from Neue Bach Ausgabe. Another example is Albrechtsberger, who almost always puts his figures above the stave, saying they usually go above the note, "except where room is wanting".

**Comment by mscuthbert** [comment]
This is also common in the Boulanger/Vidal figured bass tradition, so +1

**Comment by mdgood** [comment]
Pull request #343 addresses this issue.

**Comment by mdgood** [comment]
If either @meastwoods or @mscuthbert have a chance to review #343 that would be great - thanks!
