### ISSUE TITLE
measure composition

### ISSUE THREAD

**Issue by jnunley13** [w3c/musicxml#338]
Hello,

I'm trying to hide the first note of measure1.

I set the print-object to "no" and it shrunk the size of the measure by half.
How to hide the first note without changing the measure's original size/width?

Something special about counter position 0.

**Comment by mdgood** [comment]
In MusicXML you use `<note print-object="no" print-spacing="yes">` to hide the note but keep the spacing associated with it as if it were displayed. However, print-spacing is supposed to be treated as "yes" if not present. I imagine this is a restriction of the software - what software are you using to display the MusicXML?

**Comment by jnunley13** [comment]
Thanks for the reply. 
I'm using musicxml2ly & lilypond.
The print-object print-spacing combination doesn't preserve the measures original size.  

Only when I hide the first note does the measure change.
If I print the first note, I can hide the subsequent notes without altering the measures size.

The presence of a printed element in position 0 preserves the property and size of the original measure.

Printing an invisible note at the beginning of the measure would fix it.  How do you print a blank object?

**Comment by mdgood** [comment]
My understanding is that LilyPond ignores most if not all MusicXML formatting and applies its own. I think these are questions for the LilyPond team rather than here, so I will be closing this issue.
