### ISSUE TITLE
javascript client side validator for musicxml files?

### ISSUE THREAD

**Issue by happypennygames** [w3c/musicxml#342]
Hi,

Would you mind commenting on if/how validation of a musicxml file is possible with javascript?
Use case:  loading musicxml files from untrusted sources aka "users".  Thus, both security concerns and general formatting for actually working properly are needed as checks.  The validation must also be self contained ie. client side, offline.

Saw a few issues on musicxml validation, but nothing directly to this point- could not even find a reasonable general solution on google either for some reason.

**Comment by adrianholovaty** [comment]
This is definitely possible, yes. There are at least three levels of validation you'd need to consider:

* XML syntax/DTD validation (are the correct tags/attributes used, in the correct nesting, and is it a valid XML file in the first place?)
* Music-specific validation (does the MusicXML document do things that use valid syntax but are meaningless in practice?)
* App-specific validation (does the MusicXML document do things that aren't supported by your specific notation rendering engine/app?)

It sounds like you might be looking for an off-the-shelf solution? This isn't really the place for that — this GitHub project is about maintaining the MusicXML specification itself.

**Comment by webern** [comment]
> This isn't really the place for that

Perhaps not, but this link might be helpful: https://www.musicxml.com/software/
Searching for Javascript turned up a hit that might be relevant to the OP.

**Comment by happypennygames** [comment]
@adrianholovaty thanks- I'm 100% with you conceptually.  It's writing the block of js string parsing that would do all that.  I didn't want to reinvent a whole system if you had or knew of a system that worked great with musicxml.  I had seen a few issues in this repo about moves towards facilitating validation, so I thought there might be specific code pointers available- even if not handled by this repo, perhaps "go here and use their code but with this scheme file from us".

@webern thanks as well- it's a good pointer to opensheetmusic display.  Unfortunately, from browsing their repo, looks like they punted on this: https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/Common/FileIO/Mxl.ts  Seemed to be the most promising location, but nothing struck me as validation.

If either of you have any further pointers, happy to take them, otherwise, feel free to close the issue and start coding this up I guess.

**Comment by happypennygames** [comment]
See https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/908 for latest.
