### ISSUE TITLE
Clarify what staffLines != 5 means

### ISSUE THREAD

**Issue by mscuthbert** [w3c/musicxml#351]
A documentation/standardization task:

Currently if in `<staff-details>` `<staff-lines>1</staff-lines>` MusicXML consumers are interpreting differently which of the lines is to be shown.  Finale takes what I believe to be the most logical approach, showing the middle line only.  MuseScore is showing the top line only.  I doesn't really matter which is being shown, but users who want to show a melody around a single line (e.g., Sprechstimme a la later Schoenberg) need a way of knowing which line will be shown.

Proposed documentation:

Stafflines are shown in the order of middle-line of a five-line staff and add lines alternating with the next line above this line and the next line below.  So `<staff-lines>2</staff-lines>` would show in treble clef D5 and B4.  `<staff-lines>4</staff-lines>` would show in bass clef A3, F3, D3, B2.  If staffLines is greater than 5, then positions which would normally be ledger lines are replaced with staff lines, alternating above the normal staff and below as before.  Ledger lines (with their added thickness) should not be shown for notes on such lines.

_(edited to use proper MusicXML terms)_

**Comment by mscuthbert** [comment]
(I will leave to a separate enhancement issue a way of hiding individual staff lines, etc.)

**Comment by mdgood** [comment]
Issue #305 deals with percussion staff spacing and the solution is likely to involve hiding individual staff lines. It seems it would be good to address this issue around the same time.

@mscuthbert, would A Survivor from Warsaw be an example of the later Schoenberg you have in mind? It has a single line staff with a clef symbol in the part name that suggests the line should be pitched around F.

In this case I am wondering if the solution for hiding staff lines might work here too. Alternatively, perhaps we could have the `<staff-tuning>` element apply to this situation.

I'm not so sure that the documentation approach by itself really solves the issue for this piece, since it's the equivalent of the 4th line that's being shown.

Please let me know if I am misunderstanding something or if there is another example that might show this better. Perhaps we may want to re-title the issue to focus on the representation issue of needing to know the pitch associated with a single line.

**Comment by mscuthbert** [comment]
The narrator staff in Survivor from Warsaw is indeed the main piece I had in mind.  Hiding staff lines would work here if it was accompanied by an F3 (not F4) clef:

![Screen Shot 2020-12-01 at 13 04 00](https://user-images.githubusercontent.com/3521479/100807081-c587e400-33d5-11eb-9113-cf03816769f1.png)
![Screen Shot 2020-12-01 at 13 04 21](https://user-images.githubusercontent.com/3521479/100807087-c7ea3e00-33d5-11eb-9978-87d30ecd5af6.png)

In general, the clef used with single-line staves is either percussion clef or no clef, so it is much less often a problem.  However, for #305 and other uses, a more specific format would need to be made -- I suggest for that, having a more specific `<line-detail>` that overrides `staffLines=X` (if both are present) would need to exist.  I'll put the suggestion in 305.

**Comment by mdgood** [comment]
I sang in the chorus of A Survivor from Warsaw a few years ago, but this is the first time I've looked at the full score. Thanks for raising this issue!

**Comment by jsawruk** [comment]
I think adding visual examples to the documentation would help clarify this as well.

**Comment by mdgood** [comment]
Thinking about this some more, I don't think we actually need to add anything to MusicXML to handle this situation. It could be represented with a hidden F clef on line 1 of a 1-line staff:

```
<attributes>
  <clef print-object="no">
    <sign>F</sign>
    <line>1</line>
  </clef>
  <staff-details>
    <staff-lines>1</staff-lines>
  </staff-details>
</attributes>
```

The issue would seem to be more in software support for either exporting or importing this type of notation, since most applications probably don't have this piece in their test suite (yet).

**Comment by mscuthbert** [comment]
This would be a place to emphasize in the docs that according to the current spec, line 1 refers to the first of the displayed staff lines.  I would have thought it referred to line in a "normal" 5-line placement.  I'll look at what two current leaders (Finale and MuseScore) are doing and what might change.

----
How does the interpretation of the current spec's Clef-Lines align with the "display-step" with percussion clefs and one-line staves?  It means as we see in https://www.musicxml.com/tutorial/percussion/staff-lines/ (though better also mentioned in the docs for `<unpitched>` as well, that it is:
```
<unpitched>
    <display-step>E</display-step>
    <display-octave>4</display-octave>
</unpitched>
```
Is this how it's working in practice?  I'll also look at the unsupported--but very commonly used --case of pitched notes with a percussion clef.

Here are four minimal musicxml files using 1-line staves showing how they're currently rendering in Finale and MuseScore.  Images are always Finale first then MuseScore

1. Percussion Clef, unpitched display as E4:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
  <part-list>
    <score-part id="P1">
      <part-name>Part</part-name>
    </score-part>
  </part-list>
  <part id="P1">
    <measure number="1">
      <attributes>
        <divisions>2</divisions>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
        </time>
        <clef>
          <sign>percussion</sign>
        </clef>
        <staff-details>
          <staff-lines>1</staff-lines>
        </staff-details>
      </attributes>
      <note>
        <unpitched>
           <display-step>E</display-step>
           <display-octave>4</display-octave>
        </unpitched>
        <duration>8</duration>
        <voice>1</voice>
        <type>whole</type>
      </note>
    </measure>
  </part>
</score-partwise>
```
![Screen Shot 2020-12-04 at 08 57 00](https://user-images.githubusercontent.com/3521479/101203501-d96a5a80-360e-11eb-8f11-3e5eed128da8.png)
![Screen Shot 2020-12-04 at 08 57 12](https://user-images.githubusercontent.com/3521479/101203511-dcfde180-360e-11eb-852b-5aa340a3a251.png)

Here, Finale's behavior is correct according to spec as much as I can gather, and MuseScore's is a fifth too low.

(Changing to G4 moves the note up a third in both Finale and MuseScore, though Finale does not draw ledger lines; acceptable behavior I suppose)

But this makes percussion clef an anomaly from other clefs in that it supposes that its "line" interpretation depends on the "staff-lines" attribute.  It does not seem to be shifting up or down according to the number of staff-lines as other clefs are supposed to.


2. Percussion clef, Note is PITCHED as B4 (unsupported in MusicXML spec, but commonly found)
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
  <part-list>
    <score-part id="P1">
      <part-name>Part</part-name>
    </score-part>
  </part-list>
  <part id="P1">
    <measure number="1">
      <attributes>
        <divisions>2</divisions>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
        </time>
        <clef>
          <sign>percussion</sign>
        </clef>
        <staff-details>
          <staff-lines>1</staff-lines>
        </staff-details>
      </attributes>
      <note>
        <pitch>
          <step>B</step>
          <octave>4</octave>
        </pitch>
        <duration>8</duration>
        <voice>1</voice>
        <type>whole</type>
      </note>
    </measure>
  </part>
</score-partwise>
```
![Screen Shot 2020-12-04 at 09 02 16](https://user-images.githubusercontent.com/3521479/101203897-74fbcb00-360f-11eb-8c60-214139c1b1ee.png)
![Screen Shot 2020-12-04 at 09 02 28](https://user-images.githubusercontent.com/3521479/101203907-77f6bb80-360f-11eb-86ff-40f30bfce769.png)

The spec for percussion clef + pitched element is undefined.  If we suppose that it is the same as the `<unpitched>` element -- i.e., reading as if it's a Treble Clef (G-clef on line two), then Finale's behavior is incorrect according to spec and MuseScore's is also incorrect but consistent with (1) above.  To place a note on the single staff line it should again be encoded as E4.

This is, btw, the default Finale and MuseScore MusicXML output if using a one-line staff with percussion clef not set up as a percussion instrument through score editor, which is what would commonly be used for things like a Triangle on the line of a single staff if someone wasn't able to mess with percussion maps.  (Try to get an unpitched musicxml output in Finale of a single-line Triangle staff where the notes are on the line)

3a.  Now one-line staff in Treble Clef (G2), with a note Pitched as B4: (Supported by Spec)
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
  <part-list>
    <score-part id="P1">
      <part-name>Part</part-name>
    </score-part>
  </part-list>
  <part id="P1">
    <measure number="1">
      <attributes>
        <divisions>2</divisions>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
        </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
        </clef>
        <staff-details>
          <staff-lines>1</staff-lines>
        </staff-details>
      </attributes>
      <note>
        <pitch>
          <step>B</step>
          <octave>4</octave>
        </pitch>
        <duration>8</duration>
        <voice>1</voice>
        <type>whole</type>
      </note>
    </measure>
  </part>
</score-partwise>
``` 
![Screen Shot 2020-12-04 at 09 17 05](https://user-images.githubusercontent.com/3521479/101205367-99f13d80-3611-11eb-96c1-524be124e960.png)
![Screen Shot 2020-12-04 at 09 17 43](https://user-images.githubusercontent.com/3521479/101205379-9f4e8800-3611-11eb-9866-f89b86ec034a.png)

Finale's Clef is too low by 2 lines according to the spec, and the note is also too low by 2 lines according to the spec.  MuseScore's clef is correct according to the spec, but the note is too low by 4(!) lines according to the spec.


3b.  Same as 3a but with clef on G1 (should be with the curl directly on the line) not G2.  Both Finale and MuseScore move both the clef and the note down one space from their previous positions, but neither is correct:
![Screen Shot 2020-12-04 at 09 23 53](https://user-images.githubusercontent.com/3521479/101206177-d709ff80-3612-11eb-8753-d71c9e838fad.png)
![Screen Shot 2020-12-04 at 09 24 24](https://user-images.githubusercontent.com/3521479/101206187-dbceb380-3612-11eb-9d4e-220b7b642fff.png)

3c.  Same as 3a/b but with clef on G0 (should be with the curl below the line, as if a treble clef score only had its middle line drawn.  Both Finale and MuseScore ignore line=0 (specification is "xs:integer" not "xs:positiveInteger") and parse as if it's G2:
![Screen Shot 2020-12-04 at 09 29 40](https://user-images.githubusercontent.com/3521479/101206543-60b9cd00-3613-11eb-9d4a-9ab42176685e.png)
![Screen Shot 2020-12-04 at 09 29 06](https://user-images.githubusercontent.com/3521479/101206550-631c2700-3613-11eb-8110-4a345a42573f.png)

Finale's output here actually happens to be correct, but only because it's ignoring `line=0` and displaying as if it's `line=2`.  Putting `<line>-1</line>` (acceptable by spec) results in the same behavior as `<line>0</line>` in both consumers, which is to say, as if it's `<line>2</line>`.

-----
Neither of these two readers are conforming with the spec in at least one of (1) or (3) and Finale's is also "wrong" for the unsupported but common (2).  Neither of them is able to import a treble clef in the "normal" position for a one-line staff when encoded according to the spec.  I don't have access during Covid to Sibelius or Dorico and untested on Noteflight/Flat.io.  BUT if they also are non-conforming, then it may be possible to change the spec without breaking a conforming system.  And I think we should.

Why change the spec?  Consider this decently common usage of one-line staves within pitched music:

![Screen Shot 2020-12-04 at 09 35 31](https://user-images.githubusercontent.com/3521479/101207742-23563f00-3615-11eb-8be9-fa6b9268841a.png)

(this is commonly seen for, say, "clap hands/strike body of instrument" or "indeterminate pitch" or for exercises or for "improvise on this rhythm", etc.  or Stravinsky-style cut-away scores during rests.)

According to the spec, this passage would require not just two `<staff-lines>` changes but also two `<clef>` changes in order to keep the treble clef at the same position.  In fact in the current spec the **absence** of a `<clef>` tag in conjunction with a change in `<staff-lines>` connotes a change of clef position! Moreover, in the absence of a clef change the note's pitch would have to change from B4 to E4 in order to maintain the same staff position.  In order to know where to render a clef with respect to a part, the consumer would need to be aware of the current staff-lines (possibly in a multi-stave part).  

This seems sufficient reason to change the spec for interpreting `<clef><line/></clef>` and `<unpitched>...</unpitched>` for 4.0 in the context of `<staff-lines>!5</staff-lines>`  to something like:  "The clef `<line>` element is measured from the first-line of a five-line staff" and display-step for percussion clef to also assume that staff-lines=1 means that the B4 line is the line being shown.

There would need to be no changes to `<clef><sign>TAB</sign><line>5</line></clef>` within a six-line TAB staff, and the interpretation of "string" in TAB would not need to change (MNX would be the better place to renumber the tuning and `<technical>` string counting to be aligned).  I have not, however, searched extensively to other references to staff lines to be sure that

**Comment by mdgood** [comment]
@mscuthbert Thank you for this very thorough analysis!

I think some of what you are seeing in 1) and 2) in particular is due to Finale having buggy handling of percussion music entered as standard notation up until Finale 26.3. Finale 26.3 has fixed a great many things here. It no longer exports `<pitch>` instead of `<unpitched>` elements in some situations, and in others it fixes the `<unpitched>` export to match the spec. Corresponding changes were made for import.

Issue 3 is a limitation that Finale has with pitched clefs for any non-5-line staves. Until this thread I was unaware of the Schoenberg example in use with the 1-line staff.

In your 5-line to 1-line example, might you see clef changes more often than not? I'll check with what we see here. In any event this type of notation is still a problem point for Finale's MusicXML export, and likely would be regardless of any spec changes.

I think one thing we can clarify in the spec is that the `<line>` element only applies to pitched staves values so that one can determine what staff line is associated with what pitch. This is not needed for percussion, tab, jianpu, or none clefs. We can also clarify that music in percussion clef should not have `<pitch>` elements.

I don't think it is a good idea to be changing MusicXML's behavior for the line-related elements at this point, even though there are some issues with the current representation. However I am definitely interested in how we can tighten up and clarify the spec for these situations. The hidden line feature proposed in #305 interacts with this issue so I suspect we will want to address them together.

**Comment by mscuthbert** [comment]
Clef changes in switching to one-line staves are rare.  In Penderecki's Threnody, no clef changes are notated except if the instrument has never had a pitched clef defined previously:

![Screen Shot 2020-12-10 at 09 23 15](https://user-images.githubusercontent.com/3521479/101819489-6f97f800-3ac9-11eb-93ac-3f4121a8a078.png)

(also demonstrates the importance of a staff line-style=dashed for #305)

Earle Brown also does not notate a change of clefs:

![Screen Shot 2020-12-10 at 09 45 51](https://user-images.githubusercontent.com/3521479/101821794-8d1a9100-3acc-11eb-98ff-a6620d84d239.png)

Richard Beaudoin similar, note especially here how the unpitched object might be the right choice for encoding, but "percussion" clef definitely would not be:

![Screen Shot 2020-12-10 at 09 54 51](https://user-images.githubusercontent.com/3521479/101822683-cef80700-3acd-11eb-80a9-c512ab88cbf2.png)


Trevor Bača does not use a clef change with his frequent changes in number of staves (except changing from unpitched to pitched percussion = Feldman usage).  The idea is that the single-line staff already indicates a change in performing styles.

![Screen Shot 2020-12-10 at 09 29 13](https://user-images.githubusercontent.com/3521479/101820249-665b5b00-3aca-11eb-9394-77acedfae859.png)

George Crumb does not usually notate a change of clef at a change in staves:

![Screen Shot 2020-12-10 at 09 36 04](https://user-images.githubusercontent.com/3521479/101820894-4e380b80-3acb-11eb-96e8-538fdee14fe5.png)

...but if a system begins with a one-line staff, the clef is often omitted, and if after a long section on one-line staff (or no staff), the staff returns in a clef that is not the normal one for the instrument (as in the cello part in treble clef here), then that clef is sometimes given (Hespos is similar):

![Screen Shot 2020-12-10 at 09 39 17](https://user-images.githubusercontent.com/3521479/101821099-97885b00-3acb-11eb-9253-b47b7e54cc69.png)
 

Kate Soper's use of extensive notated clef changes is I believe unusual:

![Screen Shot 2020-12-10 at 09 24 51](https://user-images.githubusercontent.com/3521479/101819713-b980de00-3ac9-11eb-8ea1-08a7d5130ee3.png)

(Ferneyhough does not use a change of clefs in moving from 5 to 1 line, but does in the opposite direction)

I'll move up to Finale 26.3 (been having some trouble updating on my Mojave "desktop" [=laptop w/ bad battery] computer that I'm using more and more during Covid) and see what changes.

More later, but just adding data.

**Comment by mdgood** [comment]
Thanks for these examples @mscuthbert - this is very helpful. I had been thinking more in terms of percussion parts that switch from pitched to unpitched percussion instruments, where I think we do see clef changes more often.

If there are no pitches on a single line as in the Brown, or there are only unpitched notes on the single line as in the Beaudoin, then the clef line would not affect how the notes are displayed. An `<unpitched>` element without child elements is always place on the middle line of the staff. The clef line would matter if the clef needs to appear in the correct vertical position at the start of a system.

I am still thinking that these issues are probably better handled by allowing hidden staff lines, which I believe we will need for #305, than by changing how lines are defined in other contexts.
