### ISSUE TITLE
Consider adding `print-object` to metronome

### ISSUE THREAD

**Issue by mscuthbert** [w3c/musicxml#355]
The `<metronome>` tag represents an encoding of the tempo in beats (not quarter notes) per minute, but also can encode ambiguity (a tempo range or "ca.") and metrical relationships (prior quarter note equals new eighth note) etc.  In the future (see #50) there might be even more subtlety in what is encoded here.  Metronomes are always printed.

The `<tempo>` tag (part of the sound object) gives playback instructions in terms of quarter notes per minute, without any display/print implications.

The original design of MusicXML had a relationship between metronome and tempo like other display/sound pairs (tied/tie, etc.) that made having `<metronome print-object="no">...` not make sense.  If you don't want to print the metronome mark, don't encode it!  Just use a tempo tag  :-)  But as the metronome tag has gotten richer and richer, it can make sense to encode metronome information without necessarily wanting it to be displayed.  Thus I recommend adding `print-object` attribute (and anything else that might allow for, say, printing on parts only and not scores) to the metronome tag for v4.0.  

`<other-direction>` gives a precedent for having a tag that does not affect playback or computational interpretation of the score that also has a `print-object` tag.  My colleague Jacob Taylor Wells also notes that putting `print-object="no"` in a <metronome> tag on Finale causes a MusicXML validation error (as it should) but then causes the metronome mark to be grayed out for non-display.  So we can point to that as one consumer implementation of this proposal already in existence.  :-)

**Comment by mscuthbert** [comment]
References: 

Discussion at music21 github: https://github.com/cuthbertLab/music21/issues/684
Complex type metronome: https://usermanuals.musicxml.com/MusicXML/Content/CT-MusicXML-metronome.htm
Changes to metronome tag in 3.1 did not add print-object: https://www.w3.org/2017/12/musicxml31/

**Comment by mdgood** [comment]
@mscuthbert Thanks for this suggestion. I read through the music21 reference but I'm afraid I don't yet understand the use case. The specific issue here seems to have been addressed in MusicXML 4.0 by #37, and it seems the most important semantic gap has been addressed by #283. 

The argument that the metronome element contains semantics that one may want to encode but not see could theoretically apply to many direction-type child elements that do not currently have print-object attributes. It would be very helpful to hear a user story of situations where this capability would be helpful. Thanks!

**Comment by mscuthbert** [comment]
The main use cases are being able to specify an acceptable tempo range or an implied metric modulation for analysis without displaying.  A particular case is if the sound tag is being used to track with a particular recording, but there are lots of shifts between, say, 3/4 and 6/8 where different interpreters imply different metric modulations (8th = 8th, vs. quarter = dotted quarter.  These are important for the analysis of early music, where editors want clean scores w/o editorial interpretations but performers and analysts want to be able to grasp implied metrical patterns.

Indeed, I think that the first direction-type, accordion registration is a type of object that one might want to have attached to every chord but only printed on the first of each type (switching between beginner and advanced versions of a score), harp pedals are another one, where it can be analytically useful to understand every implied change of harp pedaling but only a few non-obvious ones would be printed.

Perhaps simpler would be to allow `print-object` as an attribute on the surrounding `<direction>` tag, since it fits well with the other two attributes present there (`placement` and `directive`)

**Comment by mdgood** [comment]
Adding a `print-object` attribute to the `<direction>` tag has a nice simplicity, but there are some potentially confusing interactions with some of the grandchild elements. What does this mean combined with an `<octave-shift>` element , for instance?

For now I think it might be best to just add this to the `<metronome>` element since there is a clear use case for analysis applications, and no confusing interactions to worry about.
