### ISSUE TITLE
Add new instrument sounds to sounds.xml list

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#363]
In addition to the whistle.tin.c instrument added in #289, there are other instrument sounds that could be added to the standard sounds.xml list. Requests that I have received so far include:

- Cavaquinho (e.g. pluck.cavaquinho)
- Handchimes (e.g. pitched-percussion.handchimes)
- Tabor (e.g. drum.tabor)
- Tamborim (e.g. drum.tamborim)

Do these seem like reasonable additions? Are there other instrument sounds that we could be adding?

**Comment by mscuthbert** [comment]
`wind.reed.clarinet.d` is a notable omission.
`wind.reed.clarinet.g` is common in Turkish music.

Some things that might be helpful for translation:

`wind.group` and `brass.group` exist, but maybe some more specific groups: `wind.group.woodwind-quintet`, `brass.group.brass-quintet`.  

And perhaps `wind.flutes.group.flute-choir` and same for clarinet choirs, etc. -- in some ways these can be taken care of with `wind.flutes.flute` + an `<ensemble>` tag, but when they might span multiple sounds (flute choir contains piccolo, flutes, alto/bass flutes, etc.) this might be a way of specifying a better sound.

One update: in sounds.dtd, change: "The sound element lists one of the standard sounds available in MusicXML 3.0" to "in MusicXML 4.0"

Putting a larger proposal in to a separate issue now.

**Comment by mscuthbert** [comment]
Also add generic `wind.reed.clarinet.piccolo` for high G, Bb, and C piccolo clarinets, and to fit the general trend of having a generic category for things with specifics.

**Comment by mdgood** [comment]
@mscuthbert Thanks for these suggestions. I agree with the clarinet additions and thanks for finding the old 3.0 reference.

I am curious about the use case for the new groups though. I understand the distinction, but when would these be used? The existing groups are mailing there for compatibility with existing patches like the Orchestra Hit and Brass Section in the General MIDI spec. I'm not sure how often these types of more general heterogeneous groups are used. I am no expert in virtual instrument libraries, so please correct me if I am mistaken!

The groups idea also sounds like something where we might want to wait to see how MIDI 2.0 Profiles work out before making partial additions. We have set things up so that the sounds.xml list can be updated independently of the rest of the MusicXML 4.0 specification, so we could have quicker turnaround if we want.

At this point I would be plan to fix the typo and add:

- drum.tabor
- drum.tamborim
- pitched-percussion.handchimes
- pluck.cavaquinho
- wind.reed.clarinet.d
- wind.reed.clarinet.g
- wind.reed.clarinet.piccolo
