### ISSUE TITLE
Update documentation to 3.1

### ISSUE THREAD

**Issue by rettinghaus** [w3c/musicxml#387]
Please update the official documentation on https://www.musicxml.com/ to reflect version 3.1.

**Comment by mdgood** [comment]
@rettinghaus We will be doing this in a somewhat different form as part of #353. The documentation will be for MusicXML 4.0 and will be hosted at the W3C site and GitHub pages as a Community Group report. At that time we will remove the old MusicXML 3.0 documentation at the www.musicxml.com site, redirecting to the new 4.0 documentation. We plan to use the same tools that @adrianholovaty is building for the MNX spec to create the MusicXML 4.0 spec.
