### ISSUE TITLE
Deprecate the DTDs

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#401]
When MusicXML was originally created in 2000, the only official language for specifying a schema was the Document Type Definition, or DTD. In 2008 we added a W3C XML Schema definition for MusicXML 2.0 to the DTDs.

Since then we have maintained both the DTD and the XSD versions for the MusicXML schemas. This seemed worth it due to the greater readability of the DTD files compared to the XSD files. It also provided compatibility for applications using DTD technology. However the cost was having to update two schemas instead of one whenever making a MusicXML update. 

Now that we have full documentation for the MusicXML format, the balance of benefit and cost seems to have changed. We would now have to update things in 3 places: the XSD, the DTD, and the documentation. While the cost increases, the benefit is reduced. The documentation is easier to read than either the DTD or the XSD, so that will be the main reference point for developers. XSD schema technology has been around a long time, so it should be straightforward for any applications still using DTDs to migrate over to XSDs. 

I think it is time for us to deprecate the DTDs as of MusicXML 4.0. A future release of MusicXML could then just update the XSD and the documentation. The documentation elements in the XSD could also be largely removed so that we are not duplicating documentation in two (much less three) places.

To remove the DTDs in the future we would need to create XSDs for the container and sounds formats. These are simple formats so that should be straightforward to do.

Deprecating the DTDs now does not commit us to removing them in the next release, but it makes removing them a possibility in the future.

**Comment by mdgood** [comment]
When this issue was mentioned in the co-chair meeting minutes, @DavidMWebber replied

> Is that necessary? I'd like to appeal for the DTDs to remain official and undeprecated. I've been happily using this method for many years, for import and export of MusicXML from my Mozart notation software - https://www.mozart.co.uk - and I really don't want to have to go and learn new tricks for the sake of it.

I agree we don't want to force developer changes just for the sake of it. I think the benefits in catching more errors through more precise MusicXML validation, and simplifying the MusicXML technology base for everyone, are worth the cost of switching technology at some point over the next few years. Deprecating doesn't mean the DTDs are going away now. But it gives us the option to drop them for a possible MusicXML 4.1 release.

**Comment by svenemtell** [comment]
Just for the record, this is our take on this...
We use the DTDs for validation in ScoreCloud (https://scorecloud.com) today. We think they are convenient and will continue to use them for as long as they are available. When they eventually are removed, we'll look for an XSD validation replacement.
Sven
Doremir Music Research

**Comment by jsawruk** [comment]
If the DTDs are being deprecated, then maybe the [Hello World](https://w3c.github.io/musicxml/tutorial/hello-world/) in the documentation should be updated to not use the DTD anymore.

**Comment by mdgood** [comment]
Given the current use of DTDs in the community, and some of the complexity involved with deprecating the DTDs while maintaining document compatibility, we have decided not to do this for MusicXML 4.0. We might want to do this in a future version of MusicXML, so I will leave this issue open.

Removing the duplicate documentation from the DTD and XSD files could address many of the issues regarding the extra work in maintaining the DTD. This is something we can address and discuss when developing a future version of MusicXML beyond 4.0.

**Comment by jsawruk** [comment]
I thought deprecate meant "this feature will be removed in the future" and not actual removal. I still think we should mark DTD support as deprecated and that users should transition to XSD starting in MusicXML 4.0.

**Comment by DavidMWebber** [comment]
>From: jsawruk ***@***.***> 
>… I still think we should mark DTD support as deprecated and that users should transition to XSD starting in MusicXML 4.0.

 

Why?    Some of us are very happy using the DTD.    It ain’t broke so why make us work to fix it?



Dave

 

David Webber
Mozart Music Software
https://www.mozart.co.uk

**Comment by mdgood** [comment]
@DavidMWebber, DTDs cause problems both for MusicXML customers and developers. So there are things broken that we can fix by deprecating DTD support.

For customers, the problem is that DTDs provide a looser definition of the MusicXML format than the XSDs. This means that errors that could be caught just by validation are let through, causing additional problems with interchange for people moving files between applications.

One of the main complaints about MusicXML is the differing level of support between applications. There is not a lot that the W3C Music Notation Community Group can do about this. Removing DTD support is one tool we do have available to make the MusicXML experience consistently better across applications.

For developers, the problem is that retaining DTD support will slow the development of future versions of the MusicXML format. We currently have to make edits in three places when anything changes: in the XSD, in the DTD, and in the document database. Ideally we would like to make the change just once, in the document database, and automatically generate the XSD from that. This was @adrianholovaty's original version when building the documentation tool for MNX. We believe it could be applied to MusicXML as well.

Automatically generating an XSD from the database should be relatively straightforward as XSDs are XML documents and can make use of Python's built in XML language support. DTDs are not XML documents are automatically generating them would be a substantially more difficult proposition.

It has been 20 years since XSDs became a W3C recommendation. In that time support for XSDs has become ubiquitous. I am sure that we can help you make the transition from using DTDs to XSDs.

Based on this, we have decided to bring this into scope for MusicXML 4.0.

**Comment by mdgood** [comment]
Reopening for review which seems easier with the live web site and documentation.

**Comment by mdgood** [comment]
The latest updates include new XSD versions of the sounds and container DTDs. The deprecation also applies to the midixml.dtd file and its corresponding midixml.xsl file.
