### ISSUE TITLE
Documentation: Clarify MusicXML version(s) under "File Suffixes and Media Types"

### ISSUE THREAD

**Issue by samuelbradshaw** [w3c/musicxml#416]
The "File Suffixes and Media Types" section of the "Compressed .MXL Files" page says:
> For Internet use, MusicXML 3.1 has registered media types available for both compressed .mxl and uncompressed .musicxml files.

Should the MusicXML version reference be changed to include newer versions?

For example:

> For Internet use, starting with MusicXML 3.1, registered media types are available for both compressed .mxl and uncompressed .musicxml files.

Relevant page:
https://w3c.github.io/musicxml/drafts/4.0-2021-05-25/tutorial/compressed-mxl-files/

**Comment by mdgood** [comment]
@samuelbradshaw Yes, we should fix this - thanks! The media types were registered a long time ago, before 3.1. I think just removing the version number should be fine, along with rewriting that sentence to be a little less awkward.

**Comment by mdgood** [comment]
Pull request #417 should fix this. @samuelbradshaw, would you have a chance to review this to see if it looks good? Reviewing the HTML file difference is probably easier than the JSON file which contains the same change. Thanks!
