### ISSUE TITLE
Clarify relationship between dynamics and direction placement attributes

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#43]
The dynamics element can be used as a child of either the notations element and the direction-type element. It has a placement attribute for its use within the notations element. MusicXML 3.0 is not clear on what happens if the dynamics placement attribute conflicts with the direction placement attribute when dynamics is used within a direction-type. This led to David Webber's question on the MusicXML forum:

> Does the "placement" of a "dynamics" element override the placement of its grand-parent "direction"?

No other direction-type child element has a placement attribute. It seems likely that the dynamics placement should only be used within the notations element, and be ignored when used within a direction-type. 

See the MusicXML forum discussion at http://forums.makemusic.com/viewtopic.php?f=12&t=2119.

**Comment by mdgood** [comment]
This point was also raised by @cecilios in #356.

**Comment by mdgood** [comment]
Pull request #371 addresses this issue. @cecilios and @DavidMWebber, as you both have brought up this issue, could you please review if you have the chance? Thanks for raising this issue.

**Comment by cecilios** [comment]
Thanks a lot. The added text fully clarifies this issue.

**Comment by DavidMWebber** [comment]
Hi Michael,

 

Thanks for this and sorry for a slow reply.  It’s fine that the issue is resolved.  

Dave



David Webber
Mozart Music Software
https://www.mozart.co.uk
