### ISSUE TITLE
Feature request: JSON conversion

### ISSUE THREAD

**Issue by patricio1979** [w3c/musicxml#435]
Could be an ordering of the <direction> tab? It seems that it cannot be ordered in JSON files and elements like lines and wedges are lost in the measure. Also a mandatory x or y values in lines could solve this

**Comment by Jojo-Schmitz** [comment]
Would https://github.com/saebekassebil/musicjson help here?

**Comment by patricio1979** [comment]
I've tried but it didn't work; wrote to them as well.

An elegant solution would be to add the attribute x (absolute or relative) to the start element of all the directions; in this way wedges could be paired with its dependent note.
Do you think this could be done? At the moment I will try it manually

**Comment by GeorgeTailor** [comment]
@scoresmexico 
MusicXML relies on XML order preservation of different types in multiple elements, for example `measure` -> `note`, `note`, `note`, `backup`, `note`, `note`, `note`.
That means that storing them as an object will produce incorrect results, since JSON is not order-aware way of presenting some data.
You could potentially treat everything as an array, you could use any XML -> JSON converter out there for this task.

**Comment by mdgood** [comment]
What is the problem that you are trying to solve? The adage of JSON for data and XML for documents still seems appropriate. Musical scores work much more like documents than plain data, hence the continued preference for XML even in a new format like MNX.

**Comment by patricio1979** [comment]
I'm new at programming but XML parsing has been pretty difficult to me.
When working with JSON I can parse de score more as a map rather than a sequence.
But it is alright. What I'm implementing is adding two attributes to the <direction> elements: "default-x" and measure "number". With these two I can convert musicXML to JSON with a Sublime text 3 extension.
This solution helps me to search elements in the score, attach them to an indexed <note> and get histograms.

MNX is something that I never saw before, it looks very promising... if lines and ornaments could be referred to the event as well it would be great. Also if events could be indexed with attributes as well.

Thanks for the time
