### ISSUE TITLE
Suggestion: Enable discussions on this repo

### ISSUE THREAD

**Issue by infojunkie** [w3c/musicxml#441]
Since the old [MusicXML forum](https://forums.makemusic.com/viewforum.php?f=12) closed, there's a lack of public space where the many users of MusicXML can discuss issues and share experiences. The mailing list public-music-notation@w3.org is not easily discoverable, and seems to be only used by members of the working group (even though it's public).

I suggest to use the GitHub "Discussions" feature on this repo as a public forum.

**Comment by mdgood** [comment]
@infojunkie Thank you for this suggestion. This seems like a promising idea. We'll take a closer look and get back to you soon.

**Comment by mdgood** [comment]
Discussions are now enabled and available at https://github.com/w3c/musicxml/discussions. Thank you again @infojunkie for this suggestion!
