### ISSUE TITLE
Request for clarification of ornament specification

### ISSUE THREAD

**Issue by drpond1** [w3c/musicxml#462]
For the version 4 specification:

 The ornament section  has the phrase ,"In this order (Zero or more times)" and then  the phrase  "Exactly one of the following"

   and below that is a list that includes ```<trill-mark>``` and  ```<wavy-line>```
  
I first assumed this meant that you could not include  ```<trill-mark>``` and ```<wavy-line>``` in the same ornament section.   However the 
```<trill-mark>``` example shows it is allowed.   Of course,  you could say that since multiple occurrences are allowed  this is ok.   But then,    i am not sure what is meant by "exactly one".

   I suspect you mean something like:  zero or more  Items from the list below, with duplications allowed,  that follows the ordering as shown.

**Comment by mdgood** [comment]
The indentation matters in this documentation. The `<ornaments>` element has zero or more sequences that contain a choice of exactly one of the 15 child elements, followed by zero or more `<accidental-mark>` elements that apply to that choice of ornament.

This part of the documentation is generated directly from the W3C XML Schema, which is defined in a way that satisfies requirements such as unique particle attribution. Sometimes that may not be as easy to read as something more narrative, but it is more precise. The examples are there to complement the formal description.

I hope this helps. If something is still unclear please let us know. It might help to reference the [XSD definition](w3.org/2021/06/musicxml40/listings/musicxml.xsd/) to see how the specification definitions are working. Search for `<xs:complexType name="ornaments">`.

**Comment by drpond1** [comment]
Thank you for the clarification.   I now see my mistake.
The documentation is fine as is.    You can close the issue.
