### ISSUE TITLE
Is it realy "effect.stamp" and not rather "effect.stomp"?

### ISSUE THREAD

**Issue by Jojo-Schmitz** [w3c/musicxml#463]
See https://github.com/w3c/musicxml/blob/49f2fd5b757f2ca251a3f5448a11e386e5dd42a9/schema/sounds.xml#L285

**Comment by mdgood** [comment]
Yes. The words "stamp" and "stomp" are synonymous in English in this context. (Definitely in American English, and I believe in British English as well.)

**Comment by Jojo-Schmitz** [comment]
But stamp has also other meanings, stomp would be far less ambiguous

**Comment by mdgood** [comment]
Perhaps, but It has been this way for over 10 years since MusicXML 3.0, so we will not be changing it now.

**Comment by Jojo-Schmitz** [comment]
And while adding `effect.stomp` might work, it'd just raise further confusion about the difference.
