### ISSUE TITLE
Are chords (harmonies) transposed or not?

### ISSUE THREAD

**Issue by mogenslundholm** [w3c/musicxml#474]
Are chords (harmonies) transposed or not?
Retired - didn't really think I should look at my program and MusiicXml again but ...

How did I get a problem?
I used MuseScore to transpose the melody to a Bb-instrument. And noted that the chords/harmonies were transposed also. To me this is an error - the chords are not played on the clarinet, but chords are played on some other instrument.
However - I cannot find anything in the MusicXml-specification about this. 

So,  in MusicXml: Are chords (harmonies) transposed or not?

![Musicxml](https://user-images.githubusercontent.com/3636047/202836142-9d2741e7-258d-4a1b-98c8-a15cfbd4b7e6.jpg)

On the picture you see the original melody and the transposed part for Bb-clarinet. The chords are changed and saved in the MusicXml-file as transposed. (And my program plays A instead of G-chord)

**Comment by mdgood** [comment]
@mogenslundholm If the chords are associated with a transposed part, then the chords are transposed as well. The player of a transposed part is not going to expect chord symbol pitches to be in concert pitch. The [`<transpose>` documentation](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/transpose/) refers to pitches in general, not just those represented with the `<pitch>` element.

**Comment by mogenslundholm** [comment]
Hello Michael

Thanks - I will change my program. But I was surprised, when I should play guitar-chords to a clarinet.
I cannot distribute my program any more. The price for the certificate has exploded, so now Microsoft writes that my program may be dangerous. (gave up Apple also). But I am still allowed to use my own computer and work with music.

Regards
Mogens

**Comment by mscuthbert** [comment]
Sorry for the cert issues @mogenslundholm -- empathy.
