### ISSUE TITLE
SMuFL ('other') accidentals not recognised

### ISSUE THREAD

**Issue by s-socha** [w3c/musicxml#482]
Hello,

It seems that Extended Helmholtz-Ellis SMuFL accidentals are not recognised by MuseScore 4 upon importing MusicXML 4 files. See attached screenshot and MusicXML text.

I'm not sure if the issue is my syntax or MuseScore's support for SMuFL accidentals.

[SMuFL_accidentals_test.odt](https://github.com/w3c/musicxml/files/10419567/SMuFL_accidentals_test.odt)

![SMuFL_accidentals_test_MuseScore4](https://user-images.githubusercontent.com/118038567/212525617-fcc713bf-e802-40f3-bc2d-49c545fab62a.png)

**Comment by Jojo-Schmitz** [comment]
I guess that's an issue you should rather bring up with MuseScore.
I assume that this just hasn't been implemented there.

Might then be a question to @lvinken

[SMuFL_accidentals_test.musicxml.txt](https://github.com/w3c/musicxml/files/10420026/SMuFL_accidentals_test.musicxml.txt)

**Comment by Jojo-Schmitz** [comment]
Might then be a question to @lvinken

**Comment by s-socha** [comment]
> I guess that's an issue you should rather bring up with MuseScore. I assume that this just hasn't been implemented there.
> 
> Might then be a question to @lvinken
> 
> [SMuFL_accidentals_test.musicxml.txt](https://github.com/w3c/musicxml/files/10420026/SMuFL_accidentals_test.musicxml.txt)

Thanks @Jojo-Schmitz; I'll discuss with MuseScore. Just to double-check - are the lines in my MusicXML file that begin with "<accidental smufl=..." written correctly?

**Comment by Jojo-Schmitz** [comment]
See also https://github.com/musescore/MuseScore/issues/15903

**Comment by lvinken** [comment]
The smufl attribute indeed has not been implemented in MuseScore's MusicXML importer. The syntax in the attached MusicXML file is correct. Note that MuseScore always does a schema validation, incorrect syntax would have been detected.

**Comment by rettinghaus** [comment]
Works in MuseScore 4.2:

![image](https://github.com/w3c/musicxml/assets/7693447/75263869-b99e-4197-bcee-49b5a00c0a0a)

@mscuthbert I think this issues can be closed.

**Comment by mscuthbert** [comment]
Thanks Klaus. It's been a busy week but hoping to look over all your amazing contributions this weekend.
