### ISSUE TITLE
Update MusicXML media types to W3C organization

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#51]
The media types [application/vnd.recordare.musicxml](https://www.iana.org/assignments/media-types/application/vnd.recordare.musicxml) and [application/vnd.recordare.musicxml+xml](https://www.iana.org/assignments/media-types/application/vnd.recordare.musicxml+xml) are registered at the IANA for use by compressed and uncompressed MusicXML files respectively. For the next MusicXML release we may want to update these media types to reflect the transfer of MusicXML development to the W3C Music Notation Community Group. 

This is related to issue #50 about adding MusicXML Uniform Type Identifiers, since the current UTI developed by Neuratron with MakeMusic's assistance uses a similar com.recordare identification, and the UTI definitions reference the media type names.

**Comment by mdgood** [comment]
As a first step, we want to at least change the responsibility for this media type from myself at Recordare to the W3C Music Notation Community Group. According to RFC 6838, "The owner of a media type may pass responsibility to another person or agency by informing the IANA; this can be done without discussion or review." So this step should be simple. I have emailed the first author of RFC 6838 about how to do this.

**Comment by mdgood** [comment]
This transfer request is now logged at the IANA as  [IANA #944875].

**Comment by mdgood** [comment]
IANA has updated responsibility of these media types to the W3C Music Notation Community Group, as you can see at https://www.iana.org/assignments/media-types/media-types.xhtml.

**Comment by mdgood** [comment]
Since our work is now at W3C, we may have the option to register in the standards tree as application/musicxml (or application/musicxml+zip) and application/musicxml+xml.

**Comment by adrianholovaty** [comment]
My two cents: application/musicxml is easier to remember (and less prone to typos) than application/org.w3c.musicxml. If application/musicxml is available, that gets my vote!

**Comment by mdgood** [comment]
The group consensus at the Musikmesse meeting was to go ahead with the application/musicxml and application/musicxml+xml proposal.

**Comment by mdgood** [comment]
After reviewing [RFC-6839](https://tools.ietf.org/html/rfc6839), it seems best to have the compressed MusicXML file use the application/musicxml+zip media type.

**Comment by mdgood** [comment]
Pull request #206 addresses this issue.

**Comment by mdgood** [comment]
It turns out that the standards tree is generally not available to W3C Community Group reports. One exception was made in the past, but those exceptions require a formal specification document that MusicXML currently does not have.

Given this, I recommend that we move back to application/vnd.recordare.musicxml and application/vnd.recordare.musicxml+xml. I don't think updating to another name within the vnd tree is worth the effort at this point. The timing of IANA reviews on the vendor tree is also indeterminate which doesn't work well with trying to complete our beta test by the end of June. I will update the related issues #50 and #185 accordingly.

We do have these media types updated to W3C Music Notation Community Group ownership, so we have gotten part of this issue done.

**Comment by mdgood** [comment]
Pull request #211 reverts back to the current MusicXML media types.
