### ISSUE TITLE
Add complete SMuFL dynamics range

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#52]
MusicXML could add support for the complete SMuFL dynamics range U+E520–U+E54F for better interoperability between applications. The range is documented at http://w3c.github.io/smufl/gitbook/tables/dynamics.html.

Most of these symbols are already represented in MusicXML 3.0. The ones that would need to be added as of SMuFL 1.19 are:
- Niente as an "n" dynamic symbol (U+E526)
- The pf dynamic (U+E52E)
- Sforzato piano sfzp (U+E53A)

Originally this issue included support for the Messa di voce symbol at slot U+E540. This has been removed and replaced with support for the soft accent symbols in the articulations supplement range as part of issue #131.

**Comment by jsawruk** [comment]
Proposed solution:
Add new dynamics elements in common.mod and musicxml.xsd to support the above SMuFL 1.20 dynamic elements. 

Proposed elements:
Niente - `<n />` (alternate proposal - `<niente />`) - U+E526 (Could this also be mapped to U+E541, niente for hairpins? )
pf dynamic - `<pf />` - U+E52E
Sforzato piano - `<sfzp />` - U+E53A
Messa di voce - `<messa-di-voce />` (alternate proposal - `<swell>`) - U+E540

**Comment by mdgood** [comment]
Thanks, Jeremy. The niente for hairpins is already represented by the niente attribute of the wedge element. So I like the `<n/>` proposal better as it is more consistent with the other letter dynamics.

Since this issue was written up, SMuFL has added an [articulation supplement](https://w3c.github.io/smufl/gitbook/tables/articulation-supplement.html) range that includes many soft accent characters. Those seem more generally useful than the messa di voce symbol here. Perhaps we want to remove the messa di voce element from this issue, and add a new issue for supporting the articulation supplement range?

**Comment by jsawruk** [comment]
I agree that removing the messa di voce element from this issue and creating a new issue for the articulation supplement range makes more sense. The other dynamics in this issue are text, while the messa di voce is a graphical element, and the articulation supplement supports a wider range for messa di voce anyway.

**Comment by mdgood** [comment]
Pull request #136 addressed this issue.

**Comment by mdgood** [comment]
Issue #216 and pull request #217 improved the handling of these new elements when converting to MusicXML 3.0.
