### ISSUE TITLE
documentation: Example for `<senza-misura>` is misleading

### ISSUE THREAD

**Issue by lemzwerg** [w3c/musicxml#544]
The [online documentation](https://www.w3.org/2021/06/musicxml40/musicxml-reference/examples/senza-misura-element/) shows the following image for the sample code

```xml
<time>
   <senza-misura/>
</time>
```

![image](https://github.com/user-attachments/assets/83468581-9fb7-45f8-83a4-22f98d44d793)

which I think is misleading: A single `<time>` instruction doesn't cause *two* senza-misura time symbols three bars away.  A casual reader could get the impression that the `<senza-misura/>` element is persisting for more than a single `<time>` element.

**Comment by mscuthbert** [comment]
Good catch.  If you'd like to crop the image in a PR I'd appreciate it.

**Comment by lemzwerg** [comment]
Done, see #548.
