### ISSUE TITLE
Add clef distinctions when switching between concert and transposing scores

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#55]
Another source of confusion when switching between concert and transposing scores are clefs that display differently in the two views. MusicXML could add the ability to suggest when the clef display should should change when moving to the view not encoded in the MusicXML file. Michael Cuthbert (@mscuthbert) suggested this on the MusicXML forum:

> Another needed element is to specify Clef objects that only appear in one score or the other (or which are substituted for another when switching views). The bass clarinet should be in treble throughout in a modern transposing score, but might switch between Treble and Bass on the C-conductor's score.

See the MusicXML forum discussion at http://forums.makemusic.com/viewtopic.php?f=12&t=2395#p6481.

**Comment by mdgood** [comment]
If we reframe this issue in terms of differences between a concert score and a transposed part, perhaps #278 could address this.

**Comment by jsawruk** [comment]
I personally think this should be reframed as the difference between a concert score and a transposed part. This would be the least ambiguous in my opinion.

**Comment by mdgood** [comment]
In the forum discussion referenced above, @joeberkovitz suggested "Perhaps this argues for a `<concert-attributes>` element that can contain an alternative clef and transposition to the regular (transposed) `<attributes>` element."

This idea seems promising, and even better if we can emphasize the use for concert score and transposed parts. I've made a proposal in #279 for a new `<for-part>` child element of the `<attributes>` element that could contain this clef and transposition information.

**Comment by mdgood** [comment]
Addressed by #340.
