### ISSUE TITLE
Add more polygonal options to enclosure-shape element

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#86]
MusicXML 3.0 enclosures lack polygonal shapes with more than 4 sides despite their use in published music. Adding pentagon, hexagon, heptagon, octagon, enneagon, and decagon values to the enclosure-shape simple type would get up to 10 sides and cover the majority of enclosures seen in practice. Rare pieces do seem to get up to pentadecagons or 15 sides.

This issue was raised by a MusicXML QA tester in a private email.

**Comment by joeberkovitz** [comment]
I think this issue would benefit from wider MNCG input and should be dealt with as a lower-priority issue outside of 3.1.

**Comment by mdgood** [comment]
@joeberkovitz, could you please elaborate more on why this would be outside of version 3.1? It seems like a simple addition of enumeration values, similar to many other 3.1 issues. 

I do understand that this is getting into issues of style and appearance that we want to revisit in MNX. But we are not adding a new way of specifying appearance here. We are simply extending the existing MusicXML 3.0 construct to handle enclosures that are used in published music, yet cannot transfer correctly between applications when using MusicXML 3.0.

**Comment by joeberkovitz** [comment]
@mdgood Thanks for explaining - I think including this is OK given that there are lots of other things we'd have to revisit in MNX already and this isn't adding more complexity

**Comment by mdgood** [comment]
Thanks, Joe. As suggested above, the proposed solution would be to add the "pentagon", "hexagon", "heptagon", "octagon", "enneagon", and "decagon" enumeration values to the enclosure-shape simple type. The enumeration values in this type are not in alphabetical order, so these will just be appended to the end of the current enumeration values. Corresponding changes would be made to the enclosure-shape entity in the common.mod file and to the to30.xsl file.

**Comment by mdgood** [comment]
It looks like "nonagon" is more frequently used than "enneagon" for a 9-sided polygon, so I recommend we use that as the enumeration value instead.

**Comment by jsawruk** [comment]
I agree, I think nonagon is more frequent. I had never heard of enneagon until you wrote this (my spell checker doesn't recognize this word, but it does recognize nonagon).

**Comment by mdgood** [comment]
Pull requst #164 addresses this issue.
