### ISSUE TITLE
Add support for distinguishing breve notehead styles

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#89]
MusicXML 3.0 represents breve notes and rests, but does not distinguish between the round and square styles for the breve notehead. These are glyphs U+E0A0 and U+E0A1 in the SMuFL [Noteheads range](http://w3c.github.io/smufl/gitbook/tables/noteheads.html), glyphs U+E1D0 and U+E1D1 in the SMuFL [Individual notes](http://w3c.github.io/smufl/gitbook/tables/individual-notes.html) range, and glyphs U+ECA0 and U+ECA1 in the SMuFL [Metronome marks](http://w3c.github.io/smufl/gitbook/tables/metronome-marks.html) range.

This distinction might be made at the document level in the defaults element, or on a note-by-note basis.

This issue arose while analyzing MusicXML 3.0 for SMuFL support in preparation for the 2015 MusicXML community meeting at Musikmesse.

**Comment by joeberkovitz** [comment]
If this is to be done in a way beyond using the `other-` element then we should probably defer this.

**Comment by mdgood** [comment]
Issue #110 is now a more general method of addressing this without adding new enumeration values for specific stylistic distinctions. It is closely related to the other- elements.

**Comment by mdgood** [comment]
Pull request #150 addressed this issue.
