### ISSUE TITLE
Add support for ties with metronome marks

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#92]
MusicXML 3.0 includes support for tuplets within the metronome element. MusicXML could expand its support for complex metric equations by adding support for ties within the metronome element. Elaine Gould's _Behind Bars_ gives an example in the last figure on page 186. SMuFL supports this as well with glyph U+E1FD in the [Beamed groups of notes](http://w3c.github.io/smufl/gitbook/tables/beamed-groups-of-notes.html) range.

**Comment by rlanyon** [comment]
I think this would definitely be useful. Irregular time signatures often need these sorts of equations, e.g. if you're changing to/from 5/8 you might want to say something about the tempo of minim-tied-to-quaver. There are quite a few examples in Bartók, even in his straightforward folk and educational pieces.

**Comment by mdgood** [comment]
This could be implemented by adding an optional metronome-tied element before the metronome-tuplet element within the metronome-note complex type. This element would have a new metronome-tied complex type, specifying an empty element with a required type attribute:

```
	<xs:complexType name="metronome-tied">
		<xs:attribute name="type" type="start-stop" use="required"/>
	</xs:complexType>
```

**Comment by rlanyon** [comment]
This would definitely be useful for metric modulations. I wonder if it would be possible to have a similar beat-unit-tied element (coming after beat-unit-dot) in the case of simple metronome marks too? For example, Bartók's Mikrokosmos 113, which is in 7/8, has a metronome mark of "Allegro molto, minim-tied-to-dotted-crotchet = 49", and I don't think that can be represented using the metronome-note types.

**Comment by mdgood** [comment]
Are you envisioning a beat-unit-tied element whose content is the type of the second tied note? That could work without causing too many problems for existing software. If we tried to add another beat-unit element in addition to beat-unit-tied, that could get tricky.

**Comment by mdgood** [comment]
Or maybe the beat-unit-tied element contains both beat-unit and beat-unit-dot elements. We would need something like that for the Bartók example.

**Comment by rlanyon** [comment]
I think either of those could work. In principle it's possible (though rare) for more than two notes to be tied in a metronome mark, but as long as multiple beat-unit/beat-unit-dot elements can be contained within the beat-unit-tied element then that shouldn't be a problem either way.

**Comment by mdgood** [comment]
We could support that by adding a new beat-unit-tied element whose content is a beat-unit group (that is, a beat-unit element followed by 0 or more beat-unit-dot elements):
```
<xs:complexType name="beat-unit-tied">
	<xs:group ref="beat-unit"/>
</xs:complexType>
```
The overall definition for the metronome-note and metronome elements, minus documentation for brevity, would then look something like this:
```
<xs:complexType name="metronome-note">
	<xs:sequence>
		<xs:element name="metronome-type" type="note-type-value"/>
		<xs:element name="metronome-dot" type="empty" minOccurs="0" maxOccurs="unbounded"/>
		<xs:element name="metronome-beam" type="metronome-beam" minOccurs="0" maxOccurs="unbounded"/>
		<xs:element name="metronome-tied" type="metronome-tied" minOccurs="0"/>
		<xs:element name="metronome-tuplet" type="metronome-tuplet" minOccurs="0"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="metronome">
	<xs:choice>
		<xs:sequence>
			<xs:group ref="beat-unit"/>
			<xs:element name="beat-unit-tied" type="beat-unit-tied" minOccurs="0" maxOccurs="unbounded"/>
			<xs:choice>
				<xs:element name="per-minute" type="per-minute"/>
				<xs:sequence>
					<xs:group ref="beat-unit"/>
					<xs:element name="beat-unit-tied" type="beat-unit-tied" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:choice>
		</xs:sequence>
		<xs:sequence>
			<xs:element name="metronome-arrows" type="empty" minOccurs="0"/>
			<xs:element name="metronome-note" type="metronome-note" maxOccurs="unbounded"/>
			<xs:sequence minOccurs="0">
				<xs:element name="metronome-relation" type="xs:string"/>
				<xs:element name="metronome-note" type="metronome-note" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:choice>
	<xs:attributeGroup ref="print-style-align"/>
	<xs:attributeGroup ref="justify"/>
	<xs:attribute name="parentheses" type="yes-no"/>
	<xs:attributeGroup ref="optional-unique-id"/>
</xs:complexType>
```

The XSLT converting to MusicXML 3.0 would remove all the beat-unit-tied and metronome-tied elements.

@rlanyon, does this look like that should cover everything?

**Comment by rlanyon** [comment]
Yes, I think that covers it!

**Comment by mdgood** [comment]
Pull request #192 addresses this issue. @rlanyon, would you be able to review this pull request to make sure everything is as you expect? Thanks!

**Comment by rlanyon** [comment]
This all looks fine to me, thanks.
