### ISSUE TITLE
Add complete SMuFL tremolos range

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#99]
MusicXML could complete its support for the SMuFL tremolos range U+E220–U+E23F for better interoperability between applications. The range is documented at http://w3c.github.io/smufl/gitbook/tables/tremolos.html.

MusicXML 3.0 already supports the combining and fingered tremolo symbols. Completing the range would involve adding:
- The buzz roll and Penderecki unmeasured tremolo glyphs U+E22A and U+E22B, related to stem display issue #96 
- The Wieniawski unmeasured tremolo glyphs U+E22C and U+E22D
- The divided measured tremolo glyphs U+E22E-U+E231
- The Stockhausen irregular tremolo glyph U+E232

This issue arose while analyzing MusicXML 3.0 for SMuFL support in preparation for the 2015 MusicXML community meeting at Musikmesse.

**Comment by ericcarraway** [comment]
My first comment on `w3c` - pardon me if I'm in the wrong place.

I'd like to "plus one" this issue and advocate support for buzz rolls in the MusicXML standard.

**Comment by mdgood** [comment]
Thank you for the feedback! How would you propose we do this? Perhaps we could add buzz-roll as a new technical element, and leave the rest of these to the other-ornament element. It would seem the buzz roll is more common than the other symbols in this range, except perhaps the divided measured tremolo glyphs. Does that sound good or do you see a better way to add this?

**Comment by ericcarraway** [comment]
If we could get it done with the existing tremolo element, it might be unnecessary to add another element definition.

Considering that we have this,
```
<notations>
 <ornaments>
  <tremolo type="single">1</tremolo>
</notations>
...
  <tremolo type="single">2</tremolo>
...
  <tremolo type="single">3</tremolo>
```
Would the following be possible?
```
  <tremolo type="single">z</tremolo>
```
<img width="350" alt="tremolo-sibelius" src="https://cloud.githubusercontent.com/assets/6632454/22850937/73198a82-efd9-11e6-9737-79d51f8f1b00.png">

What's currently written as _"integer from zero to eight"_
could instead be _"integer from zero to eight, or z"_

**Comment by domn1995** [comment]
I would love to see support for the unmeasured tremolo (z). What ericcarraway has suggested seems like a sensible solution.

**Comment by mdgood** [comment]
This is the most popular SMuFL issue that was not previously included in the V3.1 milestone, so I have added it to V3.1. Here is my proposal for addressing the issue that 

1) Create a new tremolo-type simple type to replace the start-stop-single type. This would add a new unmeasured value.
```
<xs:simpleType name="tremolo-type">
	<xs:annotation>
		<xs:documentation>The tremolo-type is used to distinguish multi-note, single-note, and unmeasured tremolos.</xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:token">
		<xs:enumeration value="start"/>
		<xs:enumeration value="stop"/>
		<xs:enumeration value="single"/>
		<xs:enumeration value="unmeasured"/>
	</xs:restriction>
</xs:simpleType>
```
2) We could then add a new smufl attribute to the tremolo element that would only be used for an unmeasured type. It would specify a glyph to use from the SMuFL tremolos range. We could say that the default is buzzRoll if the attribute is not present. The tremolo type would then look like this:
```
<xs:complexType name="tremolo">
	<xs:annotation>
		<xs:documentation>The tremolo ornament can be used to indicate single-note, double-note, or unmeasured tremolos. Single-note tremolos use the single type, double-note tremolos use the start and stop types, and unmeasured tremolos use the unmeasured type. The default is "single" for compatibility with Version 1.1. The text of the element indicates the number of tremolo marks and is an integer from 0 to 8. Note that the number of attached beams is not included in this value, but is represented separately using the beam element. The value should be 0 for unmeasured tremolos.

When using double-note tremolos, the duration of each note in the tremolo should correspond to half of the notated type value. A time-modification element should also be added with an actual-notes value of 2 and a normal-notes value of 1. If used within a tuplet, this 2/1 ratio should be multiplied by the existing tuplet ratio.

The smufl attribute specifies the glyph to use from the SMuFL tremolos range for an unmeasured tremolo. It is ignored for other tremolo types. The SMuFL buzzRoll glyph is used by default if the attribute is missing.

Using repeater beams for indicating tremolos is deprecated as of MusicXML 3.0.</xs:documentation>
	</xs:annotation>
	<xs:simpleContent>
		<xs:extension base="tremolo-marks">
			<xs:attribute name="type" type="tremolo-type" default="single"/>
			<xs:attributeGroup ref="print-style"/>
			<xs:attributeGroup ref="placement"/>
			<xs:attributeGroup ref="smufl"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>
```

3) The start-stop-single type documentation uses tremolos as its example. This should be replaced with something that still uses the start-stop-single type, like groupings.

@ericcarraway and @domn1995, what do you think? I wanted to keep the tremolo element content as an integer for better compatibility with MusicXML 3.0, while also allowing flexibility to specify different SMuFL tremolo glyphs.

**Comment by ericcarraway** [comment]
Thanks, @mdgood!

The only thing I'll add here is a link to the [tremolo glyphs in the SMuFL docs](
http://www.smufl.org/version/latest/range/tremolos/), in case someone comes along in the future looking for this information.

`buzzRoll` is **U+E22A**

___

http://www.smufl.org/version/latest/range/tremolos/

![screen shot 2017-04-03 at 7 41 47 am](https://cloud.githubusercontent.com/assets/6632454/24609795/bbb13ec6-1841-11e7-81d9-4e9df9cbc0ca.png)

**Comment by mdgood** [comment]
Pull request #200 addresses this issue.
